/**
 * @fileoverview Pure-logic planner that builds pending channel list from config.
 * @module core/channel-setup/ChannelSetupPlanner
 * @version 1.0.0
 */

import type {
    ChannelSetupConfig,
    ChannelSetupEstimates,
    SetupStrategyKey,
} from './types';
import { DEFAULT_MIN_ITEMS_PER_CHANNEL, DEFAULT_STRATEGY_PRIORITIES } from './constants';
import { DEFAULT_CHANNEL_SETUP_MAX } from '../../modules/scheduler/channel-manager/constants';
import type {
    PlexLibraryType,
    PlexCollection,
    PlexPlaylist,
    PlexTagDirectoryItem,
} from '../../modules/plex/library';
import type {
    ChannelConfig,
    ContentFilter,
    SortOrder,
    BuildStrategy,
} from '../../modules/scheduler/channel-manager';

export type PendingChannel = {
    name: string;
    contentSource: ChannelConfig['contentSource'];
    playbackMode: ChannelConfig['playbackMode'];
    shuffleSeed: number;
    blockSize?: number;
    contentFilters?: ContentFilter[];
    sortOrder?: SortOrder;
    isAutoGenerated?: boolean;
    buildStrategy?: BuildStrategy;
    sourceLibraryId?: string;
    sourceLibraryName?: string;
    lineupReplicaIndex?: number;
    isSequentialVariant?: boolean;
};

interface ChannelSetupPlanInput {
    config: ChannelSetupConfig;
    libraries: PlexLibraryType[];
    playlists: PlexPlaylist[];
    collectionsByLibraryId: Map<string, PlexCollection[]>;
    genresByLibraryId: Map<string, PlexTagDirectoryItem[]>;
    directorsByLibraryId: Map<string, PlexTagDirectoryItem[]>;
    yearsByLibraryId: Map<string, PlexTagDirectoryItem[]>;
    actorsByLibraryId: Map<string, PlexTagDirectoryItem[]>;
    studiosByLibraryId: Map<string, PlexTagDirectoryItem[]>;
    warnings: string[];
    seedFor: (value: string) => number;
}

interface ChannelSetupPlan {
    pendingChannels: PendingChannel[];
    estimates: ChannelSetupEstimates;
    warnings: string[];
    skipped: number;
    reachedMaxChannels: boolean;
}

interface ChannelIdentityCandidate {
    contentSource: ChannelConfig['contentSource'];
    contentFilters?: ContentFilter[];
    sortOrder?: SortOrder;
    playbackMode: ChannelConfig['playbackMode'];
    blockSize?: number;
    lineupReplicaIndex?: number;
    isSequentialVariant?: boolean;
}

interface ChannelDiffEntry {
    name: string;
    identityKey: string;
    channelId?: string;
    number?: number;
    isAutoGenerated?: boolean;
}

export interface ChannelDiffResult {
    created: ChannelDiffEntry[];
    removed: ChannelDiffEntry[];
    unchanged: ChannelDiffEntry[];
    matchedPairs: Array<{ existing: ChannelConfig; planned: PendingChannel }>;
    summary: { created: number; removed: number; unchanged: number };
    samples: { created: string[]; removed: string[]; unchanged: string[] };
}

type CategoryCandidate = {
    strategy: SetupStrategyKey;
    categoryKey: string;
    categoryLabel: string;
    baseSource: ChannelConfig['contentSource'];
    sourceLibraryId?: string;
    sourceLibraryName?: string;
    itemCount?: number;
};

const emptyEstimates = (): ChannelSetupEstimates => ({
    total: 0,
    collections: 0,
    playlists: 0,
    genres: 0,
    directors: 0,
    decades: 0,
    recentlyAdded: 0,
    studios: 0,
    actors: 0,
});

export function buildChannelSetupPlan(input: ChannelSetupPlanInput): ChannelSetupPlan {
    const {
        config,
        libraries,
        playlists,
        collectionsByLibraryId,
        genresByLibraryId,
        directorsByLibraryId,
        yearsByLibraryId,
        actorsByLibraryId,
        studiosByLibraryId,
        warnings,
        seedFor,
    } = input;

    let skipped = 0;

    const requestedMax = Number.isFinite(config.maxChannels) ? config.maxChannels : DEFAULT_CHANNEL_SETUP_MAX;
    const effectiveMaxChannels = Math.max(1, Math.floor(requestedMax));
    const requestedMinItems = Number.isFinite(config.minItemsPerChannel) ? config.minItemsPerChannel : DEFAULT_MIN_ITEMS_PER_CHANNEL;
    const minItems = Math.max(1, Math.floor(requestedMinItems));

    const selectedLibraries = libraries
        .filter((lib) => config.selectedLibraryIds.includes(lib.id))
        .sort((a, b) => a.title.localeCompare(b.title));

    const getStrategyPriority = (strategy: SetupStrategyKey): number => {
        const configured = config.strategyConfig[strategy]?.priority;
        if (Number.isFinite(configured)) {
            return Math.max(1, Math.floor(Number(configured)));
        }
        return DEFAULT_STRATEGY_PRIORITIES[strategy];
    };

    const isStrategyEnabled = (strategy: SetupStrategyKey): boolean => {
        return config.strategyConfig[strategy]?.enabled === true;
    };

    const getStrategyScope = (strategy: SetupStrategyKey): 'per-library' | 'cross-library' => {
        return config.strategyConfig[strategy]?.scope === 'cross-library' ? 'cross-library' : 'per-library';
    };

    const strategyBuckets: Record<SetupStrategyKey, PendingChannel[]> = {
        collections: [],
        playlists: [],
        genres: [],
        directors: [],
        decades: [],
        recentlyAdded: [],
        studios: [],
        actors: [],
    };

    const addStrategyChannel = (strategy: SetupStrategyKey, channel: PendingChannel): void => {
        strategyBuckets[strategy].push({
            ...channel,
            buildStrategy: strategy,
            lineupReplicaIndex: channel.lineupReplicaIndex ?? 0,
            isSequentialVariant: channel.isSequentialVariant === true,
        });
    };

    const sortCategoryCandidates = (candidates: CategoryCandidate[]): CategoryCandidate[] => {
        const compare = (a: string, b: string): number => {
            if (a === b) return 0;
            return a < b ? -1 : 1;
        };
        return [...candidates].sort((a, b) => {
            const countDiff = (b.itemCount ?? 0) - (a.itemCount ?? 0);
            if (countDiff !== 0) return countDiff;
            const aLabel = a.categoryLabel.toLowerCase();
            const bLabel = b.categoryLabel.toLowerCase();
            const labelDiff = compare(aLabel, bLabel);
            if (labelDiff !== 0) return labelDiff;
            return compare(a.categoryKey, b.categoryKey);
        });
    };

    const sortTags = (tags: PlexTagDirectoryItem[]): PlexTagDirectoryItem[] => {
        return [...tags].sort((a, b) => {
            const countDiff = (b.count || 0) - (a.count || 0);
            if (countDiff !== 0) return countDiff;
            return a.title.localeCompare(b.title);
        });
    };

    const toDecade = (tag: PlexTagDirectoryItem): number | null => {
        const year = Number.parseInt(tag.title, 10);
        if (!Number.isFinite(year)) {
            return null;
        }
        return Math.floor(year / 10) * 10;
    };

    // 0. Server-wide Playlists
    if (isStrategyEnabled('playlists')) {
        const orderedPlaylists = [...playlists].sort((a, b) => {
            const countDiff = b.leafCount - a.leafCount;
            if (countDiff !== 0) return countDiff;
            return a.title.localeCompare(b.title);
        });
        for (const pl of orderedPlaylists) {
            if (pl.leafCount >= minItems) {
                addStrategyChannel('playlists', {
                    name: pl.title,
                    contentSource: {
                        type: 'playlist',
                        playlistKey: pl.ratingKey,
                        playlistName: pl.title,
                    },
                    playbackMode: 'shuffle',
                    shuffleSeed: seedFor(`playlist:${pl.ratingKey}`),
                    isAutoGenerated: true,
                });
            } else {
                skipped++;
            }
        }
    }

    const actorStudioCombineMode = config.actorStudioCombineMode ?? 'separate';

    for (const library of selectedLibraries) {
        // 1. Collections
        if (isStrategyEnabled('collections')) {
            const collections = collectionsByLibraryId.get(library.id) ?? [];
            const candidates: CategoryCandidate[] = [];
            for (const collection of collections) {
                if (collection.childCount >= minItems) {
                    candidates.push({
                        strategy: 'collections',
                        categoryKey: collection.ratingKey,
                        categoryLabel: collection.title,
                        itemCount: collection.childCount,
                        baseSource: {
                            type: 'collection',
                            collectionKey: collection.ratingKey,
                            collectionName: collection.title,
                        },
                        sourceLibraryId: library.id,
                        sourceLibraryName: library.title,
                    });
                } else {
                    skipped++;
                }
            }
            for (const candidate of sortCategoryCandidates(candidates)) {
                addStrategyChannel('collections', {
                    name: candidate.categoryLabel,
                    contentSource: candidate.baseSource,
                    playbackMode: 'shuffle',
                    shuffleSeed: seedFor(`collection:${candidate.categoryKey}`),
                    isAutoGenerated: true,
                    sourceLibraryId: library.id,
                    sourceLibraryName: library.title,
                });
            }
        }

        // 2. Recently Added
        if (isStrategyEnabled('recentlyAdded')) {
            addStrategyChannel('recentlyAdded', {
                name: `${library.title} - Recently Added`,
                contentSource: {
                    type: 'library',
                    libraryId: library.id,
                    libraryType: library.type === 'movie' ? 'movie' : 'show',
                    includeWatched: true,
                },
                sortOrder: 'added_desc',
                playbackMode: 'sequential',
                shuffleSeed: seedFor(`recentlyAdded:${library.id}`),
                isAutoGenerated: true,
                sourceLibraryId: library.id,
                sourceLibraryName: library.title,
            });
        }

        // 3. Item Scanning Strategies (per-library only pass)
        if (isStrategyEnabled('genres') || isStrategyEnabled('directors') || isStrategyEnabled('decades')) {
            const genres = sortTags(genresByLibraryId.get(library.id) ?? []);
            const directors = sortTags(directorsByLibraryId.get(library.id) ?? []);
            const years = yearsByLibraryId.get(library.id) ?? [];

            if (isStrategyEnabled('genres') && getStrategyScope('genres') === 'per-library') {
                const candidates: CategoryCandidate[] = [];
                for (const genre of genres) {
                    if (genre.count < minItems) continue;
                    candidates.push({
                        strategy: 'genres',
                        categoryKey: `${library.id}:${genre.title.toLowerCase()}`,
                        categoryLabel: genre.title,
                        itemCount: genre.count,
                        baseSource: {
                            type: 'library',
                            libraryId: library.id,
                            libraryType: library.type === 'movie' ? 'movie' : 'show',
                            includeWatched: true,
                            libraryFilter: { genre: genre.title },
                        },
                        sourceLibraryId: library.id,
                        sourceLibraryName: library.title,
                    });
                }
                for (const candidate of sortCategoryCandidates(candidates)) {
                    addStrategyChannel('genres', {
                        name: `${library.title} - ${candidate.categoryLabel}`,
                        contentSource: candidate.baseSource,
                        playbackMode: 'shuffle',
                        shuffleSeed: seedFor(`genre:${library.id}:${candidate.categoryLabel}`),
                        isAutoGenerated: true,
                        sourceLibraryId: library.id,
                        sourceLibraryName: library.title,
                    });
                }
            }

            if (isStrategyEnabled('directors') && getStrategyScope('directors') === 'per-library') {
                const candidates: CategoryCandidate[] = [];
                for (const director of directors) {
                    if (director.count < minItems) continue;
                    candidates.push({
                        strategy: 'directors',
                        categoryKey: `${library.id}:${director.title.toLowerCase()}`,
                        categoryLabel: director.title,
                        itemCount: director.count,
                        baseSource: {
                            type: 'library',
                            libraryId: library.id,
                            libraryType: library.type === 'movie' ? 'movie' : 'show',
                            includeWatched: true,
                        },
                        sourceLibraryId: library.id,
                        sourceLibraryName: library.title,
                    });
                }
                for (const candidate of sortCategoryCandidates(candidates)) {
                    addStrategyChannel('directors', {
                        name: `${library.title} - ${candidate.categoryLabel}`,
                        contentSource: candidate.baseSource,
                        contentFilters: [{ field: 'director', operator: 'eq', value: candidate.categoryLabel }],
                        playbackMode: 'shuffle',
                        shuffleSeed: seedFor(`director:${library.id}:${candidate.categoryLabel}`),
                        isAutoGenerated: true,
                        sourceLibraryId: library.id,
                        sourceLibraryName: library.title,
                    });
                }
            }

            if (isStrategyEnabled('decades')) {
                const decadeCounts = new Map<number, number>();
                for (const yearTag of years) {
                    const decade = toDecade(yearTag);
                    if (decade === null) {
                        continue;
                    }
                    decadeCounts.set(decade, (decadeCounts.get(decade) || 0) + (yearTag.count || 0));
                }
                const sortedDecades = Array.from(decadeCounts.entries())
                    .filter((entry): entry is [number, number] => entry[1] >= minItems)
                    .sort((a, b) => a[0] - b[0])
                    .map(([decade]) => decade);

                for (const decade of sortedDecades) {
                    addStrategyChannel('decades', {
                        name: `${library.title} - ${decade}s`,
                        contentSource: {
                            type: 'library',
                            libraryId: library.id,
                            libraryType: library.type === 'movie' ? 'movie' : 'show',
                            includeWatched: true,
                        },
                        contentFilters: [
                            { field: 'year', operator: 'gte', value: decade },
                            { field: 'year', operator: 'lt', value: decade + 10 },
                        ],
                        playbackMode: 'shuffle',
                        shuffleSeed: seedFor(`decade:${library.id}:${decade}`),
                        isAutoGenerated: true,
                        sourceLibraryId: library.id,
                        sourceLibraryName: library.title,
                    });
                }
            }
        }
    }

    if (isStrategyEnabled('genres') && getStrategyScope('genres') === 'cross-library') {
        const grouped = new Map<string, { label: string; totalCount: number; sources: ChannelConfig['contentSource'][] }>();
        for (const library of selectedLibraries) {
            const tagItems = genresByLibraryId.get(library.id) ?? [];
            const genres = sortTags(tagItems);
            for (const genre of genres) {
                const key = genre.title.trim().toLowerCase();
                if (!key) continue;
                const entry = grouped.get(key) ?? { label: genre.title, totalCount: 0, sources: [] as ChannelConfig['contentSource'][] };
                entry.totalCount += genre.count;
                entry.sources.push({
                    type: 'library',
                    libraryId: library.id,
                    libraryType: library.type === 'movie' ? 'movie' : 'show',
                    includeWatched: true,
                    libraryFilter: { genre: genre.title },
                });
                grouped.set(key, entry);
            }
        }
        const candidates: CategoryCandidate[] = [];
        for (const [categoryKey, entry] of grouped.entries()) {
            if (entry.totalCount < minItems) continue;
            const baseSource: ChannelConfig['contentSource'] = entry.sources.length > 1
                ? { type: 'mixed', mixMode: 'interleave', sources: entry.sources }
                : entry.sources[0] ?? { type: 'manual', items: [] };
            candidates.push({
                strategy: 'genres',
                categoryKey,
                categoryLabel: entry.label,
                itemCount: entry.totalCount,
                baseSource,
            });
        }
        for (const candidate of sortCategoryCandidates(candidates)) {
            addStrategyChannel('genres', {
                name: candidate.categoryLabel,
                contentSource: candidate.baseSource,
                playbackMode: 'shuffle',
                shuffleSeed: seedFor(`genre:cross:${candidate.categoryKey}`),
                isAutoGenerated: true,
            });
        }
    }

    if (isStrategyEnabled('directors') && getStrategyScope('directors') === 'cross-library') {
        const grouped = new Map<string, { label: string; totalCount: number; sources: ChannelConfig['contentSource'][] }>();
        for (const library of selectedLibraries) {
            const tagItems = directorsByLibraryId.get(library.id) ?? [];
            const directors = sortTags(tagItems);
            for (const director of directors) {
                const key = director.title.trim().toLowerCase();
                if (!key) continue;
                const entry = grouped.get(key) ?? { label: director.title, totalCount: 0, sources: [] as ChannelConfig['contentSource'][] };
                entry.totalCount += director.count;
                entry.sources.push({
                    type: 'library',
                    libraryId: library.id,
                    libraryType: library.type === 'movie' ? 'movie' : 'show',
                    includeWatched: true,
                    libraryFilter: { director: director.title },
                });
                grouped.set(key, entry);
            }
        }
        const candidates: CategoryCandidate[] = [];
        for (const [categoryKey, entry] of grouped.entries()) {
            if (entry.totalCount < minItems) continue;
            const baseSource: ChannelConfig['contentSource'] = entry.sources.length > 1
                ? { type: 'mixed', mixMode: 'interleave', sources: entry.sources }
                : entry.sources[0] ?? { type: 'manual', items: [] };
            candidates.push({
                strategy: 'directors',
                categoryKey,
                categoryLabel: entry.label,
                itemCount: entry.totalCount,
                baseSource,
            });
        }
        for (const candidate of sortCategoryCandidates(candidates)) {
            addStrategyChannel('directors', {
                name: candidate.categoryLabel,
                contentSource: candidate.baseSource,
                playbackMode: 'shuffle',
                shuffleSeed: seedFor(`director:cross:${candidate.categoryKey}`),
                isAutoGenerated: true,
            });
        }
    }

    if (isStrategyEnabled('studios')) {
        const studioScope = getStrategyScope('studios');
        if (actorStudioCombineMode === 'combined' || studioScope === 'cross-library') {
            const combined = combineTagSources(selectedLibraries, studiosByLibraryId, 'studio');
            for (const tag of combined) {
                if (tag.totalCount < minItems) continue;
                addStrategyChannel('studios', {
                    name: tag.title,
                    contentSource: {
                        type: 'mixed',
                        mixMode: studioScope === 'cross-library' ? 'interleave' : 'sequential',
                        sources: tag.sources,
                    },
                    playbackMode: 'shuffle',
                    shuffleSeed: seedFor(`studio:${tag.key}`),
                    isAutoGenerated: true,
                });
            }
        } else {
            for (const library of selectedLibraries) {
                const tags = sortTags(studiosByLibraryId.get(library.id) ?? []);
                for (const tag of tags) {
                    if (tag.count < minItems) continue;
                    addStrategyChannel('studios', {
                        name: `${tag.title} - ${library.type === 'movie' ? 'Movies' : 'TV'}`,
                        contentSource: {
                            type: 'library',
                            libraryId: library.id,
                            libraryType: library.type === 'movie' ? 'movie' : 'show',
                            includeWatched: true,
                            libraryFilter: buildTagFilter(tag, 'studio'),
                        },
                        playbackMode: 'shuffle',
                        shuffleSeed: seedFor(`studio:${library.id}:${tag.key}`),
                        isAutoGenerated: true,
                        sourceLibraryId: library.id,
                        sourceLibraryName: library.title,
                    });
                }
            }
        }
    }

    if (isStrategyEnabled('actors')) {
        const actorScope = getStrategyScope('actors');
        if (actorStudioCombineMode === 'combined' || actorScope === 'cross-library') {
            const combined = combineTagSources(selectedLibraries, actorsByLibraryId, 'actor');
            for (const tag of combined) {
                if (tag.totalCount < minItems) continue;
                addStrategyChannel('actors', {
                    name: tag.title,
                    contentSource: {
                        type: 'mixed',
                        mixMode: actorScope === 'cross-library' ? 'interleave' : 'sequential',
                        sources: tag.sources,
                    },
                    playbackMode: 'shuffle',
                    shuffleSeed: seedFor(`actor:${tag.key}`),
                    isAutoGenerated: true,
                });
            }
        } else {
            for (const library of selectedLibraries) {
                const tags = sortTags(actorsByLibraryId.get(library.id) ?? []);
                for (const tag of tags) {
                    if (tag.count < minItems) continue;
                    addStrategyChannel('actors', {
                        name: `${tag.title} - ${library.type === 'movie' ? 'Movies' : 'TV'}`,
                        contentSource: {
                            type: 'library',
                            libraryId: library.id,
                            libraryType: library.type === 'movie' ? 'movie' : 'show',
                            includeWatched: true,
                            libraryFilter: buildTagFilter(tag, 'actor'),
                        },
                        playbackMode: 'shuffle',
                        shuffleSeed: seedFor(`actor:${library.id}:${tag.key}`),
                        isAutoGenerated: true,
                        sourceLibraryId: library.id,
                        sourceLibraryName: library.title,
                    });
                }
            }
        }
    }

    const orderedStrategies = (Object.keys(strategyBuckets) as SetupStrategyKey[]).sort((a, b) => {
        const priorityDiff = getStrategyPriority(a) - getStrategyPriority(b);
        if (priorityDiff !== 0) return priorityDiff;
        return a.localeCompare(b);
    });

    const showLibraryIds = new Set(
        selectedLibraries
            .filter((library) => library.type === 'show')
            .map((library) => library.id)
    );

    const isTvOnlySource = (source: ChannelConfig['contentSource']): boolean => {
        switch (source.type) {
            case 'library':
                return source.libraryType === 'show';
            case 'show':
                return true;
            case 'mixed':
                return source.sources.every(isTvOnlySource);
            default:
                return false;
        }
    };

    const isSeriesDerivedChannel = (channel: PendingChannel): boolean => {
        if (typeof channel.sourceLibraryId === 'string' && showLibraryIds.has(channel.sourceLibraryId)) {
            return true;
        }
        return isTvOnlySource(channel.contentSource);
    };

    const baseOrderedUnadjusted: PendingChannel[] = [];
    for (const strategy of orderedStrategies) {
        baseOrderedUnadjusted.push(...strategyBuckets[strategy]);
    }

    const sanitizeBlockSize = (raw: unknown, fallback: number): number => {
        const numeric = typeof raw === 'number' ? raw : Number(raw);
        if (!Number.isFinite(numeric)) return fallback;
        const value = Math.floor(numeric);
        if (value < 1) return fallback;
        return value;
    };

    const baseSeriesModeRaw = config.seriesOrdering?.basePlaybackMode;
    const baseSeriesMode =
        baseSeriesModeRaw === 'sequential' || baseSeriesModeRaw === 'block'
            ? baseSeriesModeRaw
            : 'shuffle';
    const baseSeriesBlockSize = sanitizeBlockSize(config.seriesOrdering?.baseBlockSize, 3);
    const baseOrdered: PendingChannel[] = baseOrderedUnadjusted.map((channel) => {
        const isSeriesDerived = isSeriesDerivedChannel(channel);
        if (baseSeriesMode === 'shuffle' || !isSeriesDerived || channel.playbackMode !== 'shuffle') {
            return channel;
        }
        const updated: PendingChannel = {
            ...channel,
            playbackMode: baseSeriesMode,
        };
        if (baseSeriesMode === 'block') {
            updated.blockSize = baseSeriesBlockSize;
        } else {
            delete updated.blockSize;
        }
        return updated;
    });

    let alternateCopies = 0;
    if (config.channelExpansion?.addAlternateLineups) {
        const raw = config.channelExpansion?.alternateLineupCopies;
        const copies = Number.isFinite(raw) ? Math.floor(Number(raw)) : 1;
        alternateCopies = Math.min(3, Math.max(1, copies));
    }
    const withAlternateLineups: PendingChannel[] = [];
    for (const channel of baseOrdered) {
        const baseChannel: PendingChannel = {
            ...channel,
            lineupReplicaIndex: channel.lineupReplicaIndex ?? 0,
            isSequentialVariant: false,
        };
        withAlternateLineups.push(baseChannel);

        if (alternateCopies <= 0 || baseChannel.playbackMode === 'sequential') {
            continue;
        }
        for (let replicaIndex = 1; replicaIndex <= alternateCopies; replicaIndex++) {
            withAlternateLineups.push({
                ...baseChannel,
                name: `${baseChannel.name} (${replicaIndex + 1})`,
                shuffleSeed: seedFor(`${createChannelIdentityKey(baseChannel)}:replica:${replicaIndex}`),
                lineupReplicaIndex: replicaIndex,
                isSequentialVariant: false,
            });
        }
    }

    const variantTypeRaw = config.channelExpansion?.variantType;
    const variantType =
        variantTypeRaw === 'sequential' || variantTypeRaw === 'block'
            ? variantTypeRaw
            : 'none';
    const variantBlockSize = sanitizeBlockSize(config.channelExpansion?.variantBlockSize, 3);
    const withVariants: PendingChannel[] = [...withAlternateLineups];
    if (variantType !== 'none') {
        const variantLabel = variantType === 'sequential' ? 'Sequential' : 'Block';
        for (const channel of withAlternateLineups) {
            const isSeriesDerived = isSeriesDerivedChannel(channel);
            if (!isSeriesDerived) {
                continue;
            }
            const sameMode = channel.playbackMode === variantType;
            const sameBlockSize =
                variantType !== 'block' || channel.blockSize === variantBlockSize;
            if (sameMode && sameBlockSize) {
                continue;
            }
            const variant: PendingChannel = {
                ...channel,
                name: `${channel.name} • ${variantLabel}`,
                playbackMode: variantType,
                // Marks this as a setup-generated playback-mode variant (sequential/block) for identity/diffing.
                isSequentialVariant: true,
                shuffleSeed: seedFor(`${createChannelIdentityKey(channel)}:variant:${variantType}`),
            };
            if (variantType === 'block') {
                variant.blockSize = variantBlockSize;
            } else {
                delete variant.blockSize;
            }
            withVariants.push(variant);
        }
    }

    const pending = withVariants.slice(0, effectiveMaxChannels);
    const reachedMaxChannels = withVariants.length > effectiveMaxChannels;
    const estimates = emptyEstimates();
    for (const channel of pending) {
        estimates.total += 1;
        const strategyKey = channel.buildStrategy as keyof ChannelSetupEstimates | undefined;
        if (!strategyKey || strategyKey === 'total') {
            continue;
        }
        if (strategyKey in estimates) {
            estimates[strategyKey] += 1;
        }
    }

    return {
        pendingChannels: pending,
        estimates,
        warnings: [...warnings],
        skipped,
        reachedMaxChannels,
    };
}

export function createChannelIdentityKey(candidate: ChannelIdentityCandidate): string {
    // Identity keys are used to match planned channels to existing channels in merge/append flows.
    // Intentionally exclude mutable playback settings like `blockSize` so changing those settings
    // updates an existing channel rather than creating a duplicate.
    const normalized = {
        source: normalizeSource(candidate.contentSource),
        filters: normalizeFilters(candidate.contentFilters),
        sortOrder: candidate.sortOrder ?? null,
        lineupReplicaIndex: candidate.lineupReplicaIndex ?? 0,
        isSequentialVariant: candidate.isSequentialVariant === true,
        variantPlaybackMode: candidate.isSequentialVariant === true ? candidate.playbackMode : null,
    };
    return stableStringify(normalized);
}

export function diffChannelPlans(
    existingChannels: ChannelConfig[],
    plannedChannels: PendingChannel[]
): ChannelDiffResult {
    const plannedByKey = new Map<string, PendingChannel[]>();
    for (const planned of plannedChannels) {
        const key = createChannelIdentityKey(planned);
        const list = plannedByKey.get(key) ?? [];
        list.push(planned);
        plannedByKey.set(key, list);
    }

    const created: ChannelDiffEntry[] = [];
    const removed: ChannelDiffEntry[] = [];
    const unchanged: ChannelDiffEntry[] = [];
    const matchedPairs: Array<{ existing: ChannelConfig; planned: PendingChannel }> = [];

    const consumePlanned = (key: string): PendingChannel | null => {
        const list = plannedByKey.get(key);
        if (!list || list.length === 0) return null;
        return list.shift() ?? null;
    };

    for (const existing of existingChannels) {
        const key = createChannelIdentityKey(existing);
        const planned = consumePlanned(key);
        if (planned) {
            matchedPairs.push({ existing, planned });
            const entry: ChannelDiffEntry = {
                name: existing.name,
                identityKey: key,
                channelId: existing.id,
                number: existing.number,
            };
            if (existing.isAutoGenerated !== undefined) {
                entry.isAutoGenerated = existing.isAutoGenerated;
            }
            unchanged.push(entry);
        } else {
            const entry: ChannelDiffEntry = {
                name: existing.name,
                identityKey: key,
                channelId: existing.id,
                number: existing.number,
            };
            if (existing.isAutoGenerated !== undefined) {
                entry.isAutoGenerated = existing.isAutoGenerated;
            }
            removed.push(entry);
        }
    }

    for (const [key, remaining] of plannedByKey.entries()) {
        for (const planned of remaining) {
            const entry: ChannelDiffEntry = {
                name: planned.name,
                identityKey: key,
            };
            if (planned.isAutoGenerated !== undefined) {
                entry.isAutoGenerated = planned.isAutoGenerated;
            }
            created.push(entry);
        }
    }

    const summary = {
        created: created.length,
        removed: removed.length,
        unchanged: unchanged.length,
    };
    const samples = {
        created: created.slice(0, 6).map((c) => c.name),
        removed: removed.slice(0, 6).map((c) => c.name),
        unchanged: unchanged.slice(0, 6).map((c) => c.name),
    };

    return { created, removed, unchanged, matchedPairs, summary, samples };
}

function buildTagFilter(tag: PlexTagDirectoryItem, type: 'actor' | 'studio'): Record<string, string | number> {
    if (tag.fastKey) {
        const parsed = parseFastKeyFilters(tag.fastKey);
        const hasActor = typeof parsed.actor === 'string' && parsed.actor.length > 0;
        const hasStudio = typeof parsed.studio === 'string' && parsed.studio.length > 0;
        if ((type === 'actor' && hasActor) || (type === 'studio' && hasStudio)) {
            return parsed;
        }
    }
    return { [type]: tag.key };
}

function parseFastKeyFilters(fastKey: string): Record<string, string | number> {
    try {
        const result: Record<string, string | number> = {};
        const url = new URL(fastKey, 'http://localhost');
        const allowList = new Set(['actor', 'studio', 'type']);
        for (const [rawKey, value] of url.searchParams.entries()) {
            if (!rawKey || value === '') continue;
            const key = rawKey.trim();
            const lowerKey = key.toLowerCase();
            if (/token/i.test(key)) continue;
            if (lowerKey.startsWith('x-plex-') || lowerKey.startsWith('x-plex-container-')) continue;
            if (!allowList.has(lowerKey)) continue;
            const trimmed = value.trim();
            if (!trimmed) continue;
            if (lowerKey === 'type') {
                const parsedType = Number.parseInt(trimmed, 10);
                if (Number.isFinite(parsedType)) {
                    result.type = parsedType;
                }
                continue;
            }
            if (lowerKey === 'actor') {
                result.actor = trimmed;
            }
            if (lowerKey === 'studio') {
                result.studio = trimmed;
            }
        }
        return result;
    } catch {
        return {};
    }
}

function combineTagSources(
    libraries: PlexLibraryType[],
    tagsByLibraryId: Map<string, PlexTagDirectoryItem[]>,
    type: 'actor' | 'studio'
): Array<{ key: string; title: string; totalCount: number; sources: ChannelConfig['contentSource'][] }> {
    const grouped = new Map<string, { title: string; totalCount: number; sources: ChannelConfig['contentSource'][] }>();

    for (const library of libraries) {
        const tags = tagsByLibraryId.get(library.id) ?? [];
        for (const tag of tags) {
            const groupKey = tag.title.trim().toLowerCase();
            if (!groupKey) continue;
            const entry = grouped.get(groupKey) ?? { title: tag.title, totalCount: 0, sources: [] };
            entry.totalCount += tag.count || 0;
            entry.sources.push({
                type: 'library',
                libraryId: library.id,
                libraryType: library.type === 'movie' ? 'movie' : 'show',
                includeWatched: true,
                libraryFilter: buildTagFilter(tag, type),
            });
            grouped.set(groupKey, entry);
        }
    }

    return Array.from(grouped.entries())
        .map(([key, entry]) => ({ key, title: entry.title, totalCount: entry.totalCount, sources: entry.sources }))
        .sort((a, b) => {
            const countDiff = b.totalCount - a.totalCount;
            if (countDiff !== 0) return countDiff;
            return a.title.localeCompare(b.title);
        });
}

function normalizeFilters(filters?: ContentFilter[]): Array<ContentFilter> | null {
    if (!filters || filters.length === 0) return null;
    return [...filters].sort((a, b) => {
        const aKey = `${a.field}:${a.operator}:${String(a.value)}`;
        const bKey = `${b.field}:${b.operator}:${String(b.value)}`;
        return aKey.localeCompare(bKey);
    });
}

function normalizeSource(source: ChannelConfig['contentSource']): unknown {
    switch (source.type) {
        case 'library':
            return {
                type: source.type,
                libraryId: source.libraryId,
                libraryType: source.libraryType,
                includeWatched: source.includeWatched,
                libraryFilter: normalizeRecord(source.libraryFilter),
            };
        case 'collection':
            return { type: source.type, collectionKey: source.collectionKey };
        case 'playlist':
            return { type: source.type, playlistKey: source.playlistKey };
        case 'show':
            return {
                type: source.type,
                showKey: source.showKey,
                seasonFilter: source.seasonFilter ? [...source.seasonFilter].sort((a, b) => a - b) : null,
            };
        case 'manual':
            return {
                type: source.type,
                items: [...source.items].sort((a, b) => a.ratingKey.localeCompare(b.ratingKey)),
            };
        case 'mixed': {
            const normalizedSources = source.sources.map(normalizeSource);
            const sortedSources = [...normalizedSources].sort((a, b) => stableStringify(a).localeCompare(stableStringify(b)));
            return { type: source.type, mixMode: source.mixMode, sources: sortedSources };
        }
        default:
            return source;
    }
}

function normalizeRecord(record?: Record<string, string | number>): Record<string, string | number> | null {
    if (!record) return null;
    const entries = Object.entries(record).sort(([a], [b]) => a.localeCompare(b));
    const normalized: Record<string, string | number> = {};
    for (const [key, value] of entries) {
        normalized[key] = value;
    }
    return normalized;
}

function stableStringify(value: unknown): string {
    if (value === null || typeof value !== 'object') {
        return JSON.stringify(value);
    }
    if (Array.isArray(value)) {
        return `[${value.map(stableStringify).join(',')}]`;
    }
    const obj = value as Record<string, unknown>;
    const keys = Object.keys(obj).sort();
    const entries = keys.map((key) => `${JSON.stringify(key)}:${stableStringify(obj[key])}`);
    return `{${entries.join(',')}}`;
}
