/**
 * @fileoverview Pure-logic planner that builds pending channel list from config.
 * @module core/channel-setup/ChannelSetupPlanner
 * @version 1.0.0
 */

import type {
    ChannelSetupConfig,
    ChannelSetupEstimates,
    SetupStrategyKey,
} from './types';
import { DEFAULT_MIN_ITEMS_PER_CHANNEL, DEFAULT_STRATEGY_PRIORITIES } from './constants';
import { DEFAULT_CHANNEL_SETUP_MAX } from '../../modules/scheduler/channel-manager/constants';
import type {
    PlexLibrarySection,
    PlexCollection,
    PlexPlaylist,
    PlexTagDirectoryItem,
} from '../../modules/plex/library';
import type {
    ChannelConfig,
    ContentFilter,
    SortOrder,
    BuildStrategy,
} from '../../modules/scheduler/channel-manager';
import { buildChannelSetupTagFilter } from './ChannelSetupTagFilters';

export type PendingChannel = {
    name: string;
    contentSource: ChannelConfig['contentSource'];
    playbackMode: ChannelConfig['playbackMode'];
    shuffleSeed: number;
    blockSize?: number;
    contentFilters?: ContentFilter[];
    sortOrder?: SortOrder;
    isAutoGenerated?: boolean;
    buildStrategy?: BuildStrategy;
    sourceLibraryId?: string;
    sourceLibraryName?: string;
    lineupReplicaIndex?: number;
    isPlaybackModeVariant?: boolean;
};

interface ChannelSetupPlanInput {
    config: ChannelSetupConfig;
    libraries: PlexLibrarySection[];
    playlists: PlexPlaylist[];
    collectionsByLibraryId: Map<string, PlexCollection[]>;
    genresByLibraryId: Map<string, PlexTagDirectoryItem[]>;
    directorsByLibraryId: Map<string, PlexTagDirectoryItem[]>;
    yearsByLibraryId: Map<string, PlexTagDirectoryItem[]>;
    actorsByLibraryId: Map<string, PlexTagDirectoryItem[]>;
    studiosByLibraryId: Map<string, PlexTagDirectoryItem[]>;
    warnings: string[];
    seedFor: (value: string) => number;
}

interface ChannelSetupPlan {
    pendingChannels: PendingChannel[];
    estimates: ChannelSetupEstimates;
    warnings: string[];
    skipped: number;
    reachedMaxChannels: boolean;
}

type ChannelSetupPlannerFacetFamily = 'genres' | 'directors' | 'decades' | 'studios' | 'actors';

export interface ChannelSetupPlannerLibraryCount {
    libraryId: string;
    libraryName: string;
    count: number;
}

export interface ChannelSetupPlannerCountSample {
    title: string;
    count: number;
}

export interface ChannelSetupPlannerFacetCountDiagnostics {
    libraryId: string;
    libraryName: string;
    rawTagCount: number;
    effectiveCandidateCount: number;
    candidatesWithKnownCount: number;
    candidatesWithUnknownCount: number;
    candidatesBelowMinItems: number;
    minKnownCount: number | null;
    maxKnownCount: number | null;
    sampleKnownCounts: ChannelSetupPlannerCountSample[];
    sampleUnknownCountTitles: string[];
    sampleBelowMinItems: ChannelSetupPlannerCountSample[];
}

export interface ChannelSetupPlannerDiagnostics {
    effectiveMaxChannels: number;
    minItems: number;
    fetchedTagsByFamily: Record<ChannelSetupPlannerFacetFamily, ChannelSetupPlannerLibraryCount[]>;
    tagCountDiagnosticsByFamily: Record<ChannelSetupPlannerFacetFamily, ChannelSetupPlannerFacetCountDiagnostics[]>;
    candidatesBeforeMinItems: ChannelSetupEstimates;
    candidatesAfterMinItems: ChannelSetupEstimates;
    strategyBucketSizes: ChannelSetupEstimates;
    afterAlternateLineups: ChannelSetupEstimates;
    afterVariants: ChannelSetupEstimates;
    afterMaxChannels: ChannelSetupEstimates;
    lostToMaxChannels: ChannelSetupEstimates;
}

interface ChannelIdentityCandidate {
    contentSource: ChannelConfig['contentSource'];
    contentFilters?: ContentFilter[];
    sortOrder?: SortOrder;
    playbackMode: ChannelConfig['playbackMode'];
    blockSize?: number;
    lineupReplicaIndex?: number;
    isPlaybackModeVariant?: boolean;
}

interface ChannelDiffEntry {
    name: string;
    identityKey: string;
    channelId?: string;
    number?: number;
    isAutoGenerated?: boolean;
}

export interface ChannelDiffResult {
    created: ChannelDiffEntry[];
    removed: ChannelDiffEntry[];
    unchanged: ChannelDiffEntry[];
    matchedPairs: Array<{ existing: ChannelConfig; planned: PendingChannel }>;
    summary: { created: number; removed: number; unchanged: number };
    samples: { created: string[]; removed: string[]; unchanged: string[] };
}

type CategoryCandidate = {
    strategy: SetupStrategyKey;
    categoryKey: string;
    categoryLabel: string;
    baseSource: ChannelConfig['contentSource'];
    sourceLibraryId?: string;
    sourceLibraryName?: string;
    itemCount?: number;
};

const emptyEstimates = (): ChannelSetupEstimates => ({
    total: 0,
    collections: 0,
    playlists: 0,
    genres: 0,
    directors: 0,
    decades: 0,
    recentlyAdded: 0,
    studios: 0,
    actors: 0,
});

const sortTagValuesByCountThenTitle = <T extends { title: string; count: number }>(values: T[]): T[] => (
    [...values].sort((a, b) => {
        const countDiff = b.count - a.count;
        if (countDiff !== 0) return countDiff;
        return a.title.localeCompare(b.title);
    })
);

const sortTagTitles = (titles: string[]): string[] => [...titles].sort((a, b) => a.localeCompare(b));

const toCountSamples = (values: Array<{ title: string; count: number }>, limit: number = 5): ChannelSetupPlannerCountSample[] =>
    sortTagValuesByCountThenTitle(values).slice(0, limit).map((value) => ({
        title: value.title,
        count: value.count,
    }));

const toDecadeValue = (tag: PlexTagDirectoryItem): number | null => {
    const year = Number.parseInt(tag.title, 10);
    if (!Number.isFinite(year)) {
        return null;
    }
    return Math.floor(year / 10) * 10;
};

const formatDecadeLabel = (decade: number): string => `${decade}s`;

const getLibraryMediaType = (library: PlexLibrarySection): 'movie' | 'show' => (
    library.type === 'movie' ? 'movie' : 'show'
);

const sortLibrariesByTitle = (libraries: PlexLibrarySection[]): PlexLibrarySection[] => (
    [...libraries].sort((a, b) => {
        const titleDiff = a.title.localeCompare(b.title);
        if (titleDiff !== 0) return titleDiff;
        return a.id.localeCompare(b.id);
    })
);

const sortPlaylistsByCountThenTitle = (playlists: PlexPlaylist[]): PlexPlaylist[] => (
    [...playlists].sort((a, b) => {
        const countDiff = b.leafCount - a.leafCount;
        if (countDiff !== 0) return countDiff;
        const titleDiff = a.title.localeCompare(b.title);
        if (titleDiff !== 0) return titleDiff;
        return a.ratingKey.localeCompare(b.ratingKey);
    })
);

const sortTagsByCountThenTitle = (tags: PlexTagDirectoryItem[]): PlexTagDirectoryItem[] => (
    [...tags].sort((a, b) => {
        const countDiff = (b.count ?? 0) - (a.count ?? 0);
        if (countDiff !== 0) return countDiff;
        const titleDiff = a.title.localeCompare(b.title);
        if (titleDiff !== 0) return titleDiff;
        return a.key.localeCompare(b.key);
    })
);

const sortCategoryCandidates = (candidates: CategoryCandidate[]): CategoryCandidate[] => {
    const compare = (a: string, b: string): number => {
        if (a === b) return 0;
        return a < b ? -1 : 1;
    };
    return [...candidates].sort((a, b) => {
        const countDiff = (b.itemCount ?? 0) - (a.itemCount ?? 0);
        if (countDiff !== 0) return countDiff;
        const aLabel = a.categoryLabel.toLowerCase();
        const bLabel = b.categoryLabel.toLowerCase();
        const labelDiff = compare(aLabel, bLabel);
        if (labelDiff !== 0) return labelDiff;
        return compare(a.categoryKey, b.categoryKey);
    });
};

const tagMeetsMinItems = (tag: PlexTagDirectoryItem, minItems: number): boolean => (
    tag.count === null || tag.count >= minItems
);

const getTagItemCount = (tag: PlexTagDirectoryItem): number | undefined => (
    tag.count === null ? undefined : tag.count
);

const withOptionalItemCount = (
    candidate: Omit<CategoryCandidate, 'itemCount'>,
    itemCount: number | undefined
): CategoryCandidate => {
    if (itemCount === undefined) {
        return candidate;
    }
    return {
        ...candidate,
        itemCount,
    };
};

const createLibrarySource = (
    library: PlexLibrarySection,
    libraryFilter?: Record<string, string | number>
): ChannelConfig['contentSource'] => ({
    type: 'library',
    libraryId: library.id,
    libraryType: getLibraryMediaType(library),
    includeWatched: true,
    ...(libraryFilter ? { libraryFilter } : {}),
});

const buildCrossLibraryFacetCandidates = (
    libraries: PlexLibrarySection[],
    tagsByLibraryId: Map<string, PlexTagDirectoryItem[]>,
    minItems: number,
    strategy: SetupStrategyKey,
    buildLibraryFilter: (tag: PlexTagDirectoryItem) => Record<string, string | number>
): CategoryCandidate[] => {
    const grouped = new Map<
        string,
        { label: string; totalCount: number; hasUnknownCount: boolean; sources: ChannelConfig['contentSource'][] }
    >();

    for (const library of libraries) {
        const tags = sortTagsByCountThenTitle(tagsByLibraryId.get(library.id) ?? []);
        for (const tag of tags) {
            const key = tag.title.trim().toLowerCase();
            if (!key) continue;
            const entry = grouped.get(key) ?? {
                label: tag.title,
                totalCount: 0,
                hasUnknownCount: false,
                sources: [] as ChannelConfig['contentSource'][],
            };
            if (tag.count === null) {
                entry.hasUnknownCount = true;
            } else {
                entry.totalCount += tag.count;
            }
            entry.sources.push(createLibrarySource(library, buildLibraryFilter(tag)));
            grouped.set(key, entry);
        }
    }

    const candidates: CategoryCandidate[] = [];
    for (const [categoryKey, entry] of grouped.entries()) {
        const passesMinItems = entry.hasUnknownCount || entry.totalCount >= minItems;
        if (!passesMinItems) continue;
        const baseSource: ChannelConfig['contentSource'] = entry.sources.length > 1
            ? { type: 'mixed', mixMode: 'interleave', sources: entry.sources }
            : entry.sources[0] ?? { type: 'manual', items: [] };
        candidates.push(withOptionalItemCount({
            strategy,
            categoryKey,
            categoryLabel: entry.label,
            baseSource,
        }, entry.totalCount > 0 ? entry.totalCount : undefined));
    }

    return sortCategoryCandidates(candidates);
};

const sanitizeBlockSize = (raw: unknown, fallback: number): number => {
    const numeric = typeof raw === 'number' ? raw : Number(raw);
    if (!Number.isFinite(numeric)) return fallback;
    const value = Math.floor(numeric);
    if (value < 1) return fallback;
    return value;
};

const isTvOnlySource = (source: ChannelConfig['contentSource']): boolean => {
    switch (source.type) {
        case 'library':
            return source.libraryType === 'show';
        case 'show':
            return true;
        case 'mixed':
            return source.sources.every(isTvOnlySource);
        default:
            return false;
    }
};

const isSeriesDerivedChannel = (
    channel: PendingChannel,
    showLibraryIds: Set<string>
): boolean => {
    if (typeof channel.sourceLibraryId === 'string' && showLibraryIds.has(channel.sourceLibraryId)) {
        return true;
    }
    return isTvOnlySource(channel.contentSource);
};

export function buildChannelSetupPlan(input: ChannelSetupPlanInput): ChannelSetupPlan {
    return buildChannelSetupPlanInternal(input).plan;
}

export function buildChannelSetupPlanDiagnostics(input: ChannelSetupPlanInput): ChannelSetupPlannerDiagnostics {
    return buildChannelSetupPlanInternal(input, true).diagnostics as ChannelSetupPlannerDiagnostics;
}

function buildChannelSetupPlanInternal(
    input: ChannelSetupPlanInput,
    collectDiagnostics: boolean = false
): { plan: ChannelSetupPlan; diagnostics?: ChannelSetupPlannerDiagnostics } {
    const {
        config,
        libraries,
        playlists,
        collectionsByLibraryId,
        genresByLibraryId,
        directorsByLibraryId,
        yearsByLibraryId,
        actorsByLibraryId,
        studiosByLibraryId,
        warnings,
        seedFor,
    } = input;

    let skipped = 0;

    const requestedMax = Number.isFinite(config.maxChannels) ? config.maxChannels : DEFAULT_CHANNEL_SETUP_MAX;
    const effectiveMaxChannels = Math.max(1, Math.floor(requestedMax));
    const requestedMinItems = Number.isFinite(config.minItemsPerChannel) ? config.minItemsPerChannel : DEFAULT_MIN_ITEMS_PER_CHANNEL;
    const minItems = Math.max(1, Math.floor(requestedMinItems));

    const selectedLibraries = sortLibrariesByTitle(
        libraries.filter((lib) => config.selectedLibraryIds.includes(lib.id))
    );

    const diagnostics = collectDiagnostics
        ? createPlannerDiagnostics(
            selectedLibraries,
            genresByLibraryId,
            directorsByLibraryId,
            yearsByLibraryId,
            actorsByLibraryId,
            studiosByLibraryId,
            effectiveMaxChannels,
            minItems
        )
        : undefined;

    const recordCandidate = (strategy: SetupStrategyKey, passesMinItems: boolean, amount: number = 1): void => {
        if (!diagnostics || amount <= 0) {
            return;
        }
        addEstimateCount(diagnostics.candidatesBeforeMinItems, strategy, amount);
        if (passesMinItems) {
            addEstimateCount(diagnostics.candidatesAfterMinItems, strategy, amount);
        }
    };

    const recordMinItemOutcome = (
        strategy: SetupStrategyKey,
        passesMinItems: boolean,
        amount: number = 1
    ): void => {
        recordCandidate(strategy, passesMinItems, amount);
        if (!passesMinItems && amount > 0) {
            skipped += amount;
        }
    };

    const getStrategyPriority = (strategy: SetupStrategyKey): number => {
        const configured = config.strategyConfig[strategy]?.priority;
        if (Number.isFinite(configured)) {
            return Math.max(1, Math.floor(Number(configured)));
        }
        return DEFAULT_STRATEGY_PRIORITIES[strategy];
    };

    const isStrategyEnabled = (strategy: SetupStrategyKey): boolean => {
        return config.strategyConfig[strategy]?.enabled === true;
    };

    const getStrategyScope = (strategy: SetupStrategyKey): 'per-library' | 'cross-library' => {
        return config.strategyConfig[strategy]?.scope === 'cross-library' ? 'cross-library' : 'per-library';
    };

    const strategyBuckets: Record<SetupStrategyKey, PendingChannel[]> = {
        collections: [],
        playlists: [],
        genres: [],
        directors: [],
        decades: [],
        recentlyAdded: [],
        studios: [],
        actors: [],
    };

    const addStrategyChannel = (strategy: SetupStrategyKey, channel: PendingChannel): void => {
        strategyBuckets[strategy].push({
            ...channel,
            buildStrategy: strategy,
            lineupReplicaIndex: channel.lineupReplicaIndex ?? 0,
            isPlaybackModeVariant: channel.isPlaybackModeVariant === true,
        });
    };

    // 0. Server-wide Playlists
    if (isStrategyEnabled('playlists')) {
        const orderedPlaylists = sortPlaylistsByCountThenTitle(playlists);
        for (const pl of orderedPlaylists) {
            const passesMinItems = pl.leafCount >= minItems;
            recordMinItemOutcome('playlists', passesMinItems);
            if (passesMinItems) {
                addStrategyChannel('playlists', {
                    name: pl.title,
                    contentSource: {
                        type: 'playlist',
                        playlistKey: pl.ratingKey,
                        playlistName: pl.title,
                    },
                    playbackMode: 'shuffle',
                    shuffleSeed: seedFor(`playlist:${pl.ratingKey}`),
                    isAutoGenerated: true,
                });
            }
        }
    }

    const actorStudioCombineMode = config.actorStudioCombineMode ?? 'separate';

    for (const library of selectedLibraries) {
        // 1. Collections
        if (isStrategyEnabled('collections')) {
            const collections = collectionsByLibraryId.get(library.id) ?? [];
            const candidates: CategoryCandidate[] = [];
            for (const collection of collections) {
                const passesMinItems = collection.childCount >= minItems;
                recordMinItemOutcome('collections', passesMinItems);
                if (passesMinItems) {
                    candidates.push({
                        strategy: 'collections',
                        categoryKey: collection.ratingKey,
                        categoryLabel: collection.title,
                        itemCount: collection.childCount,
                        baseSource: {
                            type: 'collection',
                            collectionKey: collection.ratingKey,
                            collectionName: collection.title,
                        },
                        sourceLibraryId: library.id,
                        sourceLibraryName: library.title,
                    });
                }
            }
            for (const candidate of sortCategoryCandidates(candidates)) {
                addStrategyChannel('collections', {
                    name: candidate.categoryLabel,
                    contentSource: candidate.baseSource,
                    playbackMode: 'shuffle',
                    shuffleSeed: seedFor(`collection:${candidate.categoryKey}`),
                    isAutoGenerated: true,
                    sourceLibraryId: library.id,
                    sourceLibraryName: library.title,
                });
            }
        }

        // 2. Recently Added
        if (isStrategyEnabled('recentlyAdded')) {
            recordCandidate('recentlyAdded', true);
            addStrategyChannel('recentlyAdded', {
                name: `${library.title} - Recently Added`,
                contentSource: createLibrarySource(library),
                sortOrder: 'added_desc',
                playbackMode: 'sequential',
                shuffleSeed: seedFor(`recentlyAdded:${library.id}`),
                isAutoGenerated: true,
                sourceLibraryId: library.id,
                sourceLibraryName: library.title,
            });
        }

        // 3. Item Scanning Strategies (per-library only pass)
        if (isStrategyEnabled('genres') || isStrategyEnabled('directors') || isStrategyEnabled('decades')) {
            const genres = sortTagsByCountThenTitle(genresByLibraryId.get(library.id) ?? []);
            const directors = sortTagsByCountThenTitle(directorsByLibraryId.get(library.id) ?? []);
            const years = yearsByLibraryId.get(library.id) ?? [];

            if (isStrategyEnabled('genres') && getStrategyScope('genres') === 'per-library') {
                const candidates: CategoryCandidate[] = [];
                for (const genre of genres) {
                    const passesMinItems = tagMeetsMinItems(genre, minItems);
                    recordMinItemOutcome('genres', passesMinItems);
                    if (!passesMinItems) continue;
                    candidates.push(withOptionalItemCount({
                        strategy: 'genres',
                        categoryKey: `${library.id}:${genre.title.toLowerCase()}`,
                        categoryLabel: genre.title,
                        baseSource: createLibrarySource(library, { genre: genre.title }),
                        sourceLibraryId: library.id,
                        sourceLibraryName: library.title,
                    }, getTagItemCount(genre)));
                }
                for (const candidate of sortCategoryCandidates(candidates)) {
                    addStrategyChannel('genres', {
                        name: `${library.title} - ${candidate.categoryLabel}`,
                        contentSource: candidate.baseSource,
                        playbackMode: 'shuffle',
                        shuffleSeed: seedFor(`genre:${library.id}:${candidate.categoryLabel}`),
                        isAutoGenerated: true,
                        sourceLibraryId: library.id,
                        sourceLibraryName: library.title,
                    });
                }
            }

            if (isStrategyEnabled('directors') && getStrategyScope('directors') === 'per-library') {
                const candidates: CategoryCandidate[] = [];
                for (const director of directors) {
                    const passesMinItems = tagMeetsMinItems(director, minItems);
                    recordMinItemOutcome('directors', passesMinItems);
                    if (!passesMinItems) continue;
                    candidates.push(withOptionalItemCount({
                        strategy: 'directors',
                        categoryKey: `${library.id}:${director.title.toLowerCase()}`,
                        categoryLabel: director.title,
                        baseSource: createLibrarySource(library),
                        sourceLibraryId: library.id,
                        sourceLibraryName: library.title,
                    }, getTagItemCount(director)));
                }
                for (const candidate of sortCategoryCandidates(candidates)) {
                    addStrategyChannel('directors', {
                        name: `${library.title} - ${candidate.categoryLabel}`,
                        contentSource: candidate.baseSource,
                        contentFilters: [{ field: 'director', operator: 'eq', value: candidate.categoryLabel }],
                        playbackMode: 'shuffle',
                        shuffleSeed: seedFor(`director:${library.id}:${candidate.categoryLabel}`),
                        isAutoGenerated: true,
                        sourceLibraryId: library.id,
                        sourceLibraryName: library.title,
                    });
                }
            }

            if (isStrategyEnabled('decades')) {
                const decadeCounts = new Map<number, number>();
                const decadesWithUnknownCounts = new Set<number>();
                for (const yearTag of years) {
                    const decade = toDecadeValue(yearTag);
                    if (decade === null) {
                        continue;
                    }
                    if (yearTag.count === null) {
                        decadesWithUnknownCounts.add(decade);
                        continue;
                    }
                    decadeCounts.set(decade, (decadeCounts.get(decade) || 0) + yearTag.count);
                }
                const sortedDecades = Array.from(new Set([...decadeCounts.keys(), ...decadesWithUnknownCounts.values()]))
                    .sort((a, b) => a - b)
                    .filter((decade) => decadesWithUnknownCounts.has(decade) || (decadeCounts.get(decade) ?? 0) >= minItems);
                const allDecades = new Set<number>([...decadeCounts.keys(), ...decadesWithUnknownCounts.values()]);

                for (const decade of allDecades) {
                    const passesMinItems =
                        decadesWithUnknownCounts.has(decade) ||
                        (decadeCounts.get(decade) ?? 0) >= minItems;
                    recordMinItemOutcome('decades', passesMinItems);
                }

                for (const decade of sortedDecades) {
                    addStrategyChannel('decades', {
                        name: `${library.title} - ${decade}s`,
                        contentSource: createLibrarySource(library),
                        contentFilters: [
                            { field: 'year', operator: 'gte', value: decade },
                            { field: 'year', operator: 'lt', value: decade + 10 },
                        ],
                        playbackMode: 'shuffle',
                        shuffleSeed: seedFor(`decade:${library.id}:${decade}`),
                        isAutoGenerated: true,
                        sourceLibraryId: library.id,
                        sourceLibraryName: library.title,
                    });
                }
            }
        }
    }

    if (isStrategyEnabled('genres') && getStrategyScope('genres') === 'cross-library') {
        const candidates = buildCrossLibraryFacetCandidates(
            selectedLibraries,
            genresByLibraryId,
            minItems,
            'genres',
            (tag) => ({ genre: tag.title })
        );
        for (const candidate of candidates) {
            recordMinItemOutcome('genres', true);
            addStrategyChannel('genres', {
                name: candidate.categoryLabel,
                contentSource: candidate.baseSource,
                playbackMode: 'shuffle',
                shuffleSeed: seedFor(`genre:cross:${candidate.categoryKey}`),
                isAutoGenerated: true,
            });
        }
        const skippedCrossLibraryGenres = Array.from(
            new Set(
                selectedLibraries.flatMap((library) =>
                    (genresByLibraryId.get(library.id) ?? [])
                        .map((tag) => tag.title.trim().toLowerCase())
                        .filter((title) => title.length > 0)
                )
            )
        ).length - candidates.length;
        if (skippedCrossLibraryGenres > 0) {
            recordMinItemOutcome('genres', false, skippedCrossLibraryGenres);
        }
    }

    if (isStrategyEnabled('directors') && getStrategyScope('directors') === 'cross-library') {
        const candidates = buildCrossLibraryFacetCandidates(
            selectedLibraries,
            directorsByLibraryId,
            minItems,
            'directors',
            (tag) => ({ director: tag.title })
        );
        for (const candidate of candidates) {
            recordMinItemOutcome('directors', true);
            addStrategyChannel('directors', {
                name: candidate.categoryLabel,
                contentSource: candidate.baseSource,
                playbackMode: 'shuffle',
                shuffleSeed: seedFor(`director:cross:${candidate.categoryKey}`),
                isAutoGenerated: true,
            });
        }
        const skippedCrossLibraryDirectors = Array.from(
            new Set(
                selectedLibraries.flatMap((library) =>
                    (directorsByLibraryId.get(library.id) ?? [])
                        .map((tag) => tag.title.trim().toLowerCase())
                        .filter((title) => title.length > 0)
                )
            )
        ).length - candidates.length;
        if (skippedCrossLibraryDirectors > 0) {
            recordMinItemOutcome('directors', false, skippedCrossLibraryDirectors);
        }
    }

    if (isStrategyEnabled('studios')) {
        const studioScope = getStrategyScope('studios');
        if (actorStudioCombineMode === 'combined' || studioScope === 'cross-library') {
            const combined = combineTagSources(selectedLibraries, studiosByLibraryId, 'studio');
            for (const tag of combined) {
                const passesMinItems = tag.hasUnknownCount || tag.totalCount >= minItems;
                recordMinItemOutcome('studios', passesMinItems);
                if (!passesMinItems) continue;
                addStrategyChannel('studios', {
                    name: tag.title,
                    contentSource: {
                        type: 'mixed',
                        mixMode: studioScope === 'cross-library' ? 'interleave' : 'sequential',
                        sources: tag.sources,
                    },
                    playbackMode: 'shuffle',
                    shuffleSeed: seedFor(`studio:${tag.key}`),
                    isAutoGenerated: true,
                });
            }
        } else {
            for (const library of selectedLibraries) {
                const tags = sortTagsByCountThenTitle(studiosByLibraryId.get(library.id) ?? []);
                for (const tag of tags) {
                    const passesMinItems = tagMeetsMinItems(tag, minItems);
                    recordMinItemOutcome('studios', passesMinItems);
                    if (!passesMinItems) continue;
                    addStrategyChannel('studios', {
                        name: `${tag.title} - ${library.type === 'movie' ? 'Movies' : 'TV'}`,
                        contentSource: createLibrarySource(library, buildChannelSetupTagFilter(tag, 'studio')),
                        playbackMode: 'shuffle',
                        shuffleSeed: seedFor(`studio:${library.id}:${tag.key}`),
                        isAutoGenerated: true,
                        sourceLibraryId: library.id,
                        sourceLibraryName: library.title,
                    });
                }
            }
        }
    }

    if (isStrategyEnabled('actors')) {
        const actorScope = getStrategyScope('actors');
        if (actorStudioCombineMode === 'combined' || actorScope === 'cross-library') {
            const combined = combineTagSources(selectedLibraries, actorsByLibraryId, 'actor');
            for (const tag of combined) {
                const passesMinItems = tag.hasUnknownCount || tag.totalCount >= minItems;
                recordMinItemOutcome('actors', passesMinItems);
                if (!passesMinItems) continue;
                addStrategyChannel('actors', {
                    name: tag.title,
                    contentSource: {
                        type: 'mixed',
                        mixMode: actorScope === 'cross-library' ? 'interleave' : 'sequential',
                        sources: tag.sources,
                    },
                    playbackMode: 'shuffle',
                    shuffleSeed: seedFor(`actor:${tag.key}`),
                    isAutoGenerated: true,
                });
            }
        } else {
            for (const library of selectedLibraries) {
                const tags = sortTagsByCountThenTitle(actorsByLibraryId.get(library.id) ?? []);
                for (const tag of tags) {
                    const passesMinItems = tagMeetsMinItems(tag, minItems);
                    recordMinItemOutcome('actors', passesMinItems);
                    if (!passesMinItems) continue;
                    addStrategyChannel('actors', {
                        name: `${tag.title} - ${library.type === 'movie' ? 'Movies' : 'TV'}`,
                        contentSource: createLibrarySource(library, buildChannelSetupTagFilter(tag, 'actor')),
                        playbackMode: 'shuffle',
                        shuffleSeed: seedFor(`actor:${library.id}:${tag.key}`),
                        isAutoGenerated: true,
                        sourceLibraryId: library.id,
                        sourceLibraryName: library.title,
                    });
                }
            }
        }
    }

    const orderedStrategies = (Object.keys(strategyBuckets) as SetupStrategyKey[]).sort((a, b) => {
        const priorityDiff = getStrategyPriority(a) - getStrategyPriority(b);
        if (priorityDiff !== 0) return priorityDiff;
        return a.localeCompare(b);
    });

    const showLibraryIds = new Set(
        selectedLibraries
            .filter((library) => library.type === 'show')
            .map((library) => library.id)
    );

    const baseOrderedUnadjusted: PendingChannel[] = [];
    for (const strategy of orderedStrategies) {
        baseOrderedUnadjusted.push(...strategyBuckets[strategy]);
    }

    if (diagnostics) {
        diagnostics.strategyBucketSizes = countChannelsByStrategy(baseOrderedUnadjusted);
    }

    const baseSeriesModeRaw = config.seriesOrdering?.basePlaybackMode;
    const baseSeriesMode =
        baseSeriesModeRaw === 'sequential' || baseSeriesModeRaw === 'block'
            ? baseSeriesModeRaw
            : 'shuffle';
    const baseSeriesBlockSize = sanitizeBlockSize(config.seriesOrdering?.baseBlockSize, 3);
    const baseOrdered: PendingChannel[] = baseOrderedUnadjusted.map((channel) => {
        const isSeriesDerived = isSeriesDerivedChannel(channel, showLibraryIds);
        if (baseSeriesMode === 'shuffle' || !isSeriesDerived || channel.playbackMode !== 'shuffle') {
            return channel;
        }
        const updated: PendingChannel = {
            ...channel,
            playbackMode: baseSeriesMode,
        };
        if (baseSeriesMode === 'block') {
            updated.blockSize = baseSeriesBlockSize;
        } else {
            delete updated.blockSize;
        }
        return updated;
    });

    let alternateCopies = 0;
    if (config.channelExpansion?.addAlternateLineups) {
        const raw = config.channelExpansion?.alternateLineupCopies;
        const copies = Number.isFinite(raw) ? Math.floor(Number(raw)) : 1;
        alternateCopies = Math.min(3, Math.max(1, copies));
    }
    const withAlternateLineups: PendingChannel[] = [];
    for (const channel of baseOrdered) {
        const baseChannel: PendingChannel = {
            ...channel,
            lineupReplicaIndex: channel.lineupReplicaIndex ?? 0,
            isPlaybackModeVariant: false,
        };
        withAlternateLineups.push(baseChannel);

        if (alternateCopies <= 0 || baseChannel.playbackMode === 'sequential') {
            continue;
        }
        for (let replicaIndex = 1; replicaIndex <= alternateCopies; replicaIndex++) {
            withAlternateLineups.push({
                ...baseChannel,
                name: `${baseChannel.name} (${replicaIndex + 1})`,
                shuffleSeed: seedFor(`${createChannelIdentityKey(baseChannel)}:replica:${replicaIndex}`),
                lineupReplicaIndex: replicaIndex,
                isPlaybackModeVariant: false,
            });
        }
    }

    if (diagnostics) {
        diagnostics.afterAlternateLineups = countChannelsByStrategy(withAlternateLineups);
    }

    const variantTypeRaw = config.channelExpansion?.variantType;
    const variantType =
        variantTypeRaw === 'sequential' || variantTypeRaw === 'block'
            ? variantTypeRaw
            : 'none';
    const variantBlockSize = sanitizeBlockSize(config.channelExpansion?.variantBlockSize, 3);
    const withVariants: PendingChannel[] = [...withAlternateLineups];
    if (variantType !== 'none') {
        const variantLabel = variantType === 'sequential' ? 'Sequential' : 'Block';
        for (const channel of withAlternateLineups) {
            const isSeriesDerived = isSeriesDerivedChannel(channel, showLibraryIds);
            if (!isSeriesDerived) {
                continue;
            }
            const sameMode = channel.playbackMode === variantType;
            const sameBlockSize =
                variantType !== 'block' || channel.blockSize === variantBlockSize;
            if (sameMode && sameBlockSize) {
                continue;
            }
            const variant: PendingChannel = {
                ...channel,
                name: `${channel.name} • ${variantLabel}`,
                playbackMode: variantType,
                // Marks this as a setup-generated playback-mode variant (sequential/block) for identity/diffing.
                isPlaybackModeVariant: true,
                shuffleSeed: seedFor(`${createChannelIdentityKey(channel)}:variant:${variantType}`),
            };
            if (variantType === 'block') {
                variant.blockSize = variantBlockSize;
            } else {
                delete variant.blockSize;
            }
            withVariants.push(variant);
        }
    }

    if (diagnostics) {
        diagnostics.afterVariants = countChannelsByStrategy(withVariants);
    }

    const pending = withVariants.slice(0, effectiveMaxChannels);
    const reachedMaxChannels = withVariants.length > effectiveMaxChannels;
    const estimates = emptyEstimates();
    for (const channel of pending) {
        estimates.total += 1;
        const strategyKey = channel.buildStrategy as keyof ChannelSetupEstimates | undefined;
        if (!strategyKey || strategyKey === 'total') {
            continue;
        }
        if (strategyKey in estimates) {
            estimates[strategyKey] += 1;
        }
    }

    if (diagnostics) {
        diagnostics.afterMaxChannels = { ...estimates };
        diagnostics.lostToMaxChannels = subtractEstimates(diagnostics.afterVariants, diagnostics.afterMaxChannels);
    }

    return {
        plan: {
            pendingChannels: pending,
            estimates,
            warnings: [...warnings],
            skipped,
            reachedMaxChannels,
        },
        ...(diagnostics ? { diagnostics } : {}),
    };
}

export function createChannelIdentityKey(candidate: ChannelIdentityCandidate): string {
    // Identity keys are used to match planned channels to existing channels in merge/append flows.
    // Intentionally exclude mutable playback settings like `blockSize` so changing those settings
    // updates an existing channel rather than creating a duplicate.
    const normalized = {
        source: normalizeSource(candidate.contentSource),
        filters: normalizeFilters(candidate.contentFilters),
        sortOrder: candidate.sortOrder ?? null,
        lineupReplicaIndex: candidate.lineupReplicaIndex ?? 0,
        isPlaybackModeVariant: candidate.isPlaybackModeVariant === true,
        variantPlaybackMode: candidate.isPlaybackModeVariant === true ? candidate.playbackMode : null,
    };
    return stableStringify(normalized);
}

export function diffChannelPlans(
    existingChannels: ChannelConfig[],
    plannedChannels: PendingChannel[]
): ChannelDiffResult {
    const plannedByKey = new Map<string, PendingChannel[]>();
    for (const planned of plannedChannels) {
        const key = createChannelIdentityKey(planned);
        const list = plannedByKey.get(key) ?? [];
        list.push(planned);
        plannedByKey.set(key, list);
    }

    const created: ChannelDiffEntry[] = [];
    const removed: ChannelDiffEntry[] = [];
    const unchanged: ChannelDiffEntry[] = [];
    const matchedPairs: Array<{ existing: ChannelConfig; planned: PendingChannel }> = [];

    const consumePlanned = (key: string): PendingChannel | null => {
        const list = plannedByKey.get(key);
        if (!list || list.length === 0) return null;
        return list.shift() ?? null;
    };

    for (const existing of existingChannels) {
        const key = createChannelIdentityKey(existing);
        const planned = consumePlanned(key);
        if (planned) {
            matchedPairs.push({ existing, planned });
            const entry: ChannelDiffEntry = {
                name: existing.name,
                identityKey: key,
                channelId: existing.id,
                number: existing.number,
            };
            if (existing.isAutoGenerated !== undefined) {
                entry.isAutoGenerated = existing.isAutoGenerated;
            }
            unchanged.push(entry);
        } else {
            const entry: ChannelDiffEntry = {
                name: existing.name,
                identityKey: key,
                channelId: existing.id,
                number: existing.number,
            };
            if (existing.isAutoGenerated !== undefined) {
                entry.isAutoGenerated = existing.isAutoGenerated;
            }
            removed.push(entry);
        }
    }

    for (const [key, remaining] of plannedByKey.entries()) {
        for (const planned of remaining) {
            const entry: ChannelDiffEntry = {
                name: planned.name,
                identityKey: key,
            };
            if (planned.isAutoGenerated !== undefined) {
                entry.isAutoGenerated = planned.isAutoGenerated;
            }
            created.push(entry);
        }
    }

    const summary = {
        created: created.length,
        removed: removed.length,
        unchanged: unchanged.length,
    };
    const samples = {
        created: created.slice(0, 6).map((c) => c.name),
        removed: removed.slice(0, 6).map((c) => c.name),
        unchanged: unchanged.slice(0, 6).map((c) => c.name),
    };

    return { created, removed, unchanged, matchedPairs, summary, samples };
}

function combineTagSources(
    libraries: PlexLibrarySection[],
    tagsByLibraryId: Map<string, PlexTagDirectoryItem[]>,
    type: 'actor' | 'studio'
): Array<{ key: string; title: string; totalCount: number; hasUnknownCount: boolean; sources: ChannelConfig['contentSource'][] }> {
    const grouped = new Map<
        string,
        { title: string; totalCount: number; hasUnknownCount: boolean; sources: ChannelConfig['contentSource'][] }
    >();

    for (const library of libraries) {
        const tags = sortTagsByCountThenTitle(tagsByLibraryId.get(library.id) ?? []);
        for (const tag of tags) {
            const groupKey = tag.title.trim().toLowerCase();
            if (!groupKey) continue;
            const entry = grouped.get(groupKey) ?? { title: tag.title, totalCount: 0, hasUnknownCount: false, sources: [] };
            if (tag.count === null) {
                entry.hasUnknownCount = true;
            } else {
                entry.totalCount += tag.count;
            }
            entry.sources.push({
                ...createLibrarySource(library, buildChannelSetupTagFilter(tag, type)),
            });
            grouped.set(groupKey, entry);
        }
    }

    return Array.from(grouped.entries())
        .map(([key, entry]) => ({
            key,
            title: entry.title,
            totalCount: entry.totalCount,
            hasUnknownCount: entry.hasUnknownCount,
            sources: entry.sources,
        }))
        .sort((a, b) => {
            const countDiff = b.totalCount - a.totalCount;
            if (countDiff !== 0) return countDiff;
            const titleDiff = a.title.localeCompare(b.title);
            if (titleDiff !== 0) return titleDiff;
            return a.key.localeCompare(b.key);
        });
}

function buildFacetCountDiagnostics(
    library: PlexLibrarySection,
    tags: PlexTagDirectoryItem[],
    minItems: number
): ChannelSetupPlannerFacetCountDiagnostics {
    const knownCounts = sortTagValuesByCountThenTitle(
        tags
            .filter((tag): tag is PlexTagDirectoryItem & { count: number } => tag.count !== null)
            .map((tag) => ({ title: tag.title, count: tag.count }))
    );
    const unknownCountTitles = sortTagTitles(
        tags
            .filter((tag) => tag.count === null)
            .map((tag) => tag.title)
    );
    const belowMinItems = knownCounts.filter((tag) => tag.count < minItems);

    return {
        libraryId: library.id,
        libraryName: library.title,
        rawTagCount: tags.length,
        effectiveCandidateCount: tags.length,
        candidatesWithKnownCount: knownCounts.length,
        candidatesWithUnknownCount: unknownCountTitles.length,
        candidatesBelowMinItems: belowMinItems.length,
        minKnownCount: knownCounts.length > 0 ? knownCounts[knownCounts.length - 1]?.count ?? null : null,
        maxKnownCount: knownCounts.length > 0 ? knownCounts[0]?.count ?? null : null,
        sampleKnownCounts: toCountSamples(knownCounts),
        sampleUnknownCountTitles: unknownCountTitles.slice(0, 5),
        sampleBelowMinItems: toCountSamples(belowMinItems),
    };
}

function buildDecadeFacetCountDiagnostics(
    library: PlexLibrarySection,
    yearTags: PlexTagDirectoryItem[],
    minItems: number
): ChannelSetupPlannerFacetCountDiagnostics {
    const decades = new Map<number, { totalCount: number; hasUnknownCount: boolean }>();

    for (const yearTag of yearTags) {
        const decade = toDecadeValue(yearTag);
        if (decade === null) {
            continue;
        }
        const entry = decades.get(decade) ?? { totalCount: 0, hasUnknownCount: false };
        if (yearTag.count === null) {
            entry.hasUnknownCount = true;
        } else {
            entry.totalCount += yearTag.count;
        }
        decades.set(decade, entry);
    }

    const knownCounts = sortTagValuesByCountThenTitle(
        Array.from(decades.entries())
            .filter(([, entry]) => entry.hasUnknownCount === false)
            .map(([decade, entry]) => ({ title: formatDecadeLabel(decade), count: entry.totalCount }))
    );
    const unknownCountTitles = sortTagTitles(
        Array.from(decades.entries())
            .filter(([, entry]) => entry.hasUnknownCount === true)
            .map(([decade]) => formatDecadeLabel(decade))
    );
    const belowMinItems = knownCounts.filter((tag) => tag.count < minItems);

    return {
        libraryId: library.id,
        libraryName: library.title,
        rawTagCount: yearTags.length,
        effectiveCandidateCount: decades.size,
        candidatesWithKnownCount: knownCounts.length,
        candidatesWithUnknownCount: unknownCountTitles.length,
        candidatesBelowMinItems: belowMinItems.length,
        minKnownCount: knownCounts.length > 0 ? knownCounts[knownCounts.length - 1]?.count ?? null : null,
        maxKnownCount: knownCounts.length > 0 ? knownCounts[0]?.count ?? null : null,
        sampleKnownCounts: toCountSamples(knownCounts),
        sampleUnknownCountTitles: unknownCountTitles.slice(0, 5),
        sampleBelowMinItems: toCountSamples(belowMinItems),
    };
}

function createPlannerDiagnostics(
    selectedLibraries: PlexLibrarySection[],
    genresByLibraryId: Map<string, PlexTagDirectoryItem[]>,
    directorsByLibraryId: Map<string, PlexTagDirectoryItem[]>,
    yearsByLibraryId: Map<string, PlexTagDirectoryItem[]>,
    actorsByLibraryId: Map<string, PlexTagDirectoryItem[]>,
    studiosByLibraryId: Map<string, PlexTagDirectoryItem[]>,
    effectiveMaxChannels: number,
    minItems: number
): ChannelSetupPlannerDiagnostics {
    const toCounts = (
        valuesByLibraryId: Map<string, PlexTagDirectoryItem[]>
    ): ChannelSetupPlannerLibraryCount[] => selectedLibraries.map((library) => ({
        libraryId: library.id,
        libraryName: library.title,
        count: valuesByLibraryId.get(library.id)?.length ?? 0,
    }));
    const toFacetCountDiagnostics = (
        valuesByLibraryId: Map<string, PlexTagDirectoryItem[]>
    ): ChannelSetupPlannerFacetCountDiagnostics[] => selectedLibraries.map((library) =>
        buildFacetCountDiagnostics(library, valuesByLibraryId.get(library.id) ?? [], minItems)
    );
    const toDecadeFacetCountDiagnostics = (): ChannelSetupPlannerFacetCountDiagnostics[] => selectedLibraries.map((library) =>
        buildDecadeFacetCountDiagnostics(library, yearsByLibraryId.get(library.id) ?? [], minItems)
    );

    return {
        effectiveMaxChannels,
        minItems,
        fetchedTagsByFamily: {
            genres: toCounts(genresByLibraryId),
            directors: toCounts(directorsByLibraryId),
            decades: toCounts(yearsByLibraryId),
            studios: toCounts(studiosByLibraryId),
            actors: toCounts(actorsByLibraryId),
        },
        tagCountDiagnosticsByFamily: {
            genres: toFacetCountDiagnostics(genresByLibraryId),
            directors: toFacetCountDiagnostics(directorsByLibraryId),
            decades: toDecadeFacetCountDiagnostics(),
            studios: toFacetCountDiagnostics(studiosByLibraryId),
            actors: toFacetCountDiagnostics(actorsByLibraryId),
        },
        candidatesBeforeMinItems: emptyEstimates(),
        candidatesAfterMinItems: emptyEstimates(),
        strategyBucketSizes: emptyEstimates(),
        afterAlternateLineups: emptyEstimates(),
        afterVariants: emptyEstimates(),
        afterMaxChannels: emptyEstimates(),
        lostToMaxChannels: emptyEstimates(),
    };
}

function addEstimateCount(estimates: ChannelSetupEstimates, strategy: SetupStrategyKey, amount: number = 1): void {
    if (amount <= 0) {
        return;
    }
    estimates.total += amount;
    estimates[strategy] += amount;
}

function countChannelsByStrategy(channels: PendingChannel[]): ChannelSetupEstimates {
    const estimates = emptyEstimates();
    for (const channel of channels) {
        estimates.total += 1;
        const strategyKey = channel.buildStrategy as SetupStrategyKey | undefined;
        if (!strategyKey) {
            continue;
        }
        estimates[strategyKey] += 1;
    }
    return estimates;
}

function subtractEstimates(
    source: ChannelSetupEstimates,
    removed: ChannelSetupEstimates
): ChannelSetupEstimates {
    return {
        total: Math.max(0, source.total - removed.total),
        collections: Math.max(0, source.collections - removed.collections),
        playlists: Math.max(0, source.playlists - removed.playlists),
        genres: Math.max(0, source.genres - removed.genres),
        directors: Math.max(0, source.directors - removed.directors),
        decades: Math.max(0, source.decades - removed.decades),
        recentlyAdded: Math.max(0, source.recentlyAdded - removed.recentlyAdded),
        studios: Math.max(0, source.studios - removed.studios),
        actors: Math.max(0, source.actors - removed.actors),
    };
}

function normalizeFilters(filters?: ContentFilter[]): Array<ContentFilter> | null {
    if (!filters || filters.length === 0) return null;
    return [...filters].sort((a, b) => {
        const aKey = `${a.field}:${a.operator}:${String(a.value)}`;
        const bKey = `${b.field}:${b.operator}:${String(b.value)}`;
        return aKey.localeCompare(bKey);
    });
}

function normalizeSource(source: ChannelConfig['contentSource']): unknown {
    switch (source.type) {
        case 'library':
            return {
                type: source.type,
                libraryId: source.libraryId,
                libraryType: source.libraryType,
                includeWatched: source.includeWatched,
                libraryFilter: normalizeRecord(source.libraryFilter),
            };
        case 'collection':
            return { type: source.type, collectionKey: source.collectionKey };
        case 'playlist':
            return { type: source.type, playlistKey: source.playlistKey };
        case 'show':
            return {
                type: source.type,
                showKey: source.showKey,
                seasonFilter: source.seasonFilter ? [...source.seasonFilter].sort((a, b) => a - b) : null,
            };
        case 'manual':
            return {
                type: source.type,
                items: [...source.items].sort((a, b) => a.ratingKey.localeCompare(b.ratingKey)),
            };
        case 'mixed': {
            const normalizedSources = source.sources.map(normalizeSource);
            const sortedSources = [...normalizedSources].sort((a, b) => stableStringify(a).localeCompare(stableStringify(b)));
            return { type: source.type, mixMode: source.mixMode, sources: sortedSources };
        }
        default:
            return source;
    }
}

function normalizeRecord(record?: Record<string, string | number>): Record<string, string | number> | null {
    if (!record) return null;
    const entries = Object.entries(record).sort(([a], [b]) => a.localeCompare(b));
    const normalized: Record<string, string | number> = {};
    for (const [key, value] of entries) {
        normalized[key] = value;
    }
    return normalized;
}

function stableStringify(value: unknown): string {
    if (value === null || typeof value !== 'object') {
        return JSON.stringify(value);
    }
    if (Array.isArray(value)) {
        return `[${value.map(stableStringify).join(',')}]`;
    }
    const obj = value as Record<string, unknown>;
    const keys = Object.keys(obj).sort();
    const entries = keys.map((key) => `${JSON.stringify(key)}:${stableStringify(obj[key])}`);
    return `{${entries.join(',')}}`;
}
