export const PLAYER_OSD_CONTAINER_ID = 'player-osd-container' as const;

export const PLAYER_OSD_CLASSES = {
    CONTAINER: 'player-osd',
    VISIBLE: 'visible',
    PANEL: 'player-osd-panel',
    CONTENT_ROW: 'player-osd-content-row',
    INFO_COLUMN: 'player-osd-info-column',
    ACTIONS_COLUMN: 'player-osd-actions-column',
    ZONE_BRAND: 'player-osd-zone-brand',
    ZONE_DETAILS: 'player-osd-zone-details',
    PROGRESS_CONTAINER: 'player-osd-progress-container',
    INFO_ONLY: 'info-only',
    STATUS: 'player-osd-status',
    CLEAR_LOGO: 'player-osd-clear-logo',
    TITLE: 'player-osd-title',
    SUBTITLE: 'player-osd-subtitle',
    INFO_LINE: 'player-osd-info',
    PILL: 'osd-pill',
    UP_NEXT: 'player-osd-up-next',
    BAR: 'player-osd-bar',
    BAR_BUFFER: 'player-osd-bar-buffer',
    BAR_PLAYED: 'player-osd-bar-played',
    META_STRIP: 'player-osd-meta-strip',
    META_LEFT: 'player-osd-meta-left',
    META_RIGHT: 'player-osd-meta-right',
    TIMECODE: 'player-osd-timecode',
    ENDS: 'player-osd-ends',
    BUFFER_TEXT: 'player-osd-buffertext',
    ACTIONS: 'player-osd-actions',
    ACTION: 'player-osd-action',
    SLEEP_TIMER: 'player-osd-sleep',
} as const;
