import type {
    ChannelConfig,
    ChannelContentSource,
    ContentFilter,
    ManualContentItem,
} from './types';

export function cloneChannelForOwnership(channel: ChannelConfig): ChannelConfig {
    return clonePersistableChannel(channel);
}

export function clonePersistableChannel(channel: ChannelConfig): ChannelConfig {
    const persistable: ChannelConfig = {
        id: channel.id,
        number: channel.number,
        name: channel.name,
        contentSource: cloneContentSource(channel.contentSource),
        playbackMode: channel.playbackMode,
        startTimeAnchor: channel.startTimeAnchor,
        skipIntros: channel.skipIntros,
        skipCredits: channel.skipCredits,
        createdAt: channel.createdAt,
        updatedAt: channel.updatedAt,
        lastContentRefresh: channel.lastContentRefresh,
        itemCount: channel.itemCount,
        totalDurationMs: channel.totalDurationMs,
    };

    assignIfDefined(persistable, 'description', channel.description);
    assignIfDefined(persistable, 'isAutoGenerated', channel.isAutoGenerated);
    assignIfDefined(persistable, 'icon', channel.icon);
    assignIfDefined(persistable, 'buildStrategy', channel.buildStrategy);
    assignIfDefined(persistable, 'sourceLibraryId', channel.sourceLibraryId);
    assignIfDefined(persistable, 'sourceLibraryName', channel.sourceLibraryName);
    assignIfDefined(persistable, 'lineupReplicaIndex', channel.lineupReplicaIndex);
    assignIfDefined(persistable, 'isPlaybackModeVariant', channel.isPlaybackModeVariant);
    assignIfDefined(persistable, 'shuffleSeed', channel.shuffleSeed);
    assignIfDefined(persistable, 'blockSize', channel.blockSize);
    assignIfDefined(persistable, 'phaseSeed', channel.phaseSeed);
    if (channel.contentFilters) {
        persistable.contentFilters = cloneContentFilters(channel.contentFilters);
    }
    assignIfDefined(persistable, 'sortOrder', channel.sortOrder);
    assignIfDefined(persistable, 'maxEpisodeRunTimeMs', channel.maxEpisodeRunTimeMs);
    assignIfDefined(persistable, 'minEpisodeRunTimeMs', channel.minEpisodeRunTimeMs);

    return persistable;
}

export function cloneContentFilters(filters: ContentFilter[]): ContentFilter[] {
    return filters.map((filter) => ({ ...filter }));
}

export function cloneContentSource(source: ChannelContentSource): ChannelContentSource {
    switch (source.type) {
        case 'library':
            return {
                ...source,
                ...(source.libraryFilter ? { libraryFilter: { ...source.libraryFilter } } : {}),
            };
        case 'manual':
            return {
                ...source,
                items: source.items.map(cloneManualContentItem),
            };
        case 'mixed':
            return {
                ...source,
                sources: source.sources.map(cloneContentSource),
            };
        case 'show':
            return {
                ...source,
                ...(source.seasonFilter ? { seasonFilter: [...source.seasonFilter] } : {}),
            };
        case 'collection':
        case 'playlist':
            return { ...source };
    }
}

function cloneManualContentItem(item: ManualContentItem): ManualContentItem {
    return { ...item };
}

function assignIfDefined<K extends keyof ChannelConfig>(
    channel: ChannelConfig,
    key: K,
    value: ChannelConfig[K] | undefined
): void {
    if (value !== undefined) {
        channel[key] = value;
    }
}
