import { isValidContentSource } from './ChannelContentSourceValidator';
import { applyChannelSeedDefaults, isValidChannelSeed } from './ChannelSeedPolicy';
import { cloneContentFilters, cloneContentSource } from './ChannelDomainClone';
import {
    isValidBuildStrategy,
    isValidContentFilterArray,
    isValidPlaybackMode,
    isValidSortOrder,
} from './ChannelValueValidators';
import { stripLegacySequentialVariant } from './stripLegacySequentialVariant';
import type { ChannelConfig, StoredChannelData } from './types';

type StringOptionalChannelField = 'description' | 'icon' | 'sourceLibraryId' | 'sourceLibraryName';
type BooleanOptionalChannelField = 'isAutoGenerated' | 'isPlaybackModeVariant';
type SeedOptionalChannelField = 'shuffleSeed' | 'phaseSeed';
type FiniteNumberOptionalChannelField = 'maxEpisodeRunTimeMs' | 'minEpisodeRunTimeMs';

const STRING_OPTIONAL_CHANNEL_FIELDS: readonly StringOptionalChannelField[] = [
    'description',
    'icon',
    'sourceLibraryId',
    'sourceLibraryName',
];

const BOOLEAN_OPTIONAL_CHANNEL_FIELDS: readonly BooleanOptionalChannelField[] = [
    'isAutoGenerated',
    'isPlaybackModeVariant',
];

const SEED_OPTIONAL_CHANNEL_FIELDS: readonly SeedOptionalChannelField[] = [
    'shuffleSeed',
    'phaseSeed',
];

const FINITE_NUMBER_OPTIONAL_CHANNEL_FIELDS: readonly FiniteNumberOptionalChannelField[] = [
    'maxEpisodeRunTimeMs',
    'minEpisodeRunTimeMs',
];

function isValidStoredShape(value: unknown): value is Partial<StoredChannelData> {
    if (!value || typeof value !== 'object' || Array.isArray(value)) {
        return false;
    }

    const record = value as Record<string, unknown>;
    return Array.isArray(record.channels) && Array.isArray(record.channelOrder);
}

export function decodeStoredChannelData(raw: string): Partial<StoredChannelData> | null {
    let parsed: unknown;
    try {
        parsed = JSON.parse(raw);
    } catch {
        return null;
    }

    if (!isValidStoredShape(parsed)) {
        return null;
    }
    return parsed;
}

export function encodeStoredChannelData(data: StoredChannelData): string {
    return JSON.stringify(data);
}

export type DecodedStoredChannelConfig = {
    channel: ChannelConfig;
    didMutate: boolean;
};

export function decodeStoredChannelConfigRecord(raw: unknown): DecodedStoredChannelConfig | null {
    if (!raw || typeof raw !== 'object' || Array.isArray(raw)) {
        return null;
    }

    const sanitized = stripLegacySequentialVariant(raw);
    const record = sanitized.channel as Record<string, unknown>;
    let didMutate = sanitized.didMutate;

    const id = record['id'];
    if (typeof id !== 'string' || id.length === 0) {
        return null;
    }

    const contentSource = record['contentSource'];
    if (!isValidContentSource(contentSource)) {
        return null;
    }

    const number = decodeFiniteNumber(record, 'number', Number.NaN);
    const hasFiniteNumber = Number.isFinite(number.value);
    const finalNumber = hasFiniteNumber ? number.value : 0;
    if (number.didDefault || !hasFiniteNumber) didMutate = true;

    const name = decodeString(record, 'name', `Channel ${hasFiniteNumber ? finalNumber : id}`);
    if (name.didDefault) didMutate = true;

    const rawPlaybackMode = record['playbackMode'];
    const validPlaybackMode = isValidPlaybackMode(rawPlaybackMode);
    const playbackMode = validPlaybackMode ? rawPlaybackMode : 'sequential';
    if (!validPlaybackMode) {
        didMutate = true;
    }

    const startTimeAnchor = decodeFiniteNumber(record, 'startTimeAnchor', 0);
    const createdAt = decodeFiniteNumber(record, 'createdAt', 0);
    const updatedAt = decodeFiniteNumber(record, 'updatedAt', 0);
    const lastContentRefresh = decodeFiniteNumber(record, 'lastContentRefresh', 0);
    const itemCount = decodeFiniteNumber(record, 'itemCount', 0);
    const totalDurationMs = decodeFiniteNumber(record, 'totalDurationMs', 0);
    didMutate =
        didMutate ||
        startTimeAnchor.didDefault ||
        createdAt.didDefault ||
        updatedAt.didDefault ||
        lastContentRefresh.didDefault ||
        itemCount.didDefault ||
        totalDurationMs.didDefault;

    const skipIntros = decodeBoolean(record, 'skipIntros', false);
    const skipCredits = decodeBoolean(record, 'skipCredits', false);
    didMutate = didMutate || skipIntros.didDefault || skipCredits.didDefault;

    const channel: ChannelConfig = {
        id,
        number: finalNumber,
        name: name.value,
        contentSource: cloneContentSource(contentSource),
        playbackMode,
        startTimeAnchor: startTimeAnchor.value,
        skipIntros: skipIntros.value,
        skipCredits: skipCredits.value,
        createdAt: createdAt.value,
        updatedAt: updatedAt.value,
        lastContentRefresh: lastContentRefresh.value,
        itemCount: itemCount.value,
        totalDurationMs: totalDurationMs.value,
    };

    didMutate = applyOptionalPersistedChannelFields(channel, record, didMutate);
    const previousShuffleSeed = channel.shuffleSeed;
    const previousPhaseSeed = channel.phaseSeed;
    applyChannelSeedDefaults(channel);
    if (channel.shuffleSeed !== previousShuffleSeed || channel.phaseSeed !== previousPhaseSeed) {
        didMutate = true;
    }

    return { channel, didMutate };
}

function decodeString(
    record: Record<string, unknown>,
    key: string,
    fallback: string
): { value: string; didDefault: boolean } {
    const value = record[key];
    if (typeof value === 'string' && value.length > 0) {
        return { value, didDefault: false };
    }
    return { value: fallback, didDefault: true };
}

function decodeBoolean(
    record: Record<string, unknown>,
    key: string,
    fallback: boolean
): { value: boolean; didDefault: boolean } {
    const value = record[key];
    if (typeof value === 'boolean') {
        return { value, didDefault: false };
    }
    return { value: fallback, didDefault: true };
}

function decodeFiniteNumber(
    record: Record<string, unknown>,
    key: string,
    fallback: number
): { value: number; didDefault: boolean } {
    const value = record[key];
    if (typeof value === 'number' && Number.isFinite(value)) {
        return { value, didDefault: false };
    }
    return { value: fallback, didDefault: true };
}

function applyOptionalPersistedChannelFields(
    channel: ChannelConfig,
    record: Record<string, unknown>,
    didMutate: boolean
): boolean {
    didMutate = applyStringOptionals(channel, record, didMutate);
    didMutate = applyBooleanOptionals(channel, record, didMutate);
    didMutate = applySeedOptionals(channel, record, didMutate);
    didMutate = applyFiniteNumberOptionals(channel, record, didMutate);
    didMutate = applyBuildStrategyOptional(channel, record, didMutate);
    didMutate = applySortOrderOptional(channel, record, didMutate);
    didMutate = applyLineupReplicaIndexOptional(channel, record, didMutate);
    didMutate = applyLegacyColorOptional(record, didMutate);
    didMutate = applyBlockSizeOptional(channel, record, didMutate);
    return applyContentFiltersOptional(channel, record, didMutate);
}

function applyStringOptionals(
    channel: ChannelConfig,
    record: Record<string, unknown>,
    didMutate: boolean
): boolean {
    for (const field of STRING_OPTIONAL_CHANNEL_FIELDS) {
        const value = record[field];
        if (value === undefined) continue;
        if (typeof value === 'string') channel[field] = value;
        else didMutate = true;
    }
    return didMutate;
}

function applyBooleanOptionals(
    channel: ChannelConfig,
    record: Record<string, unknown>,
    didMutate: boolean
): boolean {
    for (const field of BOOLEAN_OPTIONAL_CHANNEL_FIELDS) {
        const value = record[field];
        if (value === undefined) continue;
        if (typeof value === 'boolean') channel[field] = value;
        else didMutate = true;
    }
    return didMutate;
}

function applySeedOptionals(
    channel: ChannelConfig,
    record: Record<string, unknown>,
    didMutate: boolean
): boolean {
    for (const field of SEED_OPTIONAL_CHANNEL_FIELDS) {
        const value = record[field];
        if (value === undefined) continue;
        if (isValidChannelSeed(value)) channel[field] = value;
        else didMutate = true;
    }
    return didMutate;
}

function applyFiniteNumberOptionals(
    channel: ChannelConfig,
    record: Record<string, unknown>,
    didMutate: boolean
): boolean {
    for (const field of FINITE_NUMBER_OPTIONAL_CHANNEL_FIELDS) {
        const value = record[field];
        if (value === undefined) continue;
        if (typeof value === 'number' && Number.isFinite(value)) channel[field] = value;
        else didMutate = true;
    }
    return didMutate;
}

function applyBuildStrategyOptional(
    channel: ChannelConfig,
    record: Record<string, unknown>,
    didMutate: boolean
): boolean {
    const value = record['buildStrategy'];
    if (value === undefined) return didMutate;
    if (isValidBuildStrategy(value)) channel.buildStrategy = value;
    else didMutate = true;
    return didMutate;
}

function applySortOrderOptional(
    channel: ChannelConfig,
    record: Record<string, unknown>,
    didMutate: boolean
): boolean {
    const value = record['sortOrder'];
    if (value === undefined) return didMutate;
    if (isValidSortOrder(value)) channel.sortOrder = value;
    else didMutate = true;
    return didMutate;
}

function applyLineupReplicaIndexOptional(
    channel: ChannelConfig,
    record: Record<string, unknown>,
    didMutate: boolean
): boolean {
    const value = record['lineupReplicaIndex'];
    if (value === undefined) return didMutate;
    if (typeof value !== 'number' || !Number.isFinite(value)) return true;

    channel.lineupReplicaIndex = Math.max(0, Math.floor(value));
    return didMutate || channel.lineupReplicaIndex !== value;
}

function applyLegacyColorOptional(record: Record<string, unknown>, didMutate: boolean): boolean {
    return record['color'] !== undefined || didMutate;
}

function applyBlockSizeOptional(
    channel: ChannelConfig,
    record: Record<string, unknown>,
    didMutate: boolean
): boolean {
    const value = record['blockSize'];
    if (value === undefined) return didMutate;
    if (channel.playbackMode !== 'block') return true;
    if (typeof value !== 'number' || !Number.isFinite(value)) return true;

    channel.blockSize = Math.max(1, Math.floor(value));
    return didMutate || channel.blockSize !== value;
}

function applyContentFiltersOptional(
    channel: ChannelConfig,
    record: Record<string, unknown>,
    didMutate: boolean
): boolean {
    const value = record['contentFilters'];
    if (value === undefined) return didMutate;
    if (isValidContentFilterArray(value)) {
        channel.contentFilters = cloneContentFilters(value);
        return didMutate;
    }
    return true;
}
