import type { AppErrorCode } from '../../../types/app-errors';
import type { PlexMediaType } from '../../plex/shared/types';

export type PlaybackMode =
    | 'sequential'  // Play in defined order, loop
    | 'shuffle'     // Deterministic shuffle with seed, loop
    | 'block'       // Deterministic round-robin by show in episode blocks
    | 'random';     // Seeded randomized order; orchestrator refreshes seed cadence

export type BuildStrategy =
    | 'collections'
    | 'playlists'
    | 'genres'
    | 'directors'
    | 'decades'
    | 'recentlyAdded'
    | 'studios'
    | 'actors'
    | 'libraryFallback';

export type FilterOperator =
    | 'eq' | 'neq'
    | 'gt' | 'gte'
    | 'lt' | 'lte'
    | 'contains' | 'notContains';

export type FilterField =
    | 'year'
    | 'rating'
    | 'contentRating'
    | 'genre'
    | 'director'
    | 'duration'
    | 'watched'
    | 'addedAt';

export type SortOrder =
    | 'title_asc' | 'title_desc'
    | 'year_asc' | 'year_desc'
    | 'added_asc' | 'added_desc'
    | 'duration_asc' | 'duration_desc'
    | 'episode_order';

export type { PlexMediaType };

export interface ContentFilter {
    field: FilterField;
    operator: FilterOperator;
    value: string | number | boolean;
}

interface BaseContentSource {
    type: string;
}

export interface LibraryContentSource extends BaseContentSource {
    type: 'library';
    /** Library section ID */
    libraryId: string;
    /** Library type */
    libraryType: 'movie' | 'show';
    /** Include already-watched content */
    includeWatched: boolean;
    /** Optional server-side filter parameters */
    libraryFilter?: Record<string, string | number>;
}

export interface CollectionContentSource extends BaseContentSource {
    type: 'collection';
    collectionKey: string;
    /** Cached collection name for display */
    collectionName: string;
}

export interface ShowContentSource extends BaseContentSource {
    type: 'show';
    showKey: string;
    /** Cached show name for display */
    showName: string;
    /** Specific seasons to include (undefined = all) */
    seasonFilter?: number[];
}

export interface PlaylistContentSource extends BaseContentSource {
    type: 'playlist';
    playlistKey: string;
    /** Cached playlist name for display */
    playlistName: string;
}

export interface ManualContentItem {
    /** Item ratingKey */
    ratingKey: string;
    /** Cached title for display */
    title: string;
    /** Cached duration in ms */
    durationMs: number;
}

export interface ManualContentSource extends BaseContentSource {
    type: 'manual';
    items: ManualContentItem[];
}

export interface MixedContentSource extends BaseContentSource {
    type: 'mixed';
    /** Component sources */
    sources: ChannelContentSource[];
    /** How to combine sources */
    mixMode: 'interleave' | 'sequential';
}

export type ChannelContentSource =
    | LibraryContentSource
    | CollectionContentSource
    | ShowContentSource
    | PlaylistContentSource
    | ManualContentSource
    | MixedContentSource;

/**
 * Complete channel configuration - persisted to storage
 */
export interface ChannelConfig {
    id: string;
    number: number;
    name: string;
    description?: string;
    /** True when name was auto-generated by setup */
    isAutoGenerated?: boolean;
    icon?: string;
    /** Accent color for UI (hex string) */
    color?: string;
    /** Build strategy that created this channel (for category coloring) */
    buildStrategy?: BuildStrategy;
    /** Source library ID for filtering (set during auto-setup when applicable) */
    sourceLibraryId?: string;
    /** Source library display name (cached for filter tabs) */
    sourceLibraryName?: string;
    /** 0 = base lineup, 1..n = alternate deterministic lineup replicas */
    lineupReplicaIndex?: number;
    /**
     * True when this channel is a playback-mode variant generated from a setup channel
     * (e.g., "Sequential" or "Block" variants). Used for identity/diffing in setup flows.
     */
    isPlaybackModeVariant?: boolean;

    contentSource: ChannelContentSource;

    playbackMode: PlaybackMode;
    /** Seed for deterministic shuffle */
    shuffleSeed?: number;
    /**
     * Episodes per show before switching, used when playbackMode === 'block'
     */
    blockSize?: number;
    /** Seed for deterministic per-channel phase offset (live drift) */
    phaseSeed?: number;
    /** Unix timestamp (ms) - schedule reference point */
    startTimeAnchor: number;

    contentFilters?: ContentFilter[];
    /** Content sort order */
    sortOrder?: SortOrder;

    /** Skip intro markers if available */
    skipIntros: boolean;
    /** Skip credit markers if available */
    skipCredits: boolean;
    /** Maximum item duration (skip longer items) */
    maxEpisodeRunTimeMs?: number;
    /** Minimum item duration (skip shorter items) */
    minEpisodeRunTimeMs?: number;

    /** Channel creation timestamp */
    createdAt: number;
    /** Last modification timestamp */
    updatedAt: number;
    /** Last content resolution timestamp */
    lastContentRefresh: number;
    itemCount: number;
    totalDurationMs: number;
}

type ChannelCreateOptionalField =
    | 'number'
    | 'name'
    | 'description'
    | 'isAutoGenerated'
    | 'icon'
    | 'color'
    | 'buildStrategy'
    | 'sourceLibraryId'
    | 'sourceLibraryName'
    | 'lineupReplicaIndex'
    | 'isPlaybackModeVariant'
    | 'playbackMode'
    | 'shuffleSeed'
    | 'blockSize'
    | 'phaseSeed'
    | 'startTimeAnchor'
    | 'contentFilters'
    | 'sortOrder'
    | 'skipIntros'
    | 'skipCredits'
    | 'maxEpisodeRunTimeMs'
    | 'minEpisodeRunTimeMs';

type ChannelWritableField = ChannelCreateOptionalField | 'contentSource';

/**
 * Writable channel fields accepted during channel creation.
 * Runtime-owned fields such as ids, timestamps, and cached content metadata are excluded.
 */
export interface ChannelCreateInput
    extends Pick<ChannelConfig, 'contentSource'>,
        Partial<Pick<ChannelConfig, ChannelCreateOptionalField>> {}

/**
 * Writable channel fields accepted during updates.
 * Runtime-owned fields such as ids, timestamps, and cached content metadata are excluded.
 */
export type ChannelUpdateInput = Partial<Pick<ChannelConfig, ChannelWritableField>>;

/**
 * A resolved content item with cached metadata
 */
export interface ResolvedContentItem {
    /** Plex ratingKey */
    ratingKey: string;
    /** Item type */
    type: PlexMediaType;
    /** Display title */
    title: string;
    /** Full title (e.g., "Show - S01E05 - Episode Name") */
    fullTitle: string;
    /** Show title for episodes (fallback for EPG show line) */
    showTitle?: string;
    /** Show poster thumb for episodes (EPG/Now Playing fallback) */
    showThumb?: string | null;
    /** Duration in ms */
    durationMs: number;
    /** Poster thumbnail URL (with token) */
    thumb: string | null;
    /** Backdrop image path (Plex art) */
    art?: string | null;
    /** Transparent title logo URL (raw Plex path; tokenized by UI layer as needed) */
    clearLogo?: string | null;
    /** Release year */
    year: number;
    /** Season number for episodes */
    seasonNumber?: number;
    /** Episode number for episodes */
    episodeNumber?: number;
    /** Position in ordered list */
    scheduledIndex: number;
    /** Rating (0-10) */
    rating?: number;
    /** Content rating (e.g., "PG-13") */
    contentRating?: string;
    /** Genres */
    genres?: string[];
    /** Directors */
    directors?: string[];
    /** Summary/description */
    summary?: string;
    /** Media quality info */
    mediaInfo?: {
        resolution?: string;
        hdr?: string;
        dvProfile?: string;
        audioCodec?: string;
        audioChannels?: number;
        audioTrackTitle?: string;
    };
    watched?: boolean;
    /** When item was added to Plex */
    addedAt?: number;
}

export interface ResolvedChannelContent {
    /** Channel ID this content belongs to */
    channelId: string;
    /** When content was resolved */
    resolvedAt: number;
    /** All resolved items */
    items: ResolvedContentItem[];
    totalDurationMs: number;
    /** Items after shuffle/sort applied */
    orderedItems: ResolvedContentItem[];
    /** Whether this content came from cache */
    fromCache?: boolean;
    /** Whether cached content is stale */
    isStale?: boolean;
    /** Reason for using cache (if applicable) */
    cacheReason?: 'fresh' | 'network_error' | 'content_unavailable';
}

export interface ImportResult {
    /** Overall success */
    success: boolean;
    importedCount: number;
    skippedCount: number;
    /** Error messages for failed imports */
    errors: string[];
}

export interface ChannelManagerEventMap {
    channelCreated: ChannelConfig;
    channelUpdated: ChannelConfig;
    channelDeleted: string;
    channelSwitch: { channel: ChannelConfig; index: number };
    contentResolved: ResolvedChannelContent;
    persistenceWarning: {
        message: string;
        code: AppErrorCode;
        isQuotaError: boolean;
        timestamp: number;
    };
}

export interface ChannelManagerState {
    channels: Map<string, ChannelConfig>;
    currentChannelId: string | null;
    channelOrder: string[];
}

export interface StoredChannelData {
    channels: ChannelConfig[];
    channelOrder: string[];
    currentChannelId: string | null;
    savedAt: number;
}
