import type { SettingsConfig } from './types';
import { LINEUP_STORAGE_KEYS } from '../../../config/storageKeys';
import { DEFAULT_THEME } from '../theme';

export const SETTINGS_STORAGE_KEYS = {
    DTS_PASSTHROUGH: LINEUP_STORAGE_KEYS.DTS_PASSTHROUGH,
    DIRECT_PLAY_AUDIO_FALLBACK: LINEUP_STORAGE_KEYS.DIRECT_PLAY_AUDIO_FALLBACK,
    KEEP_PLAYING_IN_SETTINGS: LINEUP_STORAGE_KEYS.KEEP_PLAYING_IN_SETTINGS,
    SMART_HDR10_FALLBACK: LINEUP_STORAGE_KEYS.SMART_HDR10_FALLBACK,
    FORCE_HDR10_FALLBACK: LINEUP_STORAGE_KEYS.FORCE_HDR10_FALLBACK,
    TRANSCODE_COMPAT: LINEUP_STORAGE_KEYS.TRANSCODE_COMPAT,
    TRANSCODE_QUALITY: LINEUP_STORAGE_KEYS.TRANSCODE_QUALITY,
    THEME: LINEUP_STORAGE_KEYS.THEME,
    CINEMATIC_NOW_PLAYING: LINEUP_STORAGE_KEYS.CINEMATIC_NOW_PLAYING,
    PREFER_CLEAR_LOGOS: LINEUP_STORAGE_KEYS.PREFER_CLEAR_LOGOS,
    DEBUG_LOGGING: LINEUP_STORAGE_KEYS.DEBUG_LOGGING,
    SUBTITLE_DEBUG_LOGGING: LINEUP_STORAGE_KEYS.SUBTITLE_DEBUG_LOGGING,
    SHOW_FPS: LINEUP_STORAGE_KEYS.SHOW_FPS,
    NOW_PLAYING_INFO_AUTO_HIDE_MS: LINEUP_STORAGE_KEYS.NOW_PLAYING_INFO_AUTO_HIDE_MS,
    AUDIO_SETUP_COMPLETE: LINEUP_STORAGE_KEYS.AUDIO_SETUP_COMPLETE,
    SUBTITLE_MODE: LINEUP_STORAGE_KEYS.SUBTITLE_MODE,
    SUBTITLE_LANGUAGE: LINEUP_STORAGE_KEYS.SUBTITLE_LANGUAGE,
    SUBTITLE_PREFER_FORCED: LINEUP_STORAGE_KEYS.SUBTITLE_PREFER_FORCED,
    GUIDE_CATEGORY_COLORS: LINEUP_STORAGE_KEYS.GUIDE_CATEGORY_COLORS,
    EPG_LIBRARY_TABS_ENABLED: LINEUP_STORAGE_KEYS.EPG_LIBRARY_TABS_ENABLED,
    EPG_LAYOUT_MODE: LINEUP_STORAGE_KEYS.EPG_LAYOUT_MODE,
    EPG_GUIDE_DENSITY: LINEUP_STORAGE_KEYS.EPG_GUIDE_DENSITY,
    EPG_PAST_ITEMS_WINDOW: LINEUP_STORAGE_KEYS.EPG_PAST_ITEMS_WINDOW,
    EPG_INFO_BACKGROUND_MODE: LINEUP_STORAGE_KEYS.EPG_INFO_BACKGROUND_MODE,
    EPG_NOW_WATCHING_ENABLED: LINEUP_STORAGE_KEYS.EPG_NOW_WATCHING_ENABLED,
    EPG_AGGRESSIVE_PRELOAD_ENABLED: LINEUP_STORAGE_KEYS.EPG_AGGRESSIVE_PRELOAD_ENABLED,
    SHOW_PROFILE_PICKER_ON_STARTUP: LINEUP_STORAGE_KEYS.SHOW_PROFILE_PICKER_ON_STARTUP,
} as const;

export const DEFAULT_SETTINGS: SettingsConfig = {
    audio: {
        dtsPassthrough: false,
        directPlayAudioFallback: false,
    },
    playback: {
        keepPlayingInSettings: false,
        smartHdr10Fallback: false,
        forceHdr10Fallback: false,
    },
    display: {
        theme: DEFAULT_THEME,
        nowPlayingInfoAutoHideMs: 0,
        cinematicNowPlaying: false,
        preferClearLogos: true,
        epgInfoBackgroundMode: 0,
    },
    developer: {
        debugLogging: false,
        subtitleDebugLogging: false,
        showFps: false,
    },
    subtitles: {
        mode: 'full',
        language: null,
        preferForced: false,
    },
    account: {
        showProfilePickerOnStartup: false,
    },
};
