/**
 * @jest-environment jsdom
 */

import { ChannelSetupBuildCommitter } from '../build/ChannelSetupBuildCommitter';
import type { ChannelSetupBuildScratchStore } from '../build/ChannelSetupBuildScratchStore';
import type { PendingChannel, ChannelDiffResult } from '../planning/ChannelSetupPlanningTypes';
import type { ChannelBuildProgress } from '../types';
import type { EpgScheduleRefreshResult } from '../../../shared/epgRefresh';
import type {
    IChannelManager,
    ChannelConfig,
    ChannelCreateInput,
} from '../../../modules/scheduler/channel-manager';
import type { IPlexLibrary } from '../../../modules/plex/library';
import { MAX_CHANNEL_NUMBER } from '../../../modules/scheduler/channel-manager/constants';

const mockBuilder = {
    createChannel: jest.fn(),
    getAllChannels: jest.fn(),
    dispose: jest.fn(),
};

jest.mock('../../../modules/scheduler/channel-manager', () => ({
    ChannelManager: jest.fn(() => mockBuilder),
}));

type ProgressEvent = {
    task: ChannelBuildProgress['task'];
    label: string;
    detail: string;
    current: number;
    total: number | null;
};

type Harness = {
    committer: ChannelSetupBuildCommitter;
    channelManager: jest.Mocked<IChannelManager>;
    scratchStoreCleanupKeys: jest.Mock<void, [ReturnType<ChannelSetupBuildScratchStore['createTempKeys']>]>;
    clearSelectedChannelScheduleSnapshot: jest.Mock<void, []>;
    ensureEpgInitialized: jest.Mock<Promise<void>, []>;
    primeEpgChannels: jest.Mock<void, []>;
    refreshEpgSchedules: jest.Mock<
        Promise<EpgScheduleRefreshResult>,
        [{ reason?: string; debounceMs?: number; signal?: AbortSignal | null }?]
    >;
};

const READY_GUIDE_REFRESH: EpgScheduleRefreshResult = {
    readiness: 'ready',
    attemptedChannelCount: 1,
    immediateReadyChannelCount: 1,
    backgroundQueuedChannelCount: 0,
    failedChannelCount: 0,
    staleCacheChannelCount: 0,
    firstVisibleScheduleReady: true,
};

const createHarness = (): Harness => {
    const channelManager = {
        getCurrentChannel: jest.fn().mockReturnValue({ id: 'current-channel' }),
        replaceAllChannels: jest.fn().mockResolvedValue(undefined),
    } as unknown as jest.Mocked<IChannelManager>;

    const tempKeys = {
        channelsKey: 'lineup_channels_build_tmp_v1:test',
        currentChannelKey: 'lineup_current_channel_build_tmp_v1:test',
    };
    const scratchStoreCleanupKeys = jest.fn<void, [typeof tempKeys]>();
    const scratchStore = {
        createTempKeys: jest.fn(() => tempKeys),
        cleanupKeys: scratchStoreCleanupKeys,
    };
    const clearSelectedChannelScheduleSnapshot = jest.fn<void, []>();
    const ensureEpgInitialized = jest.fn<Promise<void>, []>().mockResolvedValue(undefined);
    const primeEpgChannels = jest.fn<void, []>();
    const refreshEpgSchedules = jest.fn<
        Promise<EpgScheduleRefreshResult>,
        [{ reason?: string; debounceMs?: number; signal?: AbortSignal | null }?]
    >().mockResolvedValue(READY_GUIDE_REFRESH);

    const committer = new ChannelSetupBuildCommitter({
        plexLibrary: {} as IPlexLibrary,
        channelManager,
        scratchStore,
        clearSelectedChannelScheduleSnapshot,
        ensureEpgInitialized,
        primeEpgChannels,
        refreshEpgSchedules,
    });

    return {
        committer,
        channelManager,
        scratchStoreCleanupKeys,
        clearSelectedChannelScheduleSnapshot,
        ensureEpgInitialized,
        primeEpgChannels,
        refreshEpgSchedules,
    };
};

const makeExisting = (number: number): ChannelConfig => ({
    id: `existing-${number}`,
    name: `Existing ${number}`,
    number,
    contentSource: { type: 'library', libraryId: 'lib1', libraryType: 'movie', includeWatched: true },
    playbackMode: 'shuffle',
    shuffleSeed: 1,
    phaseSeed: 1,
    startTimeAnchor: 0,
    skipIntros: false,
    skipCredits: false,
    createdAt: 0,
    updatedAt: 0,
    lastContentRefresh: 0,
    itemCount: 0,
    totalDurationMs: 0,
});

const makePending = (name: string): PendingChannel => ({
    name,
    contentSource: { type: 'library', libraryId: 'lib1', libraryType: 'movie', includeWatched: true },
    playbackMode: 'shuffle',
    shuffleSeed: 1,
    isAutoGenerated: true,
});

const emptyDiff = (): ChannelDiffResult => ({
    created: [],
    removed: [],
    unchanged: [],
    matchedPairs: [],
    summary: { created: 0, removed: 0, unchanged: 0 },
    samples: { created: [], removed: [], unchanged: [] },
});

describe('ChannelSetupBuildCommitter', () => {
    let builtChannels: ChannelConfig[] = [];

    beforeEach(() => {
        jest.clearAllMocks();
        builtChannels = [];
        mockBuilder.createChannel.mockImplementation(async (config: ChannelCreateInput) => {
            const number = typeof config.number === 'number' ? config.number : builtChannels.length + 1;
            const channel: ChannelConfig = {
                id: `built-${number}`,
                name: config.name ?? `Built ${number}`,
                number,
                contentSource: config.contentSource ?? { type: 'library', libraryId: 'lib1', libraryType: 'movie', includeWatched: true },
                playbackMode: config.playbackMode ?? 'shuffle',
                shuffleSeed: typeof config.shuffleSeed === 'number' ? config.shuffleSeed : 1,
                startTimeAnchor: 0,
                skipIntros: false,
                skipCredits: false,
                createdAt: 0,
                updatedAt: 0,
                lastContentRefresh: 0,
                itemCount: 0,
                totalDurationMs: 0,
            };
            builtChannels.push(channel);
            return channel;
        });
        mockBuilder.getAllChannels.mockImplementation(() => builtChannels);
        mockBuilder.dispose.mockReset();
    });

    it('returns canceled before creating any channels when signal is already aborted', async () => {
        const { committer, channelManager } = createHarness();
        const controller = new AbortController();
        controller.abort();

        const result = await committer.commitBuild({
            buildMode: 'replace',
            existingChannels: [makeExisting(1)],
            pendingToCreate: [makePending('One'), makePending('Two')],
            skippedCount: 1,
            reachedMaxChannels: false,
            errorCount: 0,
            diff: emptyDiff(),
            signal: controller.signal,
            reportProgress: (): void => undefined,
        });

        expect(result.summary.canceled).toBe(true);
        expect(result.summary.lastTask).toBe('create_channels');
        expect(result.summary.created).toBe(0);
        expect(result.summary.skipped).toBe(3);
        expect(mockBuilder.createChannel).not.toHaveBeenCalled();
        expect(channelManager.replaceAllChannels).not.toHaveBeenCalled();
    });

    it('preserves reachedMaxChannels when canceled during creation in append mode', async () => {
        const { committer } = createHarness();
        const controller = new AbortController();
        let hasAborted = false;
        mockBuilder.createChannel.mockImplementationOnce(async (config: ChannelCreateInput) => {
            const channel = await Promise.resolve({
                ...makeExisting(2),
                id: 'built-2',
                name: config.name ?? 'Built 2',
                number: (config.number as number | undefined) ?? 2,
            } as ChannelConfig);
            builtChannels.push(channel);
            if (!hasAborted) {
                hasAborted = true;
                controller.abort();
            }
            return channel;
        });

        const result = await committer.commitBuild({
            buildMode: 'append',
            existingChannels: Array.from({ length: MAX_CHANNEL_NUMBER - 1 }, (_, index) => makeExisting(index + 1)),
            pendingToCreate: [makePending('One'), makePending('Two')],
            skippedCount: 0,
            reachedMaxChannels: true,
            errorCount: 0,
            diff: emptyDiff(),
            signal: controller.signal,
            reportProgress: (): void => undefined,
        });

        expect(result.summary.canceled).toBe(true);
        expect(result.summary.reachedMaxChannels).toBe(true);
        expect(result.summary.skipped).toBe(1);
    });

    it('disposes the builder before removing temporary storage keys', async () => {
        const { committer, scratchStoreCleanupKeys } = createHarness();

        await committer.commitBuild({
            buildMode: 'replace',
            existingChannels: [makeExisting(1)],
            pendingToCreate: [makePending('One')],
            skippedCount: 0,
            reachedMaxChannels: false,
            errorCount: 0,
            diff: emptyDiff(),
            signal: null,
            reportProgress: (): void => undefined,
        });

        const disposeOrder = mockBuilder.dispose.mock.invocationCallOrder[0];
        const removeOrder = scratchStoreCleanupKeys.mock.invocationCallOrder[0];
        expect(disposeOrder).toBeDefined();
        expect(removeOrder).toBeDefined();
        expect(disposeOrder as number).toBeLessThan(removeOrder as number);
    });

    it('allocates available numbers for append and merge builds', async () => {
        const { committer, channelManager } = createHarness();
        const existingChannels = [makeExisting(1), makeExisting(3)];

        await committer.commitBuild({
            buildMode: 'append',
            existingChannels,
            pendingToCreate: [makePending('Append One'), makePending('Append Two')],
            skippedCount: 0,
            reachedMaxChannels: false,
            errorCount: 0,
            diff: emptyDiff(),
            signal: null,
            reportProgress: (): void => undefined,
        });

        expect(mockBuilder.createChannel).toHaveBeenNthCalledWith(
            1,
            expect.objectContaining({ number: 2 }),
            expect.any(Object)
        );
        expect(mockBuilder.createChannel).toHaveBeenNthCalledWith(
            2,
            expect.objectContaining({ number: 4 }),
            expect.any(Object)
        );
        const [appendArgs] = channelManager.replaceAllChannels.mock.calls[0] ?? [];
        expect(appendArgs?.map((channel: ChannelConfig) => channel.number)).toEqual([1, 2, 3, 4]);

        builtChannels = [];
        mockBuilder.createChannel.mockClear();
        mockBuilder.getAllChannels.mockImplementation(() => builtChannels);

        const mergeDiff: ChannelDiffResult = {
            ...emptyDiff(),
            matchedPairs: [
                {
                    existing: existingChannels[0]!,
                    planned: {
                        ...makePending('Existing 1 Updated'),
                        playbackMode: 'sequential',
                        isPlaybackModeVariant: true,
                    },
                },
            ],
        };

        await committer.commitBuild({
            buildMode: 'merge',
            existingChannels,
            pendingToCreate: [makePending('Merge New')],
            skippedCount: 0,
            reachedMaxChannels: false,
            errorCount: 0,
            diff: mergeDiff,
            signal: null,
            reportProgress: (): void => undefined,
        });

        const [mergeArgs] = channelManager.replaceAllChannels.mock.calls[1] ?? [];
        const mergedExisting = mergeArgs?.find((channel: ChannelConfig) => channel.id === 'existing-1');
        expect(mergedExisting?.playbackMode).toBe('sequential');
        expect(mergedExisting?.isPlaybackModeVariant).toBe(true);
    });

    it('summarizes the built initial channel and successful guide refresh', async () => {
        const { committer } = createHarness();

        const result = await committer.commitBuild({
            buildMode: 'replace',
            existingChannels: [makeExisting(7)],
            pendingToCreate: [makePending('One')],
            skippedCount: 0,
            reachedMaxChannels: false,
            errorCount: 0,
            diff: emptyDiff(),
            signal: null,
            reportProgress: (): void => undefined,
        });

        expect(result.summary.initialChannelNumber).toBe(1);
        expect(result.summary.guideRefresh).toEqual(READY_GUIDE_REFRESH);
        expect(result.epgRefreshFailed).toBe(false);
    });

    it.each([
        {
            stage: 'ensure_initialized' as const,
            fail: (harness: Harness): void => {
                harness.ensureEpgInitialized.mockRejectedValueOnce(new Error('ensure failed'));
            },
            message: 'ensure failed',
        },
        {
            stage: 'prime_channels' as const,
            fail: (harness: Harness): void => {
                harness.primeEpgChannels.mockImplementationOnce(() => {
                    throw new Error('prime failed');
                });
            },
            message: 'prime failed',
        },
        {
            stage: 'refresh_schedules' as const,
            fail: (harness: Harness): void => {
                harness.refreshEpgSchedules.mockRejectedValueOnce(new Error('refresh failed'));
            },
            message: 'refresh failed',
        },
    ])('reports a non-fabricated $stage guide failure for multi-channel builds', async ({ stage, fail, message }) => {
        const harness = createHarness();
        fail(harness);
        const progress: ProgressEvent[] = [];

        const result = await harness.committer.commitBuild({
            buildMode: 'replace',
            existingChannels: [makeExisting(1)],
            pendingToCreate: [makePending('One'), makePending('Two'), makePending('Three')],
            skippedCount: 0,
            reachedMaxChannels: false,
            errorCount: 0,
            diff: emptyDiff(),
            signal: null,
            reportProgress: (
                task: ChannelBuildProgress['task'],
                label: string,
                detail: string,
                current: number,
                total: number | null
            ): void => {
                progress.push({ task, label, detail, current, total });
            },
        });

        expect(result.summary.lastTask).toBe('done');
        expect(result.summary.warnings).toEqual([
            `[ChannelSetup] EPG refresh failed after commit: ${message}`,
        ]);
        expect(result.summary.guideRefresh).toEqual({
            readiness: 'failed',
            failure: { kind: 'thrown', stage },
        });
        expect(result.summary.guideRefresh).not.toHaveProperty('attemptedChannelCount');
        expect(result.summary.guideRefresh).not.toHaveProperty('failedChannelCount');
        expect(progress.at(-1)).toEqual({
            task: 'done',
            label: 'Done!',
            detail: 'Built 3 channels (guide refresh failed)',
            current: 3,
            total: 3,
        });
    });

    it('surfaces degraded guide refresh readiness without treating the channel commit as failed', async () => {
        const { committer, refreshEpgSchedules } = createHarness();
        const partialGuideRefresh: EpgScheduleRefreshResult = {
            readiness: 'partial',
            attemptedChannelCount: 2,
            immediateReadyChannelCount: 1,
            backgroundQueuedChannelCount: 1,
            failedChannelCount: 1,
            staleCacheChannelCount: 0,
            firstVisibleScheduleReady: true,
        };
        refreshEpgSchedules.mockResolvedValueOnce(partialGuideRefresh);

        const result = await committer.commitBuild({
            buildMode: 'replace',
            existingChannels: [makeExisting(1)],
            pendingToCreate: [makePending('One'), makePending('Two')],
            skippedCount: 0,
            reachedMaxChannels: false,
            errorCount: 0,
            diff: emptyDiff(),
            signal: null,
            reportProgress: (): void => undefined,
        });

        expect(result.summary.guideRefresh).toEqual(partialGuideRefresh);
        expect(result.summary.warnings?.[0]).toContain(
            '[ChannelSetup] EPG refresh completed with degraded guide readiness'
        );
        expect(result.epgRefreshFailed).toBe(true);
    });

    it('surfaces skipped guide refresh readiness as degraded after commit', async () => {
        const { committer, refreshEpgSchedules } = createHarness();
        const skippedGuideRefresh: EpgScheduleRefreshResult = {
            readiness: 'skipped',
            attemptedChannelCount: 0,
            immediateReadyChannelCount: 0,
            backgroundQueuedChannelCount: 0,
            failedChannelCount: 0,
            staleCacheChannelCount: 0,
            firstVisibleScheduleReady: false,
        };
        refreshEpgSchedules.mockResolvedValueOnce(skippedGuideRefresh);

        const result = await committer.commitBuild({
            buildMode: 'replace',
            existingChannels: [makeExisting(1)],
            pendingToCreate: [makePending('One')],
            skippedCount: 0,
            reachedMaxChannels: false,
            errorCount: 0,
            diff: emptyDiff(),
            signal: null,
            reportProgress: (): void => undefined,
        });

        expect(result.summary.guideRefresh).toEqual(skippedGuideRefresh);
        expect(result.summary.warnings?.[0]).toContain(
            '[ChannelSetup] EPG refresh completed with degraded guide readiness'
        );
        expect(result.epgRefreshFailed).toBe(true);
    });

    it('does not report intentional guide refresh supersession as a setup failure', async () => {
        const { committer, refreshEpgSchedules } = createHarness();
        const supersededGuideRefresh: EpgScheduleRefreshResult = {
            ...READY_GUIDE_REFRESH,
            readiness: 'superseded',
            attemptedChannelCount: 0,
            immediateReadyChannelCount: 0,
            firstVisibleScheduleReady: false,
        };
        refreshEpgSchedules.mockResolvedValueOnce(supersededGuideRefresh);

        const result = await committer.commitBuild({
            buildMode: 'replace',
            existingChannels: [makeExisting(1)],
            pendingToCreate: [makePending('One')],
            skippedCount: 0,
            reachedMaxChannels: false,
            errorCount: 0,
            diff: emptyDiff(),
            signal: null,
            reportProgress: (): void => undefined,
        });

        expect(result.summary.guideRefresh).toEqual(supersededGuideRefresh);
        expect(result.summary.warnings).toBeUndefined();
        expect(result.epgRefreshFailed).toBe(false);
    });

    it('runs post-commit EPG refresh in the required order', async () => {
        const {
            committer,
            clearSelectedChannelScheduleSnapshot,
            ensureEpgInitialized,
            primeEpgChannels,
            refreshEpgSchedules,
        } = createHarness();

        await committer.commitBuild({
            buildMode: 'replace',
            existingChannels: [makeExisting(1)],
            pendingToCreate: [makePending('One')],
            skippedCount: 0,
            reachedMaxChannels: false,
            errorCount: 0,
            diff: emptyDiff(),
            signal: null,
            reportProgress: (): void => undefined,
        });

        const clearOrder = clearSelectedChannelScheduleSnapshot.mock.invocationCallOrder[0];
        const ensureOrder = ensureEpgInitialized.mock.invocationCallOrder[0];
        const primeOrder = primeEpgChannels.mock.invocationCallOrder[0];
        const refreshOrder = refreshEpgSchedules.mock.invocationCallOrder[0];
        expect(clearOrder as number).toBeLessThan(ensureOrder as number);
        expect(ensureOrder as number).toBeLessThan(primeOrder as number);
        expect(primeOrder as number).toBeLessThan(refreshOrder as number);
        expect(refreshEpgSchedules).toHaveBeenCalledWith({
            reason: 'channel-setup',
            debounceMs: 0,
            signal: null,
        });
    });

    it('propagates post-commit EPG refresh aborts without marking refresh failure', async () => {
        const { committer, refreshEpgSchedules } = createHarness();
        const abortReason = new DOMException('build canceled', 'AbortError');
        const controller = new AbortController();
        refreshEpgSchedules.mockImplementationOnce(() => {
            controller.abort(abortReason);
            return Promise.reject(abortReason);
        });

        await expect(committer.commitBuild({
            buildMode: 'replace',
            existingChannels: [makeExisting(1)],
            pendingToCreate: [makePending('One')],
            skippedCount: 0,
            reachedMaxChannels: false,
            errorCount: 0,
            diff: emptyDiff(),
            signal: controller.signal,
            reportProgress: (): void => undefined,
        })).rejects.toBe(abortReason);

        expect(refreshEpgSchedules).toHaveBeenCalledWith({
            reason: 'channel-setup',
            debounceMs: 0,
            signal: controller.signal,
        });
    });
});
