import {
    buildChannelSetupPlan,
    buildChannelSetupPlanDiagnostics,
} from '../planning/ChannelSetupPlanner';
import {
    createChannelIdentityKey,
    diffChannelPlans,
} from '../planning/ChannelSetupPlanningTypes';
import type { ChannelSetupConfig, SetupStrategyConfig, SetupStrategyKey } from '../types';
import type { PlexLibrarySection, PlexPlaylist } from '../../../modules/plex/library';
import type { ChannelConfig } from '../../../modules/scheduler/channel-manager';
import type { PendingChannel } from '../planning/ChannelSetupPlanningTypes';
import { DEFAULT_STRATEGY_PRIORITIES, MIXED_SCOPE_STRATEGY_KEYS, SETUP_STRATEGY_KEYS } from '../constants';

const seedFor = (value: string): number => {
    let hash = 0;
    for (let i = 0; i < value.length; i++) {
        hash = ((hash << 5) - hash) + value.charCodeAt(i);
        hash |= 0;
    }
    return Math.abs(hash);
};

const createStrategyConfig = (
    overrides?: Partial<Record<SetupStrategyKey, Partial<SetupStrategyConfig>>>
): Record<SetupStrategyKey, SetupStrategyConfig> => (
    SETUP_STRATEGY_KEYS.reduce<Record<SetupStrategyKey, SetupStrategyConfig>>((acc, key) => {
        const candidate = overrides?.[key];
        acc[key] = {
            enabled: candidate?.enabled ?? false,
            priority: candidate?.priority ?? DEFAULT_STRATEGY_PRIORITIES[key],
            scope: MIXED_SCOPE_STRATEGY_KEYS.has(key) && candidate?.scope === 'cross-library' ? 'cross-library' : 'per-library',
        };
        return acc;
    }, {} as Record<SetupStrategyKey, SetupStrategyConfig>)
);

const createConfig = (overrides?: Partial<ChannelSetupConfig>): ChannelSetupConfig => ({
    serverId: 'server-1',
    selectedLibraryIds: [],
    maxChannels: 50,
    buildMode: 'replace',
    strategyConfig: createStrategyConfig(),
    actorStudioCombineMode: 'separate',
    minItemsPerChannel: 1,
    ...overrides,
});

const makeExistingChannel = (planned: PendingChannel, index: number): ChannelConfig => {
    const existing: ChannelConfig = {
        id: `ch-${index + 1}`,
        number: index + 1,
        name: `Existing ${index + 1}`,
        contentSource: planned.contentSource,
        playbackMode: planned.playbackMode,
        shuffleSeed: planned.shuffleSeed,
        phaseSeed: 1,
        startTimeAnchor: 0,
        skipIntros: false,
        skipCredits: false,
        createdAt: 0,
        updatedAt: 0,
        lastContentRefresh: 0,
        itemCount: 0,
        totalDurationMs: 0,
    };
    if (planned.isAutoGenerated !== undefined) {
        existing.isAutoGenerated = planned.isAutoGenerated;
    }
    if (planned.buildStrategy !== undefined) {
        existing.buildStrategy = planned.buildStrategy;
    }
    if (planned.sourceLibraryId !== undefined) {
        existing.sourceLibraryId = planned.sourceLibraryId;
    }
    if (planned.sourceLibraryName !== undefined) {
        existing.sourceLibraryName = planned.sourceLibraryName;
    }
    if (planned.lineupReplicaIndex !== undefined) {
        existing.lineupReplicaIndex = planned.lineupReplicaIndex;
    }
    if (planned.isPlaybackModeVariant !== undefined) {
        existing.isPlaybackModeVariant = planned.isPlaybackModeVariant;
    }
    if (planned.blockSize !== undefined) {
        existing.blockSize = planned.blockSize;
    }
    return existing;
};

describe('ChannelSetupPlanner', () => {
    it('defaults alternateLineupCopies to 1 when addAlternateLineups is true but copies is non-finite', () => {
        const playlists: PlexPlaylist[] = [
            {
                ratingKey: 'pl1',
                key: '/playlists/pl1',
                title: 'Favorites',
                thumb: null,
                duration: 0,
                leafCount: 10,
            },
        ];

        const plan = buildChannelSetupPlan({
            config: createConfig({
                strategyConfig: createStrategyConfig({ playlists: { enabled: true } }),
                channelExpansion: {
                    addAlternateLineups: true,
                    alternateLineupCopies: Number.NaN,
                    variantType: 'none',
                    variantBlockSize: 3,
                },
            }),
            libraries: [],
            playlists,
            collectionsByLibraryId: new Map(),
            genresByLibraryId: new Map(),
            directorsByLibraryId: new Map(),
            yearsByLibraryId: new Map(),
            actorsByLibraryId: new Map(),
            studiosByLibraryId: new Map(),
            warnings: [],
            seedFor,
        });

        expect(plan.pendingChannels.map((c) => c.name)).toEqual(['Favorites', 'Favorites (2)']);
        expect(plan.pendingChannels.map((c) => c.lineupReplicaIndex)).toEqual([0, 1]);
    });

    it('diffChannelPlans matches base/copy/sequential variants without identity collisions', () => {
        const playlists: PlexPlaylist[] = [
            {
                ratingKey: 'pl1',
                key: '/playlists/pl1',
                title: 'Favorites',
                thumb: null,
                duration: 0,
                leafCount: 10,
            },
        ];

        const plan = buildChannelSetupPlan({
            config: createConfig({
                strategyConfig: createStrategyConfig({ playlists: { enabled: true } }),
                channelExpansion: {
                    addAlternateLineups: true,
                    alternateLineupCopies: 2,
                    variantType: 'sequential',
                    variantBlockSize: 3,
                },
            }),
            libraries: [],
            playlists,
            collectionsByLibraryId: new Map(),
            genresByLibraryId: new Map(),
            directorsByLibraryId: new Map(),
            yearsByLibraryId: new Map(),
            actorsByLibraryId: new Map(),
            studiosByLibraryId: new Map(),
            warnings: [],
            seedFor,
        });

        const identityKeys = plan.pendingChannels.map((channel) => createChannelIdentityKey(channel));
        expect(new Set(identityKeys).size).toBe(plan.pendingChannels.length);

        const existing: ChannelConfig[] = plan.pendingChannels.map(makeExistingChannel);

        const diff = diffChannelPlans(existing, plan.pendingChannels);
        expect(diff.summary).toEqual({ created: 0, removed: 0, unchanged: plan.pendingChannels.length });
        expect(diff.matchedPairs).toHaveLength(plan.pendingChannels.length);
    });

    it('does not create sequential variants for alternate shuffle replicas', () => {
        const plan = buildChannelSetupPlan({
            config: createConfig({
                selectedLibraryIds: ['show-1'],
                strategyConfig: createStrategyConfig({ genres: { enabled: true } }),
                channelExpansion: {
                    addAlternateLineups: true,
                    alternateLineupCopies: 2,
                    variantType: 'sequential',
                    variantBlockSize: 3,
                },
            }),
            libraries: [{ id: 'show-1', title: 'Shows', type: 'show', contentCount: 20 }] as PlexLibrarySection[],
            playlists: [],
            collectionsByLibraryId: new Map(),
            genresByLibraryId: new Map([['show-1', [{ key: 'genre-1', title: 'Comedy', count: 20 }]]]),
            directorsByLibraryId: new Map(),
            yearsByLibraryId: new Map(),
            actorsByLibraryId: new Map(),
            studiosByLibraryId: new Map(),
            warnings: [],
            seedFor,
        });

        expect(plan.pendingChannels.map((channel) => channel.name)).toEqual([
            'Shows - Comedy',
            'Shows - Comedy (2)',
            'Shows - Comedy (3)',
            'Shows - Comedy • Sequential',
        ]);
        expect(
            plan.pendingChannels.filter((channel) => channel.isPlaybackModeVariant)
        ).toHaveLength(1);
    });

    it('uses isPlaybackModeVariant as the canonical playback variant key in identity hashes', () => {
        const variantCandidate: PendingChannel = {
            name: 'Variant',
            contentSource: {
                type: 'library',
                libraryId: 'library-identity',
                libraryType: 'show',
                includeWatched: true,
            },
            playbackMode: 'block',
            lineupReplicaIndex: 0,
            isPlaybackModeVariant: true,
            shuffleSeed: 123,
        } as PendingChannel;

        const identityKey = createChannelIdentityKey(variantCandidate);

        expect(identityKey).toContain('"isPlaybackModeVariant":true');
        expect(identityKey).toContain('"variantPlaybackMode":"block"');
        expect(identityKey).not.toContain('"isSequentialVariant":true');
    });

    it('uses block size as part of block playback variant identity', () => {
        const blockSizeThree: PendingChannel = {
            name: 'Variant',
            contentSource: {
                type: 'library',
                libraryId: 'library-identity',
                libraryType: 'show',
                includeWatched: true,
            },
            playbackMode: 'block',
            blockSize: 3,
            lineupReplicaIndex: 0,
            isPlaybackModeVariant: true,
            shuffleSeed: 123,
        } as PendingChannel;
        const blockSizeFour: PendingChannel = {
            ...blockSizeThree,
            blockSize: 4,
        };

        expect(createChannelIdentityKey(blockSizeThree)).not.toBe(
            createChannelIdentityKey(blockSizeFour)
        );
    });

    it('normalizes filter identity deterministically across mixed value types', () => {
        const first: PendingChannel = {
            name: 'Filtered',
            contentSource: {
                type: 'library',
                libraryId: 'library-filter',
                libraryType: 'movie',
                includeWatched: true,
            },
            contentFilters: [
                { field: 'contentRating', operator: 'eq', value: 'true' },
                { field: 'contentRating', operator: 'eq', value: true },
            ],
            playbackMode: 'shuffle',
            shuffleSeed: 123,
        } as PendingChannel;
        const second: PendingChannel = {
            ...first,
            contentFilters: [...first.contentFilters!].reverse(),
        };

        expect(createChannelIdentityKey(first)).toBe(createChannelIdentityKey(second));
    });

    it('emits per-library genre channels using libraryFilter instead of contentFilters', () => {
        const plan = buildChannelSetupPlan({
            config: createConfig({
                selectedLibraryIds: ['s1'],
                strategyConfig: createStrategyConfig({ genres: { enabled: true } }),
                minItemsPerChannel: 1,
            }),
            libraries: [{ id: 's1', title: 'Shows', type: 'show', contentCount: 25 }] as PlexLibrarySection[],
            playlists: [],
            collectionsByLibraryId: new Map(),
            genresByLibraryId: new Map([['s1', [{ key: 'action', title: 'Action', count: 10 }]]]),
            directorsByLibraryId: new Map(),
            yearsByLibraryId: new Map(),
            actorsByLibraryId: new Map(),
            studiosByLibraryId: new Map(),
            warnings: [],
            seedFor,
        });

        const action = plan.pendingChannels.find((c) => c.name === 'Shows - Action');
        expect(action).toBeDefined();
        expect(action?.contentSource).toEqual(expect.objectContaining({
            type: 'library',
            libraryId: 's1',
            libraryType: 'show',
            includeWatched: true,
            libraryFilter: { genre: 'Action' },
        }));
        expect(action?.contentFilters).toBeUndefined();
    });

    it('orders per-library facet channels deterministically when selected libraries share the same title', () => {
        const plan = buildChannelSetupPlan({
            config: createConfig({
                selectedLibraryIds: ['lib-b', 'lib-a'],
                strategyConfig: createStrategyConfig({ genres: { enabled: true } }),
                minItemsPerChannel: 1,
            }),
            libraries: [
                { id: 'lib-b', title: 'Shows', type: 'show', contentCount: 25 },
                { id: 'lib-a', title: 'Shows', type: 'show', contentCount: 25 },
            ] as PlexLibrarySection[],
            playlists: [],
            collectionsByLibraryId: new Map(),
            genresByLibraryId: new Map([
                ['lib-b', [{ key: 'beta', title: 'Beta', count: 10 }]],
                ['lib-a', [{ key: 'zeta', title: 'Zeta', count: 10 }]],
            ]),
            directorsByLibraryId: new Map(),
            yearsByLibraryId: new Map(),
            actorsByLibraryId: new Map(),
            studiosByLibraryId: new Map(),
            warnings: [],
            seedFor,
        });

        expect(plan.pendingChannels.map((channel) => channel.name)).toEqual([
            'Shows - Zeta',
            'Shows - Beta',
        ]);
    });

    it('does not drop native facet channels when Plex tag directories omit counts', () => {
        const plan = buildChannelSetupPlan({
            config: createConfig({
                selectedLibraryIds: ['s1'],
                strategyConfig: createStrategyConfig({
                    genres: { enabled: true },
                    studios: { enabled: true },
                }),
                minItemsPerChannel: 5,
            }),
            libraries: [{ id: 's1', title: 'Shows', type: 'show', contentCount: 25 }] as PlexLibrarySection[],
            playlists: [],
            collectionsByLibraryId: new Map(),
            genresByLibraryId: new Map([['s1', [{ key: 'action', title: 'Action', count: null }]]]),
            directorsByLibraryId: new Map(),
            yearsByLibraryId: new Map(),
            actorsByLibraryId: new Map(),
            studiosByLibraryId: new Map([['s1', [{ key: 'studio-a', title: 'Studio A', count: null }]]]),
            warnings: [],
            seedFor,
        });

        expect(plan.pendingChannels.map((channel) => channel.name)).toContain('Shows - Action');
        expect(plan.pendingChannels.map((channel) => channel.name)).toContain('Studio A - Shows');
    });

    it('marks a legacy per-library genre channel as replaced when libraryFilter becomes source-of-truth', () => {
        const plan = buildChannelSetupPlan({
            config: createConfig({
                selectedLibraryIds: ['s1'],
                strategyConfig: createStrategyConfig({ genres: { enabled: true } }),
                minItemsPerChannel: 1,
            }),
            libraries: [{ id: 's1', title: 'Shows', type: 'show', contentCount: 25 }] as PlexLibrarySection[],
            playlists: [],
            collectionsByLibraryId: new Map(),
            genresByLibraryId: new Map([['s1', [{ key: 'action', title: 'Action', count: 10 }]]]),
            directorsByLibraryId: new Map(),
            yearsByLibraryId: new Map(),
            actorsByLibraryId: new Map(),
            studiosByLibraryId: new Map(),
            warnings: [],
            seedFor,
        });

        const plannedGenreChannel = plan.pendingChannels.find((c) => c.name === 'Shows - Action');
        expect(plannedGenreChannel).toBeDefined();

        const legacyExisting = makeExistingChannel(
            {
                ...plannedGenreChannel!,
                contentSource: {
                    type: 'library',
                    libraryId: 's1',
                    libraryType: 'show',
                    includeWatched: true,
                },
                contentFilters: [{ field: 'genre', operator: 'eq', value: 'Action' }],
            } as PendingChannel,
            0
        );

        const diff = diffChannelPlans([legacyExisting], plan.pendingChannels);
        expect(diff.summary).toEqual({ created: 1, removed: 1, unchanged: 0 });
        expect(diff.created).toHaveLength(1);
        expect(diff.removed).toHaveLength(1);
        expect(diff.unchanged).toHaveLength(0);
    });

    it('generates block variants for series-derived channels with unique identity keys', () => {
        const plan = buildChannelSetupPlan({
            config: createConfig({
                selectedLibraryIds: ['s1'],
                strategyConfig: createStrategyConfig({ collections: { enabled: true } }),
                channelExpansion: {
                    addAlternateLineups: false,
                    alternateLineupCopies: 1,
                    variantType: 'block',
                    variantBlockSize: 4,
                },
            }),
            libraries: [{ id: 's1', title: 'Shows', type: 'show', contentCount: 10 }] as PlexLibrarySection[],
            playlists: [],
            collectionsByLibraryId: new Map([
                ['s1', [{ ratingKey: 'co1', key: '/library/collections/co1', title: 'Classics', thumb: null, childCount: 10 }]],
            ]),
            genresByLibraryId: new Map(),
            directorsByLibraryId: new Map(),
            yearsByLibraryId: new Map(),
            actorsByLibraryId: new Map(),
            studiosByLibraryId: new Map(),
            warnings: [],
            seedFor,
        });

        const names = plan.pendingChannels.map((channel) => channel.name);
        expect(names).toContain('Classics');
        expect(names).toContain('Classics • Block');

        const blockVariant = plan.pendingChannels.find(
            (channel) => channel.name === 'Classics • Block'
        );
        expect(blockVariant).toBeDefined();
        expect(blockVariant?.playbackMode).toBe('block');
        expect(blockVariant?.blockSize).toBe(4);
        expect(blockVariant?.isPlaybackModeVariant).toBe(true);

        const sequentialVariantCandidate: PendingChannel = {
            ...(blockVariant as PendingChannel),
            playbackMode: 'sequential',
        };
        expect(createChannelIdentityKey(blockVariant as PendingChannel)).not.toBe(
            createChannelIdentityKey(sequentialVariantCandidate)
        );
    });

    it('does not duplicate a block variant when base series ordering already matches it', () => {
        const plan = buildChannelSetupPlan({
            config: createConfig({
                selectedLibraryIds: ['s1'],
                strategyConfig: createStrategyConfig({ collections: { enabled: true } }),
                seriesOrdering: {
                    basePlaybackMode: 'block',
                    baseBlockSize: 3,
                },
                channelExpansion: {
                    addAlternateLineups: false,
                    alternateLineupCopies: 1,
                    variantType: 'block',
                    variantBlockSize: 3,
                },
            }),
            libraries: [{ id: 's1', title: 'Shows', type: 'show', contentCount: 10 }] as PlexLibrarySection[],
            playlists: [],
            collectionsByLibraryId: new Map([
                ['s1', [{ ratingKey: 'co1', key: '/library/collections/co1', title: 'Classics', thumb: null, childCount: 10 }]],
            ]),
            genresByLibraryId: new Map(),
            directorsByLibraryId: new Map(),
            yearsByLibraryId: new Map(),
            actorsByLibraryId: new Map(),
            studiosByLibraryId: new Map(),
            warnings: [],
            seedFor,
        });

        expect(plan.pendingChannels.map((channel) => channel.name)).toEqual(['Classics']);
        expect(plan.pendingChannels[0]?.playbackMode).toBe('block');
        expect(plan.pendingChannels[0]?.blockSize).toBe(3);
    });

    it('treats mixed TV-only channels as series-derived for base series ordering and variants', () => {
        const plan = buildChannelSetupPlan({
            config: createConfig({
                selectedLibraryIds: ['s1', 's2'],
                strategyConfig: createStrategyConfig({ actors: { enabled: true, scope: 'cross-library' } }),
                seriesOrdering: {
                    basePlaybackMode: 'block',
                    baseBlockSize: 3,
                },
                channelExpansion: {
                    addAlternateLineups: false,
                    alternateLineupCopies: 1,
                    variantType: 'sequential',
                    variantBlockSize: 3,
                },
            }),
            libraries: [
                { id: 's1', title: 'Shows A', type: 'show', contentCount: 10 },
                { id: 's2', title: 'Shows B', type: 'show', contentCount: 10 },
            ] as PlexLibrarySection[],
            playlists: [],
            collectionsByLibraryId: new Map(),
            genresByLibraryId: new Map(),
            directorsByLibraryId: new Map(),
            yearsByLibraryId: new Map(),
            actorsByLibraryId: new Map([
                ['s1', [{ key: 'actor-1', title: 'Jane Doe', count: 10 }]],
                ['s2', [{ key: 'actor-1', title: 'Jane Doe', count: 10 }]],
            ]),
            studiosByLibraryId: new Map(),
            warnings: [],
            seedFor,
        });

        const base = plan.pendingChannels.find((channel) => channel.name === 'Jane Doe');
        expect(base).toBeDefined();
        expect(base?.contentSource.type).toBe('mixed');
        expect(base?.playbackMode).toBe('block');
        expect(base?.blockSize).toBe(3);

        const sequentialVariant = plan.pendingChannels.find((channel) => channel.name === 'Jane Doe • Sequential');
        expect(sequentialVariant).toBeDefined();
        expect(sequentialVariant?.playbackMode).toBe('sequential');
        expect(sequentialVariant?.isPlaybackModeVariant).toBe(true);
    });

    it('preserves known cross-library subtotals for ordering when another source omits counts', () => {
        const plan = buildChannelSetupPlan({
            config: createConfig({
                selectedLibraryIds: ['s1', 's2'],
                minItemsPerChannel: 5,
                strategyConfig: createStrategyConfig({
                    genres: { enabled: true, scope: 'cross-library' },
                }),
                channelExpansion: {
                    addAlternateLineups: false,
                    alternateLineupCopies: 1,
                    variantType: 'none',
                    variantBlockSize: 3,
                },
            }),
            libraries: [
                { id: 's1', title: 'Shows A', type: 'show', contentCount: 10 },
                { id: 's2', title: 'Shows B', type: 'show', contentCount: 10 },
            ] as PlexLibrarySection[],
            playlists: [],
            collectionsByLibraryId: new Map(),
            genresByLibraryId: new Map([
                ['s1', [{ key: 'genre-action-a', title: 'Action', count: 9 }]],
                ['s2', [
                    { key: 'genre-action-b', title: 'Action', count: null },
                    { key: 'genre-drama-b', title: 'Drama', count: 8 },
                ]],
            ]),
            directorsByLibraryId: new Map(),
            yearsByLibraryId: new Map(),
            actorsByLibraryId: new Map(),
            studiosByLibraryId: new Map(),
            warnings: [],
            seedFor,
        });

        expect(plan.pendingChannels.map((channel) => channel.name)).toEqual(['Action', 'Drama']);
    });

    it('preserves known cross-library subtotals for actors when another source omits counts', () => {
        const plan = buildChannelSetupPlan({
            config: createConfig({
                selectedLibraryIds: ['s1', 's2'],
                minItemsPerChannel: 5,
                strategyConfig: createStrategyConfig({
                    actors: { enabled: true, scope: 'cross-library' },
                }),
                channelExpansion: {
                    addAlternateLineups: false,
                    alternateLineupCopies: 1,
                    variantType: 'none',
                    variantBlockSize: 3,
                },
            }),
            libraries: [
                { id: 's1', title: 'Shows A', type: 'show', contentCount: 10 },
                { id: 's2', title: 'Shows B', type: 'show', contentCount: 10 },
            ] as PlexLibrarySection[],
            playlists: [],
            collectionsByLibraryId: new Map(),
            genresByLibraryId: new Map(),
            directorsByLibraryId: new Map(),
            yearsByLibraryId: new Map(),
            actorsByLibraryId: new Map([
                ['s1', [{ key: 'actor-alex-a', title: 'Alex Star', count: 9 }]],
                ['s2', [
                    { key: 'actor-alex-b', title: 'Alex Star', count: null },
                    { key: 'actor-blake-b', title: 'Blake Star', count: 8 },
                ]],
            ]),
            studiosByLibraryId: new Map(),
            warnings: [],
            seedFor,
        });

        expect(plan.pendingChannels.map((channel) => channel.name)).toEqual(['Alex Star', 'Blake Star']);
    });

    it('sanitizes non-finite/invalid baseBlockSize for base series ordering', () => {
        const plan = buildChannelSetupPlan({
            config: createConfig({
                selectedLibraryIds: ['s1'],
                strategyConfig: createStrategyConfig({ collections: { enabled: true } }),
                seriesOrdering: {
                    basePlaybackMode: 'block',
                    baseBlockSize: Number.NaN,
                },
            }),
            libraries: [{ id: 's1', title: 'Shows', type: 'show', contentCount: 10 }] as PlexLibrarySection[],
            playlists: [],
            collectionsByLibraryId: new Map([
                ['s1', [{ ratingKey: 'co1', key: '/library/collections/co1', title: 'Classics', thumb: null, childCount: 10 }]],
            ]),
            genresByLibraryId: new Map(),
            directorsByLibraryId: new Map(),
            yearsByLibraryId: new Map(),
            actorsByLibraryId: new Map(),
            studiosByLibraryId: new Map(),
            warnings: [],
            seedFor,
        });

        const base = plan.pendingChannels.find((channel) => channel.name === 'Classics');
        expect(base).toBeDefined();
        expect(base?.playbackMode).toBe('block');
        expect(base?.blockSize).toBe(3);
    });

    it('sanitizes non-finite/invalid variantBlockSize for block variants', () => {
        const plan = buildChannelSetupPlan({
            config: createConfig({
                selectedLibraryIds: ['s1'],
                strategyConfig: createStrategyConfig({ collections: { enabled: true } }),
                channelExpansion: {
                    addAlternateLineups: false,
                    alternateLineupCopies: 1,
                    variantType: 'block',
                    variantBlockSize: 0,
                },
            }),
            libraries: [{ id: 's1', title: 'Shows', type: 'show', contentCount: 10 }] as PlexLibrarySection[],
            playlists: [],
            collectionsByLibraryId: new Map([
                ['s1', [{ ratingKey: 'co1', key: '/library/collections/co1', title: 'Classics', thumb: null, childCount: 10 }]],
            ]),
            genresByLibraryId: new Map(),
            directorsByLibraryId: new Map(),
            yearsByLibraryId: new Map(),
            actorsByLibraryId: new Map(),
            studiosByLibraryId: new Map(),
            warnings: [],
            seedFor,
        });

        const variant = plan.pendingChannels.find((channel) => channel.name === 'Classics • Block');
        expect(variant).toBeDefined();
        expect(variant?.playbackMode).toBe('block');
        expect(variant?.blockSize).toBe(3);
    });

    it('falls back when series ordering/variant types are runtime-invalid', () => {
        const plan = buildChannelSetupPlan({
            config: createConfig({
                selectedLibraryIds: ['s1'],
                strategyConfig: createStrategyConfig({ collections: { enabled: true } }),
                seriesOrdering: {
                    basePlaybackMode: 'bogus' as unknown as 'shuffle' | 'sequential' | 'block',
                    baseBlockSize: 3,
                },
                channelExpansion: {
                    addAlternateLineups: false,
                    alternateLineupCopies: 1,
                    variantType: 'bogus' as unknown as 'none' | 'sequential' | 'block',
                    variantBlockSize: 3,
                },
            }),
            libraries: [{ id: 's1', title: 'Shows', type: 'show', contentCount: 10 }] as PlexLibrarySection[],
            playlists: [],
            collectionsByLibraryId: new Map([
                ['s1', [{ ratingKey: 'co1', key: '/library/collections/co1', title: 'Classics', thumb: null, childCount: 10 }]],
            ]),
            genresByLibraryId: new Map(),
            directorsByLibraryId: new Map(),
            yearsByLibraryId: new Map(),
            actorsByLibraryId: new Map(),
            studiosByLibraryId: new Map(),
            warnings: [],
            seedFor,
        });

        expect(plan.pendingChannels.map((channel) => channel.name)).toEqual(['Classics']);
        const base = plan.pendingChannels.find((channel) => channel.name === 'Classics');
        expect(base?.playbackMode).toBe('shuffle');
    });

    it('derives decades from summed year directories', () => {
        const plan = buildChannelSetupPlan({
            config: createConfig({
                selectedLibraryIds: ['s1'],
                strategyConfig: createStrategyConfig({ decades: { enabled: true } }),
                minItemsPerChannel: 5,
            }),
            libraries: [{ id: 's1', title: 'Shows', type: 'show', contentCount: 1200 }] as PlexLibrarySection[],
            playlists: [],
            collectionsByLibraryId: new Map(),
            genresByLibraryId: new Map(),
            directorsByLibraryId: new Map(),
            yearsByLibraryId: new Map([
                ['s1', [
                    { key: '1981', title: '1981', count: 2 },
                    { key: '1988', title: '1988', count: 3 },
                    { key: '1995', title: '1995', count: 4 },
                ]],
            ]),
            actorsByLibraryId: new Map(),
            studiosByLibraryId: new Map(),
            warnings: [],
            seedFor,
        });

        expect(plan.pendingChannels.map((channel) => channel.name)).toContain('Shows - 1980s');
        expect(plan.pendingChannels.map((channel) => channel.name)).not.toContain('Shows - 1990s');
    });

    it('does not drop decade channels when Plex year tags omit counts', () => {
        const plan = buildChannelSetupPlan({
            config: createConfig({
                selectedLibraryIds: ['s1'],
                strategyConfig: createStrategyConfig({ decades: { enabled: true } }),
                minItemsPerChannel: 5,
            }),
            libraries: [{ id: 's1', title: 'Shows', type: 'show', contentCount: 1200 }] as PlexLibrarySection[],
            playlists: [],
            collectionsByLibraryId: new Map(),
            genresByLibraryId: new Map(),
            directorsByLibraryId: new Map(),
            yearsByLibraryId: new Map([
                ['s1', [
                    { key: '1981', title: '1981', count: null },
                    { key: '1988', title: '1988', count: null },
                ]],
            ]),
            actorsByLibraryId: new Map(),
            studiosByLibraryId: new Map(),
            warnings: [],
            seedFor,
        });

        expect(plan.pendingChannels.map((channel) => channel.name)).toContain('Shows - 1980s');
    });

    it('counts min-item-rejected native facet candidates in plan.skipped', () => {
        const plan = buildChannelSetupPlan({
            config: createConfig({
                selectedLibraryIds: ['m1'],
                minItemsPerChannel: 5,
                strategyConfig: createStrategyConfig({
                    genres: { enabled: true },
                    directors: { enabled: true },
                    decades: { enabled: true },
                    studios: { enabled: true },
                    actors: { enabled: true },
                }),
                channelExpansion: {
                    addAlternateLineups: false,
                    alternateLineupCopies: 1,
                    variantType: 'none',
                    variantBlockSize: 3,
                },
            }),
            libraries: [{ id: 'm1', title: 'Movies', type: 'movie', contentCount: 25 }] as PlexLibrarySection[],
            playlists: [],
            collectionsByLibraryId: new Map(),
            genresByLibraryId: new Map([['m1', [
                { key: 'genre-a', title: 'Action', count: 8 },
                { key: 'genre-b', title: 'Drama', count: 2 },
            ]]]),
            directorsByLibraryId: new Map([['m1', [
                { key: 'dir-a', title: 'Jane Doe', count: 6 },
                { key: 'dir-b', title: 'John Roe', count: 4 },
            ]]]),
            yearsByLibraryId: new Map([['m1', [
                { key: '1981', title: '1981', count: 2 },
                { key: '1994', title: '1994', count: 8 },
            ]]]),
            actorsByLibraryId: new Map([['m1', [
                { key: 'actor-a', title: 'Alex Star', count: 10 },
                { key: 'actor-b', title: 'Blake Star', count: 1 },
            ]]]),
            studiosByLibraryId: new Map([['m1', [
                { key: 'studio-a', title: 'Studio A', count: 7 },
                { key: 'studio-b', title: 'Studio B', count: 3 },
            ]]]),
            warnings: [],
            seedFor,
        });

        expect(plan.skipped).toBe(5);
        expect(plan.pendingChannels.map((channel) => channel.name)).toEqual(expect.arrayContaining([
            'Movies - Action',
            'Movies - Jane Doe',
            'Movies - 1990s',
            'Studio A - Movies',
            'Alex Star - Movies',
        ]));
    });

    it('counts rejected decade candidates once while preserving diagnostics totals', () => {
        const diagnostics = buildChannelSetupPlanDiagnostics({
            config: createConfig({
                selectedLibraryIds: ['m1'],
                minItemsPerChannel: 5,
                strategyConfig: createStrategyConfig({
                    decades: { enabled: true },
                }),
            }),
            libraries: [{ id: 'm1', title: 'Movies', type: 'movie', contentCount: 25 }] as PlexLibrarySection[],
            playlists: [],
            collectionsByLibraryId: new Map(),
            genresByLibraryId: new Map(),
            directorsByLibraryId: new Map(),
            yearsByLibraryId: new Map([['m1', [
                { key: '1981', title: '1981', count: 2 },
                { key: '1988', title: '1988', count: 1 },
                { key: '1994', title: '1994', count: 8 },
            ]]]),
            actorsByLibraryId: new Map(),
            studiosByLibraryId: new Map(),
            warnings: [],
            seedFor,
        });

        expect(diagnostics.candidatesBeforeMinItems.decades).toBe(2);
        expect(diagnostics.candidatesAfterMinItems.decades).toBe(1);
    });

    it('reports fetched-tag and candidate counts for native facet families', () => {
        const diagnostics = buildChannelSetupPlanDiagnostics({
            config: createConfig({
                selectedLibraryIds: ['m1'],
                minItemsPerChannel: 5,
                strategyConfig: createStrategyConfig({
                    genres: { enabled: true },
                    directors: { enabled: true },
                    studios: { enabled: true },
                    actors: { enabled: true },
                }),
            }),
            libraries: [{ id: 'm1', title: 'Movies', type: 'movie', contentCount: 25 }] as PlexLibrarySection[],
            playlists: [],
            collectionsByLibraryId: new Map(),
            genresByLibraryId: new Map([['m1', [
                { key: 'genre-a', title: 'Action', count: 8 },
                { key: 'genre-b', title: 'Drama', count: 2 },
                { key: 'genre-c', title: 'Mystery', count: null },
            ]]]),
            directorsByLibraryId: new Map([['m1', [
                { key: 'dir-a', title: 'Jane Doe', count: 6 },
                { key: 'dir-b', title: 'John Roe', count: 4 },
            ]]]),
            yearsByLibraryId: new Map(),
            actorsByLibraryId: new Map([['m1', [
                { key: 'actor-a', title: 'Alex Star', count: 10 },
                { key: 'actor-b', title: 'Blake Star', count: 1 },
                { key: 'actor-c', title: 'Casey Star', count: null },
            ]]]),
            studiosByLibraryId: new Map([['m1', [
                { key: 'studio-a', title: 'Studio A', count: 7 },
                { key: 'studio-b', title: 'Studio B', count: 3 },
            ]]]),
            warnings: [],
            seedFor,
        });

        expect(diagnostics.minItems).toBe(5);
        expect(diagnostics.effectiveMaxChannels).toBeGreaterThan(0);
        expect(diagnostics.fetchedTagsByFamily.genres).toEqual([
            { libraryId: 'm1', libraryName: 'Movies', count: 3 },
        ]);
        expect(diagnostics.fetchedTagsByFamily.directors).toEqual([
            { libraryId: 'm1', libraryName: 'Movies', count: 2 },
        ]);
        expect(diagnostics.fetchedTagsByFamily.studios).toEqual([
            { libraryId: 'm1', libraryName: 'Movies', count: 2 },
        ]);
        expect(diagnostics.fetchedTagsByFamily.actors).toEqual([
            { libraryId: 'm1', libraryName: 'Movies', count: 3 },
        ]);
        expect(diagnostics.tagCountDiagnosticsByFamily.genres).toEqual([
            expect.objectContaining({
                libraryId: 'm1',
                rawTagCount: 3,
                effectiveCandidateCount: 3,
                candidatesWithKnownCount: 2,
                candidatesWithUnknownCount: 1,
                candidatesBelowMinItems: 1,
                minKnownCount: 2,
                maxKnownCount: 8,
                sampleUnknownCountTitles: ['Mystery'],
            }),
        ]);
        expect(diagnostics.tagCountDiagnosticsByFamily.directors).toEqual([
            expect.objectContaining({
                libraryId: 'm1',
                rawTagCount: 2,
                effectiveCandidateCount: 2,
                candidatesWithKnownCount: 2,
                candidatesWithUnknownCount: 0,
                candidatesBelowMinItems: 1,
                minKnownCount: 4,
                maxKnownCount: 6,
                sampleBelowMinItems: [{ title: 'John Roe', count: 4 }],
            }),
        ]);
        expect(diagnostics.tagCountDiagnosticsByFamily.studios).toEqual([
            expect.objectContaining({
                libraryId: 'm1',
                rawTagCount: 2,
                effectiveCandidateCount: 2,
                candidatesWithKnownCount: 2,
                candidatesWithUnknownCount: 0,
                candidatesBelowMinItems: 1,
                minKnownCount: 3,
                maxKnownCount: 7,
            }),
        ]);
        expect(diagnostics.tagCountDiagnosticsByFamily.actors).toEqual([
            expect.objectContaining({
                libraryId: 'm1',
                rawTagCount: 3,
                effectiveCandidateCount: 3,
                candidatesWithKnownCount: 2,
                candidatesWithUnknownCount: 1,
                candidatesBelowMinItems: 1,
                minKnownCount: 1,
                maxKnownCount: 10,
                sampleUnknownCountTitles: ['Casey Star'],
            }),
        ]);

        expect(diagnostics.candidatesBeforeMinItems).toEqual(expect.objectContaining({
            total: 10,
            genres: 3,
            directors: 2,
            studios: 2,
            actors: 3,
        }));
        expect(diagnostics.candidatesAfterMinItems).toEqual(expect.objectContaining({
            total: 6,
            genres: 2,
            directors: 1,
            studios: 1,
            actors: 2,
        }));
        expect(diagnostics.strategyBucketSizes).toEqual(expect.objectContaining({
            total: 6,
            genres: 2,
            directors: 1,
            studios: 1,
            actors: 2,
        }));
        expect(diagnostics.lostToMaxChannels.total).toBe(0);
    });

    it('reports aggregated decade count availability diagnostics', () => {
        const diagnostics = buildChannelSetupPlanDiagnostics({
            config: createConfig({
                selectedLibraryIds: ['m1'],
                minItemsPerChannel: 5,
                strategyConfig: createStrategyConfig({
                    decades: { enabled: true },
                }),
            }),
            libraries: [{ id: 'm1', title: 'Movies', type: 'movie', contentCount: 25 }] as PlexLibrarySection[],
            playlists: [],
            collectionsByLibraryId: new Map(),
            genresByLibraryId: new Map(),
            directorsByLibraryId: new Map(),
            yearsByLibraryId: new Map([['m1', [
                { key: '1981', title: '1981', count: 2 },
                { key: '1988', title: '1988', count: 1 },
                { key: '1994', title: '1994', count: 8 },
                { key: '1995', title: '1995', count: null },
            ]]]),
            actorsByLibraryId: new Map(),
            studiosByLibraryId: new Map(),
            warnings: [],
            seedFor,
        });

        expect(diagnostics.tagCountDiagnosticsByFamily.decades).toEqual([
            expect.objectContaining({
                libraryId: 'm1',
                rawTagCount: 4,
                effectiveCandidateCount: 2,
                candidatesWithKnownCount: 1,
                candidatesWithUnknownCount: 1,
                candidatesBelowMinItems: 1,
                minKnownCount: 3,
                maxKnownCount: 3,
                sampleKnownCounts: [{ title: '1980s', count: 3 }],
                sampleUnknownCountTitles: ['1990s'],
                sampleBelowMinItems: [{ title: '1980s', count: 3 }],
            }),
        ]);
    });

    it('reports alternate-lineup cap losses separately from base strategy bucket sizes', () => {
        const libraries = [{ id: 'm1', title: 'Movies', type: 'movie', contentCount: 25 }] as PlexLibrarySection[];
        const baseInput = {
            config: createConfig({
                selectedLibraryIds: ['m1'],
                maxChannels: 5,
                minItemsPerChannel: 1,
                strategyConfig: createStrategyConfig({
                    genres: { enabled: true, priority: 4 },
                    studios: { enabled: true, priority: 5 },
                    actors: { enabled: true, priority: 6 },
                    directors: { enabled: true, priority: 8 },
                }),
                channelExpansion: {
                    addAlternateLineups: false,
                    alternateLineupCopies: 1,
                    variantType: 'none',
                    variantBlockSize: 3,
                },
            }),
            libraries,
            playlists: [],
            collectionsByLibraryId: new Map(),
            genresByLibraryId: new Map([['m1', [{ key: 'genre-a', title: 'Action', count: 10 }]]]),
            directorsByLibraryId: new Map([['m1', [
                { key: 'dir-a', title: 'Director One', count: 10 },
                { key: 'dir-b', title: 'Director Two', count: 10 },
            ]]]),
            yearsByLibraryId: new Map(),
            actorsByLibraryId: new Map([['m1', [
                { key: 'actor-a', title: 'Actor One', count: 10 },
                { key: 'actor-b', title: 'Actor Two', count: 10 },
                { key: 'actor-c', title: 'Actor Three', count: 10 },
                { key: 'actor-d', title: 'Actor Four', count: 10 },
            ]]]),
            studiosByLibraryId: new Map([['m1', [{ key: 'studio-a', title: 'Studio A', count: 10 }]]]),
            warnings: [],
            seedFor,
        };

        const withoutAlternate = buildChannelSetupPlanDiagnostics(baseInput);
        const withAlternate = buildChannelSetupPlanDiagnostics({
            ...baseInput,
            config: {
                ...baseInput.config,
                channelExpansion: {
                    addAlternateLineups: true,
                    alternateLineupCopies: 1,
                    variantType: 'none',
                    variantBlockSize: 3,
                },
            },
        });

        expect(withoutAlternate.strategyBucketSizes).toEqual(expect.objectContaining({
            total: 8,
            genres: 1,
            studios: 1,
            actors: 4,
            directors: 2,
        }));
        expect(withoutAlternate.afterMaxChannels).toEqual(expect.objectContaining({
            total: 5,
            genres: 1,
            studios: 1,
            actors: 2,
            directors: 1,
        }));
        expect(withoutAlternate.allocationMode).toBe('priority-balanced-round-robin');
        expect(withoutAlternate.allocationBudgetByStrategy).toEqual(withoutAlternate.afterMaxChannels);
        expect(withoutAlternate.lostToAllocationByStrategy).toEqual(withoutAlternate.lostToMaxChannels);
        expect(withoutAlternate.lostToMaxChannels).toEqual(expect.objectContaining({
            total: 3,
            actors: 2,
            directors: 1,
        }));

        expect(withAlternate.afterAlternateLineups).toEqual(expect.objectContaining({
            total: 16,
            genres: 2,
            studios: 2,
            actors: 8,
            directors: 4,
        }));
        expect(withAlternate.afterMaxChannels).toEqual(expect.objectContaining({
            total: 5,
            genres: 2,
            studios: 1,
            actors: 1,
            directors: 1,
        }));
        expect(withAlternate.allocationBudgetByStrategy).toEqual(withAlternate.afterMaxChannels);
        expect(withAlternate.lostToAllocationByStrategy).toEqual(withAlternate.lostToMaxChannels);
        expect(withAlternate.lostToMaxChannels).toEqual(expect.objectContaining({
            total: 11,
            actors: 7,
            studios: 1,
            directors: 3,
        }));
    });

    it('balances max-channel allocation across enabled strategies instead of letting one large strategy starve the rest', () => {
        const libraries = [{ id: 'm1', title: 'Movies', type: 'movie', contentCount: 100 }] as PlexLibrarySection[];
        const actors = Array.from({ length: 12 }, (_, index) => ({
            key: `actor-${index + 1}`,
            title: `Actor ${index + 1}`,
            count: 20,
        }));

        const plan = buildChannelSetupPlan({
            config: createConfig({
                selectedLibraryIds: ['m1'],
                maxChannels: 6,
                minItemsPerChannel: 1,
                strategyConfig: createStrategyConfig({
                    genres: { enabled: true, priority: 4 },
                    studios: { enabled: true, priority: 5 },
                    actors: { enabled: true, priority: 6 },
                    directors: { enabled: true, priority: 8 },
                }),
            }),
            libraries,
            playlists: [],
            collectionsByLibraryId: new Map(),
            genresByLibraryId: new Map([['m1', [
                { key: 'genre-a', title: 'Action', count: 20 },
                { key: 'genre-b', title: 'Comedy', count: 20 },
            ]]]),
            directorsByLibraryId: new Map([['m1', [{ key: 'dir-a', title: 'Director One', count: 20 }]]]),
            yearsByLibraryId: new Map(),
            actorsByLibraryId: new Map([['m1', actors]]),
            studiosByLibraryId: new Map([['m1', [
                { key: 'studio-a', title: 'Studio A', count: 20 },
                { key: 'studio-b', title: 'Studio B', count: 20 },
            ]]]),
            warnings: [],
            seedFor,
        });

        expect(plan.reachedMaxChannels).toBe(true);
        expect(plan.estimates).toEqual(expect.objectContaining({
            total: 6,
            genres: 2,
            studios: 2,
            actors: 1,
            directors: 1,
        }));
        expect(plan.pendingChannels.map((channel) => channel.buildStrategy)).toEqual([
            'genres',
            'studios',
            'actors',
            'directors',
            'genres',
            'studios',
        ]);
    });
});
