import { buildChannelSetupPlan, createChannelIdentityKey, diffChannelPlans } from '../ChannelSetupPlanner';
import type { ChannelSetupConfig, SetupStrategyConfig, SetupStrategyKey } from '../types';
import type { PlexPlaylist } from '../../../modules/plex/library';
import type { ChannelConfig } from '../../../modules/scheduler/channel-manager';
import type { PendingChannel } from '../ChannelSetupPlanner';
import { DEFAULT_STRATEGY_PRIORITIES, MIXED_SCOPE_STRATEGY_KEYS, SETUP_STRATEGY_KEYS } from '../constants';

const seedFor = (value: string): number => {
    let hash = 0;
    for (let i = 0; i < value.length; i++) {
        hash = ((hash << 5) - hash) + value.charCodeAt(i);
        hash |= 0;
    }
    return Math.abs(hash);
};

const createStrategyConfig = (
    overrides?: Partial<Record<SetupStrategyKey, Partial<SetupStrategyConfig>>>
): Record<SetupStrategyKey, SetupStrategyConfig> => (
    SETUP_STRATEGY_KEYS.reduce<Record<SetupStrategyKey, SetupStrategyConfig>>((acc, key) => {
        const candidate = overrides?.[key];
        acc[key] = {
            enabled: candidate?.enabled ?? false,
            priority: candidate?.priority ?? DEFAULT_STRATEGY_PRIORITIES[key],
            scope: MIXED_SCOPE_STRATEGY_KEYS.has(key) && candidate?.scope === 'cross-library' ? 'cross-library' : 'per-library',
        };
        return acc;
    }, {} as Record<SetupStrategyKey, SetupStrategyConfig>)
);

const createConfig = (overrides?: Partial<ChannelSetupConfig>): ChannelSetupConfig => ({
    serverId: 'server-1',
    selectedLibraryIds: [],
    maxChannels: 50,
    buildMode: 'replace',
    strategyConfig: createStrategyConfig(),
    actorStudioCombineMode: 'separate',
    minItemsPerChannel: 1,
    ...overrides,
});

const makeExistingChannel = (planned: PendingChannel, index: number): ChannelConfig => {
    const existing: ChannelConfig = {
        id: `ch-${index + 1}`,
        number: index + 1,
        name: `Existing ${index + 1}`,
        contentSource: planned.contentSource,
        playbackMode: planned.playbackMode,
        shuffleSeed: planned.shuffleSeed,
        phaseSeed: 1,
        startTimeAnchor: 0,
        skipIntros: false,
        skipCredits: false,
        createdAt: 0,
        updatedAt: 0,
        lastContentRefresh: 0,
        itemCount: 0,
        totalDurationMs: 0,
    };
    if (planned.isAutoGenerated !== undefined) {
        existing.isAutoGenerated = planned.isAutoGenerated;
    }
    if (planned.buildStrategy !== undefined) {
        existing.buildStrategy = planned.buildStrategy;
    }
    if (planned.sourceLibraryId !== undefined) {
        existing.sourceLibraryId = planned.sourceLibraryId;
    }
    if (planned.sourceLibraryName !== undefined) {
        existing.sourceLibraryName = planned.sourceLibraryName;
    }
    if (planned.lineupReplicaIndex !== undefined) {
        existing.lineupReplicaIndex = planned.lineupReplicaIndex;
    }
    if (planned.isSequentialVariant !== undefined) {
        existing.isSequentialVariant = planned.isSequentialVariant;
    }
    return existing;
};

describe('ChannelSetupPlanner', () => {
    it('defaults alternateLineupCopies to 1 when addAlternateLineups is true but copies is non-finite', () => {
        const playlists: PlexPlaylist[] = [
            {
                ratingKey: 'pl1',
                key: '/playlists/pl1',
                title: 'Favorites',
                thumb: null,
                duration: 0,
                leafCount: 10,
            },
        ];

        const plan = buildChannelSetupPlan({
            config: createConfig({
                strategyConfig: createStrategyConfig({ playlists: { enabled: true } }),
                channelExpansion: {
                    addAlternateLineups: true,
                    alternateLineupCopies: Number.NaN,
                    addSequentialVariants: false,
                },
            }),
            libraries: [],
            playlists,
            collectionsByLibraryId: new Map(),
            tagItemsByLibraryId: new Map(),
            scanItemsByLibraryId: new Map(),
            actorsByLibraryId: new Map(),
            studiosByLibraryId: new Map(),
            warnings: [],
            seedFor,
        });

        expect(plan.pendingChannels.map((c) => c.name)).toEqual(['Favorites', 'Favorites (2)']);
        expect(plan.pendingChannels.map((c) => c.lineupReplicaIndex)).toEqual([0, 1]);
    });

    it('diffChannelPlans matches base/copy/sequential variants without identity collisions', () => {
        const playlists: PlexPlaylist[] = [
            {
                ratingKey: 'pl1',
                key: '/playlists/pl1',
                title: 'Favorites',
                thumb: null,
                duration: 0,
                leafCount: 10,
            },
        ];

        const plan = buildChannelSetupPlan({
            config: createConfig({
                strategyConfig: createStrategyConfig({ playlists: { enabled: true } }),
                channelExpansion: {
                    addAlternateLineups: true,
                    alternateLineupCopies: 2,
                    addSequentialVariants: true,
                },
            }),
            libraries: [],
            playlists,
            collectionsByLibraryId: new Map(),
            tagItemsByLibraryId: new Map(),
            scanItemsByLibraryId: new Map(),
            actorsByLibraryId: new Map(),
            studiosByLibraryId: new Map(),
            warnings: [],
            seedFor,
        });

        const identityKeys = plan.pendingChannels.map((channel) => createChannelIdentityKey(channel));
        expect(new Set(identityKeys).size).toBe(plan.pendingChannels.length);

        const existing: ChannelConfig[] = plan.pendingChannels.map(makeExistingChannel);

        const diff = diffChannelPlans(existing, plan.pendingChannels);
        expect(diff.summary).toEqual({ created: 0, removed: 0, unchanged: plan.pendingChannels.length });
        expect(diff.matchedPairs).toHaveLength(plan.pendingChannels.length);
    });
});
