import { buildChannelSetupPlan, createChannelIdentityKey, diffChannelPlans } from '../ChannelSetupPlanner';
import type { ChannelSetupConfig } from '../types';
import type { PlexPlaylist } from '../../../modules/plex/library';
import type { ChannelConfig } from '../../../modules/scheduler/channel-manager';

const seedFor = (value: string): number => {
    let hash = 0;
    for (let i = 0; i < value.length; i++) {
        hash = ((hash << 5) - hash) + value.charCodeAt(i);
        hash |= 0;
    }
    return Math.abs(hash);
};

const createConfig = (overrides?: Partial<ChannelSetupConfig>): ChannelSetupConfig => ({
    serverId: 'server-1',
    selectedLibraryIds: [],
    maxChannels: 50,
    buildMode: 'replace',
    enabledStrategies: {
        collections: false,
        libraryFallback: false,
        playlists: false,
        genres: false,
        directors: false,
        decades: false,
        recentlyAdded: false,
        studios: false,
        actors: false,
    },
    actorStudioCombineMode: 'separate',
    minItemsPerChannel: 1,
    ...overrides,
});

describe('ChannelSetupPlanner', () => {
    it('defaults alternateLineupCopies to 1 when addAlternateLineups is true but copies is non-finite', () => {
        const playlists: PlexPlaylist[] = [
            {
                ratingKey: 'pl1',
                key: '/playlists/pl1',
                title: 'Favorites',
                thumb: null,
                duration: 0,
                leafCount: 10,
            },
        ];

        const plan = buildChannelSetupPlan({
            config: createConfig({
                enabledStrategies: { ...createConfig().enabledStrategies, playlists: true },
                channelExpansion: {
                    addAlternateLineups: true,
                    alternateLineupCopies: Number.NaN,
                    addSequentialVariants: false,
                },
            }),
            libraries: [],
            playlists,
            collectionsByLibraryId: new Map(),
            tagItemsByLibraryId: new Map(),
            scanItemsByLibraryId: new Map(),
            libraryItemCountById: new Map(),
            actorsByLibraryId: new Map(),
            studiosByLibraryId: new Map(),
            warnings: [],
            seedFor,
        });

        expect(plan.pendingChannels.map((c) => c.name)).toEqual(['Favorites', 'Favorites (2)']);
        expect(plan.pendingChannels.map((c) => c.lineupReplicaIndex)).toEqual([0, 1]);
    });

    it('diffChannelPlans matches base/copy/sequential variants without identity collisions', () => {
        const playlists: PlexPlaylist[] = [
            {
                ratingKey: 'pl1',
                key: '/playlists/pl1',
                title: 'Favorites',
                thumb: null,
                duration: 0,
                leafCount: 10,
            },
        ];

        const plan = buildChannelSetupPlan({
            config: createConfig({
                enabledStrategies: { ...createConfig().enabledStrategies, playlists: true },
                channelExpansion: {
                    addAlternateLineups: true,
                    alternateLineupCopies: 2,
                    addSequentialVariants: true,
                },
            }),
            libraries: [],
            playlists,
            collectionsByLibraryId: new Map(),
            tagItemsByLibraryId: new Map(),
            scanItemsByLibraryId: new Map(),
            libraryItemCountById: new Map(),
            actorsByLibraryId: new Map(),
            studiosByLibraryId: new Map(),
            warnings: [],
            seedFor,
        });

        const identityKeys = plan.pendingChannels.map((channel) => createChannelIdentityKey({
            ...channel,
            playbackMode: channel.playbackMode,
        }));
        expect(new Set(identityKeys).size).toBe(plan.pendingChannels.length);

        const existing: ChannelConfig[] = plan.pendingChannels.map((planned, index) => ({
            id: `ch-${index + 1}`,
            number: index + 1,
            name: `Existing ${index + 1}`,
            contentSource: planned.contentSource,
            playbackMode: planned.playbackMode,
            shuffleSeed: planned.shuffleSeed,
            phaseSeed: 1,
            startTimeAnchor: 0,
            isManual: false,
            isFavorite: false,
            enabled: true,
            isAutoGenerated: true,
            lineupReplicaIndex: planned.lineupReplicaIndex,
            isSequentialVariant: planned.isSequentialVariant,
        })) as unknown as ChannelConfig[];

        const diff = diffChannelPlans(existing, plan.pendingChannels);
        expect(diff.summary).toEqual({ created: 0, removed: 0, unchanged: plan.pendingChannels.length });
        expect(diff.matchedPairs).toHaveLength(plan.pendingChannels.length);
    });
});
