import { formatErrorDetailForMessage } from '../../../../utils/errors';
import { isValidContentSource } from '../authoring/ChannelContentSourceValidator';
import { isValidChannelSeed } from '../authoring/ChannelSeedPolicy';
import {
    isValidBuildStrategy,
    isValidContentFilterArray,
    isValidPlaybackMode,
    isValidSortOrder,
} from '../authoring/ChannelValueValidators';
import { CHANNEL_ERROR_MESSAGES } from '../constants';
import type { ChannelCreateInput } from '../contracts/types';

const STRING_OPTIONAL_FIELDS = [
    'name',
    'description',
    'icon',
    'sourceLibraryId',
    'sourceLibraryName',
] as const satisfies readonly (keyof ChannelCreateInput)[];

const BOOLEAN_OPTIONAL_FIELDS = [
    'isAutoGenerated',
    'isPlaybackModeVariant',
    'skipIntros',
    'skipCredits',
] as const satisfies readonly (keyof ChannelCreateInput)[];

const FINITE_NUMBER_OPTIONAL_FIELDS = [
    'lineupReplicaIndex',
    'startTimeAnchor',
    'maxEpisodeRunTimeMs',
    'minEpisodeRunTimeMs',
] as const satisfies readonly (keyof ChannelCreateInput)[];

export type ChannelImportNormalizationResult =
    | { ok: true; channels: ChannelCreateInput[]; skippedCount: number }
    | { ok: false; error: string };

export class ChannelImportNormalizer {
    normalizePayload(data: string): ChannelImportNormalizationResult {
        let parsed: unknown;
        try {
            parsed = JSON.parse(data);
        } catch {
            return { ok: false, error: CHANNEL_ERROR_MESSAGES.INVALID_IMPORT_DATA };
        }

        if (!Array.isArray(parsed)) {
            return { ok: false, error: CHANNEL_ERROR_MESSAGES.INVALID_IMPORT_DATA };
        }

        const channels: ChannelCreateInput[] = [];
        let skippedCount = 0;
        for (const item of parsed) {
            const channel = this.buildCreateInput(item);
            if (channel) {
                channels.push(channel);
            } else {
                skippedCount++;
            }
        }
        return { ok: true, channels, skippedCount };
    }

    buildCreateInput(item: unknown): ChannelCreateInput | null {
        if (!item || typeof item !== 'object') {
            return null;
        }

        const record = item as Record<string, unknown>;
        const contentSource = record['contentSource'];
        if (!isValidContentSource(contentSource)) {
            return null;
        }

        const channel: ChannelCreateInput = {
            contentSource,
        };

        applyIntegerOptional(channel, record, 'number');
        applyStringOptionals(channel, record);
        applyBooleanOptionals(channel, record);
        applyFiniteNumberOptionals(channel, record);
        applyBuildStrategyOptional(channel, record);
        const playbackMode = isValidPlaybackMode(record['playbackMode'])
            ? record['playbackMode']
            : undefined;
        if (playbackMode !== undefined) {
            channel.playbackMode = playbackMode;
        }
        applyChannelSeedOptional(channel, record, 'shuffleSeed');
        applyImportBlockSizeOptional(channel, record, playbackMode);
        applyChannelSeedOptional(channel, record, 'phaseSeed');
        applyContentFiltersOptional(channel, record);
        applySortOrderOptional(channel, record);

        return channel;
    }

    formatErrorMessage(error: unknown): string {
        return formatErrorDetailForMessage(error);
    }
}

function applyIntegerOptional(
    channel: ChannelCreateInput,
    record: Record<string, unknown>,
    field: 'number'
): void {
    const value = record[field];
    if (typeof value === 'number' && Number.isInteger(value)) {
        channel[field] = value;
    }
}

function applyStringOptionals(
    channel: ChannelCreateInput,
    record: Record<string, unknown>
): void {
    for (const field of STRING_OPTIONAL_FIELDS) {
        const value = record[field];
        if (typeof value === 'string') {
            channel[field] = value;
        }
    }
}

function applyBooleanOptionals(
    channel: ChannelCreateInput,
    record: Record<string, unknown>
): void {
    for (const field of BOOLEAN_OPTIONAL_FIELDS) {
        const value = record[field];
        if (typeof value === 'boolean') {
            channel[field] = value;
        }
    }
}

function applyFiniteNumberOptionals(
    channel: ChannelCreateInput,
    record: Record<string, unknown>
): void {
    for (const field of FINITE_NUMBER_OPTIONAL_FIELDS) {
        const value = record[field];
        if (typeof value === 'number' && Number.isFinite(value)) {
            channel[field] = value;
        }
    }
}

function applyBuildStrategyOptional(
    channel: ChannelCreateInput,
    record: Record<string, unknown>
): void {
    const value = record['buildStrategy'];
    if (isValidBuildStrategy(value)) {
        channel.buildStrategy = value;
    }
}

function applyChannelSeedOptional(
    channel: ChannelCreateInput,
    record: Record<string, unknown>,
    field: 'shuffleSeed' | 'phaseSeed'
): void {
    const value = record[field];
    if (isValidChannelSeed(value)) {
        channel[field] = value;
    }
}

function applyImportBlockSizeOptional(
    channel: ChannelCreateInput,
    record: Record<string, unknown>,
    playbackMode: ChannelCreateInput['playbackMode'] | undefined
): void {
    const value = record['blockSize'];
    if (playbackMode === 'block' && typeof value === 'number' && Number.isFinite(value)) {
        channel.blockSize = value;
    }
}

function applyContentFiltersOptional(
    channel: ChannelCreateInput,
    record: Record<string, unknown>
): void {
    const value = record['contentFilters'];
    if (isValidContentFilterArray(value)) {
        channel.contentFilters = value;
    }
}

function applySortOrderOptional(
    channel: ChannelCreateInput,
    record: Record<string, unknown>
): void {
    const value = record['sortOrder'];
    if (isValidSortOrder(value)) {
        channel.sortOrder = value;
    }
}
