import type {
    ChannelBuildProgress,
    ChannelSetupEstimates,
    ChannelSetupPreviewFailureReason,
} from '../types';
import type {
    PlexCollection,
    PlexPlaylist,
    PlexTagDirectoryItem,
    getPlexRequestIntentForChannelSetup,
} from '../../../modules/plex/library';
import type {
    ChannelConfig,
    ChannelCreateInput,
    ContentFilter,
    SortOrder,
} from '../../../modules/scheduler/channel-manager';

export type PendingChannel =
    ChannelCreateInput
    & {
        name: string;
        playbackMode: ChannelConfig['playbackMode'];
        shuffleSeed: number;
    };

export const createEmptyChannelSetupEstimates = (): ChannelSetupEstimates => ({
    total: 0,
    collections: 0,
    playlists: 0,
    genres: 0,
    directors: 0,
    decades: 0,
    recentlyAdded: 0,
    studios: 0,
    actors: 0,
});

export const toChannelSetupDecadeValue = (title: string): number | null => {
    const year = Number.parseInt(title, 10);
    if (!Number.isFinite(year)) {
        return null;
    }
    return Math.floor(year / 10) * 10;
};

export type ChannelSetupPlannerFacetFamily = 'genres' | 'directors' | 'decades' | 'studios' | 'actors';

export interface ChannelSetupPlannerLibraryCount {
    libraryId: string;
    libraryName: string;
    count: number;
}

export interface ChannelSetupPlannerCountSample {
    title: string;
    count: number;
}

export interface ChannelSetupPlannerFacetCountDiagnostics {
    libraryId: string;
    libraryName: string;
    rawTagCount: number;
    effectiveCandidateCount: number;
    candidatesWithKnownCount: number;
    candidatesWithUnknownCount: number;
    candidatesBelowMinItems: number;
    minKnownCount: number | null;
    maxKnownCount: number | null;
    sampleKnownCounts: ChannelSetupPlannerCountSample[];
    sampleUnknownCountTitles: string[];
    sampleBelowMinItems: ChannelSetupPlannerCountSample[];
}

export interface ChannelSetupPlannerDiagnostics {
    effectiveMaxChannels: number;
    minItems: number;
    fetchedTagsByFamily: Record<ChannelSetupPlannerFacetFamily, ChannelSetupPlannerLibraryCount[]>;
    tagCountDiagnosticsByFamily: Record<ChannelSetupPlannerFacetFamily, ChannelSetupPlannerFacetCountDiagnostics[]>;
    candidatesBeforeMinItems: ChannelSetupEstimates;
    candidatesAfterMinItems: ChannelSetupEstimates;
    strategyBucketSizes: ChannelSetupEstimates;
    afterAlternateLineups: ChannelSetupEstimates;
    afterVariants: ChannelSetupEstimates;
    afterMaxChannels: ChannelSetupEstimates;
    lostToMaxChannels: ChannelSetupEstimates;
}

interface ChannelIdentityCandidate {
    contentSource: ChannelConfig['contentSource'];
    contentFilters?: ContentFilter[];
    sortOrder?: SortOrder;
    playbackMode: ChannelConfig['playbackMode'];
    blockSize?: number;
    lineupReplicaIndex?: number;
    isPlaybackModeVariant?: boolean;
}

interface ChannelDiffEntry {
    name: string;
    identityKey: string;
    channelId?: string;
    number?: number;
    isAutoGenerated?: boolean;
}

export interface ChannelDiffResult {
    created: ChannelDiffEntry[];
    removed: ChannelDiffEntry[];
    unchanged: ChannelDiffEntry[];
    matchedPairs: Array<{ existing: ChannelConfig; planned: PendingChannel }>;
    summary: { created: number; removed: number; unchanged: number };
    samples: { created: string[]; removed: string[]; unchanged: string[] };
}

export function createChannelIdentityKey(candidate: ChannelIdentityCandidate): string {
    const normalized = {
        source: normalizeSource(candidate.contentSource),
        filters: normalizeFilters(candidate.contentFilters),
        sortOrder: candidate.sortOrder ?? null,
        lineupReplicaIndex: candidate.lineupReplicaIndex ?? 0,
        isPlaybackModeVariant: candidate.isPlaybackModeVariant === true,
        variantPlaybackMode: candidate.isPlaybackModeVariant === true ? candidate.playbackMode : null,
        variantBlockSize: candidate.isPlaybackModeVariant === true && candidate.playbackMode === 'block'
            ? candidate.blockSize ?? null
            : null,
    };
    return stableStringify(normalized);
}

export function diffChannelPlans(
    existingChannels: ChannelConfig[],
    plannedChannels: PendingChannel[]
): ChannelDiffResult {
    const plannedByKey = new Map<string, PendingChannel[]>();
    for (const planned of plannedChannels) {
        const key = createChannelIdentityKey(planned);
        const list = plannedByKey.get(key) ?? [];
        list.push(planned);
        plannedByKey.set(key, list);
    }

    const created: ChannelDiffEntry[] = [];
    const removed: ChannelDiffEntry[] = [];
    const unchanged: ChannelDiffEntry[] = [];
    const matchedPairs: Array<{ existing: ChannelConfig; planned: PendingChannel }> = [];

    const consumePlanned = (key: string): PendingChannel | null => {
        const list = plannedByKey.get(key);
        if (!list || list.length === 0) return null;
        const planned = list.shift() ?? null;
        if (list.length === 0) {
            plannedByKey.delete(key);
        }
        return planned;
    };

    for (const existing of existingChannels) {
        const key = createChannelIdentityKey(existing);
        const planned = consumePlanned(key);
        if (planned) {
            matchedPairs.push({ existing, planned });
            unchanged.push(createChannelDiffEntry(existing, key));
        } else {
            removed.push(createChannelDiffEntry(existing, key));
        }
    }

    for (const [key, remaining] of plannedByKey.entries()) {
        for (const planned of remaining) {
            created.push(createChannelDiffEntry(planned, key));
        }
    }

    const summary = {
        created: created.length,
        removed: removed.length,
        unchanged: unchanged.length,
    };
    const samples = {
        created: created.slice(0, 6).map((c) => c.name),
        removed: removed.slice(0, 6).map((c) => c.name),
        unchanged: unchanged.slice(0, 6).map((c) => c.name),
    };

    return { created, removed, unchanged, matchedPairs, summary, samples };
}

function createChannelDiffEntry(
    channel: Pick<ChannelConfig, 'name' | 'id' | 'number' | 'isAutoGenerated'> | PendingChannel,
    identityKey: string
): ChannelDiffEntry {
    const entry: ChannelDiffEntry = {
        name: channel.name,
        identityKey,
    };
    if ('id' in channel && channel.id !== undefined) {
        entry.channelId = channel.id;
    }
    if ('number' in channel && channel.number !== undefined) {
        entry.number = channel.number;
    }
    if (channel.isAutoGenerated !== undefined) {
        entry.isAutoGenerated = channel.isAutoGenerated;
    }
    return entry;
}

export type ChannelSetupPlanningIntent = 'preview' | 'build';
export type ChannelSetupPlexRequestIntent = ReturnType<typeof getPlexRequestIntentForChannelSetup>;

export type ChannelSetupFacetSnapshotData = {
    playlists: PlexPlaylist[];
    collectionsByLibraryId: Map<string, PlexCollection[]>;
    genresByLibraryId: Map<string, PlexTagDirectoryItem[]>;
    directorsByLibraryId: Map<string, PlexTagDirectoryItem[]>;
    yearsByLibraryId: Map<string, PlexTagDirectoryItem[]>;
    actorsByLibraryId: Map<string, PlexTagDirectoryItem[]>;
    studiosByLibraryId: Map<string, PlexTagDirectoryItem[]>;
    warnings: string[];
    hasTransientLoadFailure: boolean;
    errorsTotal: number;
    playlistMs: number;
    collectionsMs: number;
    libraryQueryMs: number;
    lastTask?: ChannelBuildProgress['task'];
};

export type ChannelSetupFacetSnapshot =
    | ({ status: 'ready' } & ChannelSetupFacetSnapshotData)
    | ({
        status: 'blocked' | 'slow';
        message: string;
        failureReason: ChannelSetupPreviewFailureReason;
    } & ChannelSetupFacetSnapshotData);

function normalizeFilters(filters?: ContentFilter[]): Array<ContentFilter> | null {
    if (!filters || filters.length === 0) return null;
    return [...filters].sort((a, b) => {
        const aKey = `${a.field}:${a.operator}:${typeof a.value}:${stableStringify(a.value)}`;
        const bKey = `${b.field}:${b.operator}:${typeof b.value}:${stableStringify(b.value)}`;
        return aKey.localeCompare(bKey);
    });
}

function normalizeSource(source: ChannelConfig['contentSource']): unknown {
    switch (source.type) {
        case 'library':
            return {
                type: source.type,
                libraryId: source.libraryId,
                libraryType: source.libraryType,
                includeWatched: source.includeWatched,
                libraryFilter: normalizeRecord(source.libraryFilter),
            };
        case 'collection':
            return { type: source.type, collectionKey: source.collectionKey };
        case 'playlist':
            return { type: source.type, playlistKey: source.playlistKey };
        case 'show':
            return {
                type: source.type,
                showKey: source.showKey,
                seasonFilter: source.seasonFilter ? [...source.seasonFilter].sort((a, b) => a - b) : null,
            };
        case 'manual':
            return {
                type: source.type,
                items: [...source.items].sort((a, b) => a.ratingKey.localeCompare(b.ratingKey)),
            };
        case 'mixed': {
            const normalizedSources = source.sources.map(normalizeSource);
            const sortedSources = [...normalizedSources].sort((a, b) => stableStringify(a).localeCompare(stableStringify(b)));
            return { type: source.type, mixMode: source.mixMode, sources: sortedSources };
        }
        default:
            return source;
    }
}

function normalizeRecord(record?: Record<string, string | number>): Record<string, string | number> | null {
    if (!record) return null;
    const entries = Object.entries(record).sort(([a], [b]) => a.localeCompare(b));
    const normalized: Record<string, string | number> = {};
    for (const [key, value] of entries) {
        normalized[key] = value;
    }
    return normalized;
}

function stableStringify(value: unknown): string {
    if (value === null || typeof value !== 'object') {
        return JSON.stringify(value);
    }
    if (Array.isArray(value)) {
        return `[${value.map(stableStringify).join(',')}]`;
    }
    const obj = value as Record<string, unknown>;
    const keys = Object.keys(obj).sort((left, right) => left.localeCompare(right));
    const entries = keys.map((key) => `${JSON.stringify(key)}:${stableStringify(obj[key])}`);
    return `{${entries.join(',')}}`;
}
