/**
 * @fileoverview Pure-logic planner that builds pending channel list from config.
 * @module core/channel-setup/planning/ChannelSetupPlanner
 * @version 1.0.0
 */

import type {
    ChannelSetupConfig,
    ChannelSetupEstimates,
    SetupStrategyKey,
} from '../types';
import { DEFAULT_MIN_ITEMS_PER_CHANNEL, DEFAULT_STRATEGY_PRIORITIES } from '../constants';
import { DEFAULT_CHANNEL_SETUP_MAX } from '../../../modules/scheduler/channel-manager/constants';
import type {
    PlexLibrarySection,
    PlexCollection,
    PlexPlaylist,
    PlexTagDirectoryItem,
} from '../../../modules/plex/library';
import type {
    ChannelConfig,
    ContentFilter,
    SortOrder,
} from '../../../modules/scheduler/channel-manager';
import { buildChannelSetupStrategyBuckets } from './ChannelSetupStrategyBuilders';
import {
    createEmptyChannelSetupEstimates,
    toChannelSetupDecadeValue,
    type PendingChannel,
} from './ChannelSetupPlanningTypes';

export type { PendingChannel } from './ChannelSetupPlanningTypes';

interface ChannelSetupPlanInput {
    config: ChannelSetupConfig;
    libraries: PlexLibrarySection[];
    playlists: PlexPlaylist[];
    collectionsByLibraryId: Map<string, PlexCollection[]>;
    genresByLibraryId: Map<string, PlexTagDirectoryItem[]>;
    directorsByLibraryId: Map<string, PlexTagDirectoryItem[]>;
    yearsByLibraryId: Map<string, PlexTagDirectoryItem[]>;
    actorsByLibraryId: Map<string, PlexTagDirectoryItem[]>;
    studiosByLibraryId: Map<string, PlexTagDirectoryItem[]>;
    warnings: string[];
    seedFor: (value: string) => number;
}

interface ChannelSetupPlan {
    pendingChannels: PendingChannel[];
    estimates: ChannelSetupEstimates;
    warnings: string[];
    skipped: number;
    reachedMaxChannels: boolean;
}

type ChannelSetupPlannerFacetFamily = 'genres' | 'directors' | 'decades' | 'studios' | 'actors';

export interface ChannelSetupPlannerLibraryCount {
    libraryId: string;
    libraryName: string;
    count: number;
}

export interface ChannelSetupPlannerCountSample {
    title: string;
    count: number;
}

export interface ChannelSetupPlannerFacetCountDiagnostics {
    libraryId: string;
    libraryName: string;
    rawTagCount: number;
    effectiveCandidateCount: number;
    candidatesWithKnownCount: number;
    candidatesWithUnknownCount: number;
    candidatesBelowMinItems: number;
    minKnownCount: number | null;
    maxKnownCount: number | null;
    sampleKnownCounts: ChannelSetupPlannerCountSample[];
    sampleUnknownCountTitles: string[];
    sampleBelowMinItems: ChannelSetupPlannerCountSample[];
}

export interface ChannelSetupPlannerDiagnostics {
    effectiveMaxChannels: number;
    minItems: number;
    fetchedTagsByFamily: Record<ChannelSetupPlannerFacetFamily, ChannelSetupPlannerLibraryCount[]>;
    tagCountDiagnosticsByFamily: Record<ChannelSetupPlannerFacetFamily, ChannelSetupPlannerFacetCountDiagnostics[]>;
    candidatesBeforeMinItems: ChannelSetupEstimates;
    candidatesAfterMinItems: ChannelSetupEstimates;
    strategyBucketSizes: ChannelSetupEstimates;
    afterAlternateLineups: ChannelSetupEstimates;
    afterVariants: ChannelSetupEstimates;
    afterMaxChannels: ChannelSetupEstimates;
    lostToMaxChannels: ChannelSetupEstimates;
}

interface ChannelIdentityCandidate {
    contentSource: ChannelConfig['contentSource'];
    contentFilters?: ContentFilter[];
    sortOrder?: SortOrder;
    playbackMode: ChannelConfig['playbackMode'];
    blockSize?: number;
    lineupReplicaIndex?: number;
    isPlaybackModeVariant?: boolean;
}

interface ChannelDiffEntry {
    name: string;
    identityKey: string;
    channelId?: string;
    number?: number;
    isAutoGenerated?: boolean;
}

export interface ChannelDiffResult {
    created: ChannelDiffEntry[];
    removed: ChannelDiffEntry[];
    unchanged: ChannelDiffEntry[];
    matchedPairs: Array<{ existing: ChannelConfig; planned: PendingChannel }>;
    summary: { created: number; removed: number; unchanged: number };
    samples: { created: string[]; removed: string[]; unchanged: string[] };
}

const sortTagValuesByCountThenTitle = <T extends { title: string; count: number }>(values: T[]): T[] => (
    [...values].sort((a, b) => {
        const countDiff = b.count - a.count;
        if (countDiff !== 0) return countDiff;
        return a.title.localeCompare(b.title);
    })
);

const sortTagTitles = (titles: string[]): string[] => [...titles].sort((a, b) => a.localeCompare(b));

const toCountSamples = (values: Array<{ title: string; count: number }>, limit: number = 5): ChannelSetupPlannerCountSample[] =>
    sortTagValuesByCountThenTitle(values).slice(0, limit).map((value) => ({
        title: value.title,
        count: value.count,
    }));

const formatDecadeLabel = (decade: number): string => `${decade}s`;

const sortLibrariesByTitle = (libraries: PlexLibrarySection[]): PlexLibrarySection[] => (
    [...libraries].sort((a, b) => {
        const titleDiff = a.title.localeCompare(b.title);
        if (titleDiff !== 0) return titleDiff;
        return a.id.localeCompare(b.id);
    })
);

const sanitizeBlockSize = (raw: unknown, fallback: number): number => {
    const numeric = typeof raw === 'number' ? raw : Number(raw);
    if (!Number.isFinite(numeric)) return fallback;
    const value = Math.floor(numeric);
    if (value < 1) return fallback;
    return value;
};

const isTvOnlySource = (source: ChannelConfig['contentSource']): boolean => {
    switch (source.type) {
        case 'library':
            return source.libraryType === 'show';
        case 'show':
            return true;
        case 'mixed':
            return source.sources.every(isTvOnlySource);
        default:
            return false;
    }
};

const isSeriesDerivedChannel = (
    channel: PendingChannel,
    showLibraryIds: Set<string>
): boolean => {
    if (typeof channel.sourceLibraryId === 'string' && showLibraryIds.has(channel.sourceLibraryId)) {
        return true;
    }
    return isTvOnlySource(channel.contentSource);
};

export function buildChannelSetupPlan(input: ChannelSetupPlanInput): ChannelSetupPlan {
    return buildChannelSetupPlanInternal(input).plan;
}

export function buildChannelSetupPlanDiagnostics(input: ChannelSetupPlanInput): ChannelSetupPlannerDiagnostics {
    return buildChannelSetupPlanInternal(input, true).diagnostics as ChannelSetupPlannerDiagnostics;
}

function buildChannelSetupPlanInternal(
    input: ChannelSetupPlanInput,
    collectDiagnostics: boolean = false
): { plan: ChannelSetupPlan; diagnostics?: ChannelSetupPlannerDiagnostics } {
    const {
        config,
        libraries,
        playlists,
        collectionsByLibraryId,
        genresByLibraryId,
        directorsByLibraryId,
        yearsByLibraryId,
        actorsByLibraryId,
        studiosByLibraryId,
        warnings,
        seedFor,
    } = input;

    const requestedMax = Number.isFinite(config.maxChannels) ? config.maxChannels : DEFAULT_CHANNEL_SETUP_MAX;
    const effectiveMaxChannels = Math.max(1, Math.floor(requestedMax));
    const requestedMinItems = Number.isFinite(config.minItemsPerChannel) ? config.minItemsPerChannel : DEFAULT_MIN_ITEMS_PER_CHANNEL;
    const minItems = Math.max(1, Math.floor(requestedMinItems));

    const selectedLibraries = sortLibrariesByTitle(
        libraries.filter((lib) => config.selectedLibraryIds.includes(lib.id))
    );

    const diagnostics = collectDiagnostics
        ? createPlannerDiagnostics(
            selectedLibraries,
            genresByLibraryId,
            directorsByLibraryId,
            yearsByLibraryId,
            actorsByLibraryId,
            studiosByLibraryId,
            effectiveMaxChannels,
            minItems
        )
        : undefined;

    const getStrategyPriority = (strategy: SetupStrategyKey): number => {
        const configured = config.strategyConfig[strategy]?.priority;
        if (Number.isFinite(configured)) {
            return Math.max(1, Math.floor(Number(configured)));
        }
        return DEFAULT_STRATEGY_PRIORITIES[strategy];
    };

    const strategyBuild = buildChannelSetupStrategyBuckets({
        config,
        selectedLibraries,
        playlists,
        collectionsByLibraryId,
        genresByLibraryId,
        directorsByLibraryId,
        yearsByLibraryId,
        actorsByLibraryId,
        studiosByLibraryId,
        minItems,
        seedFor,
    });
    const { strategyBuckets, skipped } = strategyBuild;

    if (diagnostics) {
        diagnostics.candidatesBeforeMinItems = strategyBuild.candidatesBeforeMinItems;
        diagnostics.candidatesAfterMinItems = strategyBuild.candidatesAfterMinItems;
    }

    const orderedStrategies = (Object.keys(strategyBuckets) as SetupStrategyKey[]).sort((a, b) => {
        const priorityDiff = getStrategyPriority(a) - getStrategyPriority(b);
        if (priorityDiff !== 0) return priorityDiff;
        return a.localeCompare(b);
    });

    const showLibraryIds = new Set(
        selectedLibraries
            .filter((library) => library.type === 'show')
            .map((library) => library.id)
    );

    const baseOrderedUnadjusted: PendingChannel[] = [];
    for (const strategy of orderedStrategies) {
        baseOrderedUnadjusted.push(...strategyBuckets[strategy]);
    }

    if (diagnostics) {
        diagnostics.strategyBucketSizes = countChannelsByStrategy(baseOrderedUnadjusted);
    }

    const baseSeriesModeRaw = config.seriesOrdering?.basePlaybackMode;
    const baseSeriesMode =
        baseSeriesModeRaw === 'sequential' || baseSeriesModeRaw === 'block'
            ? baseSeriesModeRaw
            : 'shuffle';
    const baseSeriesBlockSize = sanitizeBlockSize(config.seriesOrdering?.baseBlockSize, 3);
    const baseOrdered: PendingChannel[] = baseOrderedUnadjusted.map((channel) => {
        const isSeriesDerived = isSeriesDerivedChannel(channel, showLibraryIds);
        if (baseSeriesMode === 'shuffle' || !isSeriesDerived || channel.playbackMode !== 'shuffle') {
            return channel;
        }
        const updated: PendingChannel = {
            ...channel,
            playbackMode: baseSeriesMode,
        };
        if (baseSeriesMode === 'block') {
            updated.blockSize = baseSeriesBlockSize;
        } else {
            delete updated.blockSize;
        }
        return updated;
    });

    let alternateCopies = 0;
    if (config.channelExpansion?.addAlternateLineups) {
        const raw = config.channelExpansion?.alternateLineupCopies;
        const copies = Number.isFinite(raw) ? Math.floor(Number(raw)) : 1;
        alternateCopies = Math.min(3, Math.max(1, copies));
    }
    const withAlternateLineups: PendingChannel[] = [];
    for (const channel of baseOrdered) {
        const baseChannel: PendingChannel = {
            ...channel,
            lineupReplicaIndex: channel.lineupReplicaIndex ?? 0,
            isPlaybackModeVariant: false,
        };
        withAlternateLineups.push(baseChannel);

        if (alternateCopies <= 0 || baseChannel.playbackMode === 'sequential') {
            continue;
        }
        for (let replicaIndex = 1; replicaIndex <= alternateCopies; replicaIndex++) {
            withAlternateLineups.push({
                ...baseChannel,
                name: `${baseChannel.name} (${replicaIndex + 1})`,
                shuffleSeed: seedFor(`${createChannelIdentityKey(baseChannel)}:replica:${replicaIndex}`),
                lineupReplicaIndex: replicaIndex,
                isPlaybackModeVariant: false,
            });
        }
    }

    if (diagnostics) {
        diagnostics.afterAlternateLineups = countChannelsByStrategy(withAlternateLineups);
    }

    const variantTypeRaw = config.channelExpansion?.variantType;
    const variantType =
        variantTypeRaw === 'sequential' || variantTypeRaw === 'block'
            ? variantTypeRaw
            : 'none';
    const variantBlockSize = sanitizeBlockSize(config.channelExpansion?.variantBlockSize, 3);
    const withVariants: PendingChannel[] = [...withAlternateLineups];
    if (variantType !== 'none') {
        const variantLabel = variantType === 'sequential' ? 'Sequential' : 'Block';
        for (const channel of withAlternateLineups) {
            const isSeriesDerived = isSeriesDerivedChannel(channel, showLibraryIds);
            if (!isSeriesDerived) {
                continue;
            }
            const sameMode = channel.playbackMode === variantType;
            const sameBlockSize =
                variantType !== 'block' || channel.blockSize === variantBlockSize;
            if (sameMode && sameBlockSize) {
                continue;
            }
            const variant: PendingChannel = {
                ...channel,
                name: `${channel.name} • ${variantLabel}`,
                playbackMode: variantType,
                // Marks this as a setup-generated playback-mode variant (sequential/block) for identity/diffing.
                isPlaybackModeVariant: true,
                shuffleSeed: seedFor(`${createChannelIdentityKey(channel)}:variant:${variantType}`),
            };
            if (variantType === 'block') {
                variant.blockSize = variantBlockSize;
            } else {
                delete variant.blockSize;
            }
            withVariants.push(variant);
        }
    }

    if (diagnostics) {
        diagnostics.afterVariants = countChannelsByStrategy(withVariants);
    }

    const pending = withVariants.slice(0, effectiveMaxChannels);
    const reachedMaxChannels = withVariants.length > effectiveMaxChannels;
    const estimates = createEmptyChannelSetupEstimates();
    for (const channel of pending) {
        estimates.total += 1;
        const strategyKey = channel.buildStrategy as keyof ChannelSetupEstimates | undefined;
        if (!strategyKey || strategyKey === 'total') {
            continue;
        }
        if (strategyKey in estimates) {
            estimates[strategyKey] += 1;
        }
    }

    if (diagnostics) {
        diagnostics.afterMaxChannels = { ...estimates };
        diagnostics.lostToMaxChannels = subtractEstimates(diagnostics.afterVariants, diagnostics.afterMaxChannels);
    }

    return {
        plan: {
            pendingChannels: pending,
            estimates,
            warnings: [...warnings],
            skipped,
            reachedMaxChannels,
        },
        ...(diagnostics ? { diagnostics } : {}),
    };
}

export function createChannelIdentityKey(candidate: ChannelIdentityCandidate): string {
    // Identity keys are used to match planned channels to existing channels in merge/append flows.
    // Intentionally exclude mutable playback settings like `blockSize` so changing those settings
    // updates an existing channel rather than creating a duplicate.
    const normalized = {
        source: normalizeSource(candidate.contentSource),
        filters: normalizeFilters(candidate.contentFilters),
        sortOrder: candidate.sortOrder ?? null,
        lineupReplicaIndex: candidate.lineupReplicaIndex ?? 0,
        isPlaybackModeVariant: candidate.isPlaybackModeVariant === true,
        variantPlaybackMode: candidate.isPlaybackModeVariant === true ? candidate.playbackMode : null,
    };
    return stableStringify(normalized);
}

export function diffChannelPlans(
    existingChannels: ChannelConfig[],
    plannedChannels: PendingChannel[]
): ChannelDiffResult {
    const plannedByKey = new Map<string, PendingChannel[]>();
    for (const planned of plannedChannels) {
        const key = createChannelIdentityKey(planned);
        const list = plannedByKey.get(key) ?? [];
        list.push(planned);
        plannedByKey.set(key, list);
    }

    const created: ChannelDiffEntry[] = [];
    const removed: ChannelDiffEntry[] = [];
    const unchanged: ChannelDiffEntry[] = [];
    const matchedPairs: Array<{ existing: ChannelConfig; planned: PendingChannel }> = [];

    const consumePlanned = (key: string): PendingChannel | null => {
        const list = plannedByKey.get(key);
        if (!list || list.length === 0) return null;
        return list.shift() ?? null;
    };

    for (const existing of existingChannels) {
        const key = createChannelIdentityKey(existing);
        const planned = consumePlanned(key);
        if (planned) {
            matchedPairs.push({ existing, planned });
            const entry: ChannelDiffEntry = {
                name: existing.name,
                identityKey: key,
                channelId: existing.id,
                number: existing.number,
            };
            if (existing.isAutoGenerated !== undefined) {
                entry.isAutoGenerated = existing.isAutoGenerated;
            }
            unchanged.push(entry);
        } else {
            const entry: ChannelDiffEntry = {
                name: existing.name,
                identityKey: key,
                channelId: existing.id,
                number: existing.number,
            };
            if (existing.isAutoGenerated !== undefined) {
                entry.isAutoGenerated = existing.isAutoGenerated;
            }
            removed.push(entry);
        }
    }

    for (const [key, remaining] of plannedByKey.entries()) {
        for (const planned of remaining) {
            const entry: ChannelDiffEntry = {
                name: planned.name,
                identityKey: key,
            };
            if (planned.isAutoGenerated !== undefined) {
                entry.isAutoGenerated = planned.isAutoGenerated;
            }
            created.push(entry);
        }
    }

    const summary = {
        created: created.length,
        removed: removed.length,
        unchanged: unchanged.length,
    };
    const samples = {
        created: created.slice(0, 6).map((c) => c.name),
        removed: removed.slice(0, 6).map((c) => c.name),
        unchanged: unchanged.slice(0, 6).map((c) => c.name),
    };

    return { created, removed, unchanged, matchedPairs, summary, samples };
}

function buildFacetCountDiagnostics(
    library: PlexLibrarySection,
    tags: PlexTagDirectoryItem[],
    minItems: number
): ChannelSetupPlannerFacetCountDiagnostics {
    const knownCounts = sortTagValuesByCountThenTitle(
        tags
            .filter((tag): tag is PlexTagDirectoryItem & { count: number } => tag.count !== null)
            .map((tag) => ({ title: tag.title, count: tag.count }))
    );
    const unknownCountTitles = sortTagTitles(
        tags
            .filter((tag) => tag.count === null)
            .map((tag) => tag.title)
    );
    const belowMinItems = knownCounts.filter((tag) => tag.count < minItems);

    return {
        libraryId: library.id,
        libraryName: library.title,
        rawTagCount: tags.length,
        effectiveCandidateCount: tags.length,
        candidatesWithKnownCount: knownCounts.length,
        candidatesWithUnknownCount: unknownCountTitles.length,
        candidatesBelowMinItems: belowMinItems.length,
        minKnownCount: knownCounts.length > 0 ? knownCounts[knownCounts.length - 1]?.count ?? null : null,
        maxKnownCount: knownCounts.length > 0 ? knownCounts[0]?.count ?? null : null,
        sampleKnownCounts: toCountSamples(knownCounts),
        sampleUnknownCountTitles: unknownCountTitles.slice(0, 5),
        sampleBelowMinItems: toCountSamples(belowMinItems),
    };
}

function buildDecadeFacetCountDiagnostics(
    library: PlexLibrarySection,
    yearTags: PlexTagDirectoryItem[],
    minItems: number
): ChannelSetupPlannerFacetCountDiagnostics {
    const decades = new Map<number, { totalCount: number; hasUnknownCount: boolean }>();

    for (const yearTag of yearTags) {
        const decade = toChannelSetupDecadeValue(yearTag.title);
        if (decade === null) {
            continue;
        }
        const entry = decades.get(decade) ?? { totalCount: 0, hasUnknownCount: false };
        if (yearTag.count === null) {
            entry.hasUnknownCount = true;
        } else {
            entry.totalCount += yearTag.count;
        }
        decades.set(decade, entry);
    }

    const knownCounts = sortTagValuesByCountThenTitle(
        Array.from(decades.entries())
            .filter(([, entry]) => entry.hasUnknownCount === false)
            .map(([decade, entry]) => ({ title: formatDecadeLabel(decade), count: entry.totalCount }))
    );
    const unknownCountTitles = sortTagTitles(
        Array.from(decades.entries())
            .filter(([, entry]) => entry.hasUnknownCount === true)
            .map(([decade]) => formatDecadeLabel(decade))
    );
    const belowMinItems = knownCounts.filter((tag) => tag.count < minItems);

    return {
        libraryId: library.id,
        libraryName: library.title,
        rawTagCount: yearTags.length,
        effectiveCandidateCount: decades.size,
        candidatesWithKnownCount: knownCounts.length,
        candidatesWithUnknownCount: unknownCountTitles.length,
        candidatesBelowMinItems: belowMinItems.length,
        minKnownCount: knownCounts.length > 0 ? knownCounts[knownCounts.length - 1]?.count ?? null : null,
        maxKnownCount: knownCounts.length > 0 ? knownCounts[0]?.count ?? null : null,
        sampleKnownCounts: toCountSamples(knownCounts),
        sampleUnknownCountTitles: unknownCountTitles.slice(0, 5),
        sampleBelowMinItems: toCountSamples(belowMinItems),
    };
}

function createPlannerDiagnostics(
    selectedLibraries: PlexLibrarySection[],
    genresByLibraryId: Map<string, PlexTagDirectoryItem[]>,
    directorsByLibraryId: Map<string, PlexTagDirectoryItem[]>,
    yearsByLibraryId: Map<string, PlexTagDirectoryItem[]>,
    actorsByLibraryId: Map<string, PlexTagDirectoryItem[]>,
    studiosByLibraryId: Map<string, PlexTagDirectoryItem[]>,
    effectiveMaxChannels: number,
    minItems: number
): ChannelSetupPlannerDiagnostics {
    const toCounts = (
        valuesByLibraryId: Map<string, PlexTagDirectoryItem[]>
    ): ChannelSetupPlannerLibraryCount[] => selectedLibraries.map((library) => ({
        libraryId: library.id,
        libraryName: library.title,
        count: valuesByLibraryId.get(library.id)?.length ?? 0,
    }));
    const toFacetCountDiagnostics = (
        valuesByLibraryId: Map<string, PlexTagDirectoryItem[]>
    ): ChannelSetupPlannerFacetCountDiagnostics[] => selectedLibraries.map((library) =>
        buildFacetCountDiagnostics(library, valuesByLibraryId.get(library.id) ?? [], minItems)
    );
    const toDecadeFacetCountDiagnostics = (): ChannelSetupPlannerFacetCountDiagnostics[] => selectedLibraries.map((library) =>
        buildDecadeFacetCountDiagnostics(library, yearsByLibraryId.get(library.id) ?? [], minItems)
    );

    return {
        effectiveMaxChannels,
        minItems,
        fetchedTagsByFamily: {
            genres: toCounts(genresByLibraryId),
            directors: toCounts(directorsByLibraryId),
            decades: toCounts(yearsByLibraryId),
            studios: toCounts(studiosByLibraryId),
            actors: toCounts(actorsByLibraryId),
        },
        tagCountDiagnosticsByFamily: {
            genres: toFacetCountDiagnostics(genresByLibraryId),
            directors: toFacetCountDiagnostics(directorsByLibraryId),
            decades: toDecadeFacetCountDiagnostics(),
            studios: toFacetCountDiagnostics(studiosByLibraryId),
            actors: toFacetCountDiagnostics(actorsByLibraryId),
        },
        candidatesBeforeMinItems: createEmptyChannelSetupEstimates(),
        candidatesAfterMinItems: createEmptyChannelSetupEstimates(),
        strategyBucketSizes: createEmptyChannelSetupEstimates(),
        afterAlternateLineups: createEmptyChannelSetupEstimates(),
        afterVariants: createEmptyChannelSetupEstimates(),
        afterMaxChannels: createEmptyChannelSetupEstimates(),
        lostToMaxChannels: createEmptyChannelSetupEstimates(),
    };
}

function countChannelsByStrategy(channels: PendingChannel[]): ChannelSetupEstimates {
    const estimates = createEmptyChannelSetupEstimates();
    for (const channel of channels) {
        estimates.total += 1;
        const strategyKey = channel.buildStrategy as SetupStrategyKey | undefined;
        if (!strategyKey) {
            continue;
        }
        estimates[strategyKey] += 1;
    }
    return estimates;
}

function subtractEstimates(
    source: ChannelSetupEstimates,
    removed: ChannelSetupEstimates
): ChannelSetupEstimates {
    return {
        total: Math.max(0, source.total - removed.total),
        collections: Math.max(0, source.collections - removed.collections),
        playlists: Math.max(0, source.playlists - removed.playlists),
        genres: Math.max(0, source.genres - removed.genres),
        directors: Math.max(0, source.directors - removed.directors),
        decades: Math.max(0, source.decades - removed.decades),
        recentlyAdded: Math.max(0, source.recentlyAdded - removed.recentlyAdded),
        studios: Math.max(0, source.studios - removed.studios),
        actors: Math.max(0, source.actors - removed.actors),
    };
}

function normalizeFilters(filters?: ContentFilter[]): Array<ContentFilter> | null {
    if (!filters || filters.length === 0) return null;
    return [...filters].sort((a, b) => {
        const aKey = `${a.field}:${a.operator}:${String(a.value)}`;
        const bKey = `${b.field}:${b.operator}:${String(b.value)}`;
        return aKey.localeCompare(bKey);
    });
}

function normalizeSource(source: ChannelConfig['contentSource']): unknown {
    switch (source.type) {
        case 'library':
            return {
                type: source.type,
                libraryId: source.libraryId,
                libraryType: source.libraryType,
                includeWatched: source.includeWatched,
                libraryFilter: normalizeRecord(source.libraryFilter),
            };
        case 'collection':
            return { type: source.type, collectionKey: source.collectionKey };
        case 'playlist':
            return { type: source.type, playlistKey: source.playlistKey };
        case 'show':
            return {
                type: source.type,
                showKey: source.showKey,
                seasonFilter: source.seasonFilter ? [...source.seasonFilter].sort((a, b) => a - b) : null,
            };
        case 'manual':
            return {
                type: source.type,
                items: [...source.items].sort((a, b) => a.ratingKey.localeCompare(b.ratingKey)),
            };
        case 'mixed': {
            const normalizedSources = source.sources.map(normalizeSource);
            const sortedSources = [...normalizedSources].sort((a, b) => stableStringify(a).localeCompare(stableStringify(b)));
            return { type: source.type, mixMode: source.mixMode, sources: sortedSources };
        }
        default:
            return source;
    }
}

function normalizeRecord(record?: Record<string, string | number>): Record<string, string | number> | null {
    if (!record) return null;
    const entries = Object.entries(record).sort(([a], [b]) => a.localeCompare(b));
    const normalized: Record<string, string | number> = {};
    for (const [key, value] of entries) {
        normalized[key] = value;
    }
    return normalized;
}

function stableStringify(value: unknown): string {
    if (value === null || typeof value !== 'object') {
        return JSON.stringify(value);
    }
    if (Array.isArray(value)) {
        return `[${value.map(stableStringify).join(',')}]`;
    }
    const obj = value as Record<string, unknown>;
    const keys = Object.keys(obj).sort((left, right) => left.localeCompare(right));
    const entries = keys.map((key) => `${JSON.stringify(key)}:${stableStringify(obj[key])}`);
    return `{${entries.join(',')}}`;
}
